03-1. 라이브러리 불러오기 및 경로 설정
1. 이 단계의 목적

03번 노트북에서 사용할 기본 라이브러리를 불러오고, Google Drive 안의 입력 파일 경로와 산출물 저장 폴더 경로를 설정합니다.

이 단계에서는 데이터를 아직 불러오지 않습니다.
먼저 경로가 올바른지, 출력 폴더를 어디에 만들 것인지 확인하는 단계입니다.

생성할 변수 또는 출력

이 셀에서 생성하는 주요 변수는 다음입니다.


| 변수명                  | 의미                      |
| -------------------- | ----------------------- |
| `DRIVE_ROOT`         | Google Drive의 기본 경로     |
| `PROJECT_OUTPUT_DIR` | 프로젝트 중간결과표 상위 폴더        |
| `INPUT_DIR`          | 01번 V1 분석데이터 폴더         |
| `OUTPUT_DIR`         | 03번 사업명 텍스트 분석 산출물 폴더   |
| `TABLE_DIR`          | 03번 결과표 저장 폴더           |
| `FIGURE_DIR`         | 03번 그림 저장 폴더            |
| `INPUT_FILE`         | 03번 입력 parquet 파일 전체 경로 |

1. 먼저 Drive 최상위 폴더를 확인

내 드라이브 최상위 폴더 목록 확인

In [ ]:
from pathlib import Path
from google.colab import drive
drive.mount('/content/drive')

drive_root = Path('/content/drive')

print("drive_root 존재 여부:", drive_root.exists())

print("\n/content/drive 하위 폴더:")
for p in drive_root.iterdir():
    print(p)

Mounted at /content/drive
drive_root 존재 여부: True

/content/drive 하위 폴더:
/content/drive/.shortcut-targets-by-id
/content/drive/MyDrive
/content/drive/.Trash-0
/content/drive/.Encrypted

2. 내 드라이브 최상위 폴더 목록 확인

In [ ]:
from pathlib import Path

mydrive = Path('/content/drive/MyDrive')

print("MyDrive 존재 여부:", mydrive.exists())

print("\nMyDrive 최상위 폴더 목록:")
for p in mydrive.iterdir():
    if p.is_dir():
        print(p.name)

MyDrive 존재 여부: True

MyDrive 최상위 폴더 목록:
Colab Notebooks
환경정책거버넌스
[guide & output] 분석 협업 매뉴얼 및 Figure 후보
파공장 (PA Factory)

In [ ]:
from pathlib import Path

MYDRIVE = Path('/content/drive/MyDrive')

# MyDrive 최상위에서 [guide & output]으로 시작하는 폴더 자동 탐색
guide_candidates = [
    p for p in MYDRIVE.iterdir()
    if p.is_dir() and p.name.startswith('[guide & output]')
]

print("검색된 [guide & output] 후보 폴더 수:", len(guide_candidates))

for i, p in enumerate(guide_candidates, start=1):
    print(f"{i}. {p}")
    print("   폴더명 repr:", repr(p.name))

# 후보가 1개라면 프로젝트 출력 폴더로 지정
if len(guide_candidates) == 1:
    GUIDE_OUTPUT_DIR = guide_candidates[0]
    print("\nGUIDE_OUTPUT_DIR로 설정:", GUIDE_OUTPUT_DIR)

    print("\nGUIDE_OUTPUT_DIR 하위 폴더 목록:")
    for child in GUIDE_OUTPUT_DIR.iterdir():
        if child.is_dir():
            print("-", child.name)
else:
    print("\n후보가 0개이거나 2개 이상입니다. 위 출력 결과를 확인해야 합니다.")

검색된 [guide & output] 후보 폴더 수: 1
1. /content/drive/MyDrive/[guide & output] 분석 협업 매뉴얼 및 Figure 후보
   폴더명 repr: '[guide & output] 분석 협업 매뉴얼 및 Figure 후보'

GUIDE_OUTPUT_DIR로 설정: /content/drive/MyDrive/[guide & output] 분석 협업 매뉴얼 및 Figure 후보

GUIDE_OUTPUT_DIR 하위 폴더 목록:
- 03_중간결과표

공유문서함 찾기

In [ ]:
from pathlib import Path

MYDRIVE = Path('/content/drive/MyDrive')

# MyDrive 안에서 파공장 폴더 자동 탐색
pa_candidates = [
    p for p in MYDRIVE.iterdir()
    if p.is_dir() and 'PA Factory' in p.name
]

print("파공장 후보 폴더 수:", len(pa_candidates))

for i, p in enumerate(pa_candidates, start=1):
    print(f"{i}. {p}")
    print("   폴더명 repr:", repr(p.name))

if len(pa_candidates) == 1:
    PA_FACTORY_DIR = pa_candidates[0]
    print("\nPA_FACTORY_DIR:", PA_FACTORY_DIR)

    matches = list(PA_FACTORY_DIR.rglob('*all_clean_data_v1*'))

    print("\n검색된 all_clean_data_v1 관련 파일 수:", len(matches))
    for path in matches:
        print(path)
else:
    print("\n파공장 폴더가 없거나 여러 개입니다. 위 목록을 확인하세요.")

파공장 후보 폴더 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)
   폴더명 repr: '파공장 (PA Factory)'

PA_FACTORY_DIR: /content/drive/MyDrive/파공장 (PA Factory)

검색된 all_clean_data_v1 관련 파일 수: 5
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/02_v1_파트너유형분석/02_all_clean_data_v1_partner_type_20260523_1854_KST.parquet
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/02_v1_파트너유형분석/02_all_clean_data_v1_partner_type_20260523_1854_KST.xlsx
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.xlsx
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_병합요약_20260523_0100_KST.xlsx

In [ ]:
# 03-1. 라이브러리 불러오기 및 경로 설정

# ------------------------------------------------------------
# 0) 기본 라이브러리 불러오기
# ------------------------------------------------------------

import os
import re
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

from google.colab import drive

# Google Drive 마운트
drive.mount('/content/drive', force_remount=True)

# ------------------------------------------------------------
# 1) MyDrive에서 파공장(PA Factory) 폴더 찾기
# ------------------------------------------------------------

MYDRIVE = Path('/content/drive/MyDrive')

pa_candidates = [
    p for p in MYDRIVE.iterdir()
    if p.is_dir() and 'PA Factory' in p.name
]

print("파공장 후보 폴더 수:", len(pa_candidates))

for i, p in enumerate(pa_candidates, start=1):
    print(f"{i}. {p}")
    print("   폴더명 repr:", repr(p.name))

if len(pa_candidates) != 1:
    raise FileNotFoundError(
        "파공장(PA Factory) 폴더를 정확히 1개 찾지 못했습니다. "
        "Google Drive 바로가기 추가 여부와 폴더명을 확인하세요."
    )

PA_FACTORY_DIR = pa_candidates[0]

# ------------------------------------------------------------
# 2) 03번 입력 파일 찾기
# ------------------------------------------------------------

target_file_name = 'all_clean_data_v1_20260523_0054_KST.parquet'

input_candidates = list(PA_FACTORY_DIR.rglob(target_file_name))

print("\n입력 파일 후보 수:", len(input_candidates))

for i, p in enumerate(input_candidates, start=1):
    print(f"{i}. {p}")

if len(input_candidates) != 1:
    raise FileNotFoundError(
        f"{target_file_name} 파일을 정확히 1개 찾지 못했습니다. "
        "파일명 또는 Drive 위치를 확인하세요."
    )

INPUT_FILE = input_candidates[0]
INPUT_DIR = INPUT_FILE.parent

# 입력 파일 구조:
# 03_중간결과표 / 01_v1_분석데이터 / all_clean_data_v1...
# 따라서 03_중간결과표 폴더는 INPUT_DIR의 부모 폴더입니다.
PROJECT_OUTPUT_DIR = INPUT_DIR.parent

# ------------------------------------------------------------
# 3) 03번 산출물 폴더 설정
# ------------------------------------------------------------

OUTPUT_DIR = PROJECT_OUTPUT_DIR / '03_v1_사업명텍스트분석'
TABLE_DIR = OUTPUT_DIR / 'tables'
FIGURE_DIR = OUTPUT_DIR / 'figures'

# 입력 파일이 확인된 뒤에만 출력 폴더 생성
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 4) 경로 확인 출력
# ------------------------------------------------------------

print("\n경로 설정 완료")
print("PA_FACTORY_DIR:", PA_FACTORY_DIR)
print("PROJECT_OUTPUT_DIR:", PROJECT_OUTPUT_DIR)
print("INPUT_DIR:", INPUT_DIR)
print("INPUT_FILE:", INPUT_FILE)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("TABLE_DIR:", TABLE_DIR)
print("FIGURE_DIR:", FIGURE_DIR)

print("\n입력 파일 존재 여부:", INPUT_FILE.exists())
print("03번 산출물 폴더 존재 여부:", OUTPUT_DIR.exists())

Mounted at /content/drive
파공장 후보 폴더 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)
   폴더명 repr: '파공장 (PA Factory)'

입력 파일 후보 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet

경로 설정 완료
PA_FACTORY_DIR: /content/drive/MyDrive/파공장 (PA Factory)
PROJECT_OUTPUT_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표
INPUT_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터
INPUT_FILE: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet
OUTPUT_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석
TABLE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables
FIGURE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/figures

입력 파일 존재 여부: True
03번 산출물 폴더 존재 여부: True

03-2 코드 실행 단계

In [ ]:
INPUT_FILE

PosixPath('/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet')

생성할 변수 또는 출력
| 변수명               | 의미                  |
| ----------------- | ------------------- |
| `df`              | V1 원본 분석 데이터        |
| `required_for_03` | 03번 분석에 필요한 핵심 열 목록 |
| `missing_for_03`  | 03번 핵심 열 중 누락된 열 목록 |
이 단계에서는 원본 데이터프레임 df만 생성하고, 아직 새로운 분석 열은 만들지 않습니다.

In [ ]:
# 03-2. V1 데이터 불러오기 및 기본 구조 확인

# ------------------------------------------------------------
# 1) V1 parquet 데이터 불러오기
# ------------------------------------------------------------

df = pd.read_parquet(INPUT_FILE)

# ------------------------------------------------------------
# 2) 전체 구조 확인
# ------------------------------------------------------------

print("V1 데이터 불러오기 완료")
print("- 행 수:", df.shape[0])
print("- 열 수:", df.shape[1])

print("\n열 이름 목록:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i:02d}. {col}")

# ------------------------------------------------------------
# 3) 03번 사업명 텍스트 분석에 필요한 핵심 열 확인
# ------------------------------------------------------------

required_for_03 = ['사업명']
missing_for_03 = [col for col in required_for_03 if col not in df.columns]

print("\n03번 핵심 열 확인")
print("- 필요한 열:", required_for_03)
print("- 누락된 열:", missing_for_03)

if missing_for_03:
    raise ValueError(f"03번 분석에 필요한 핵심 열이 없습니다: {missing_for_03}")

# ------------------------------------------------------------
# 4) 사업명 열의 기본 상태 확인
# ------------------------------------------------------------

total_rows = len(df)
missing_project_name = df['사업명'].isna().sum()
blank_project_name = df['사업명'].astype(str).str.strip().eq('').sum()

print("\n사업명 열 기본 상태")
print("- 전체 행 수:", total_rows)
print("- 사업명 결측 행 수:", missing_project_name)
print("- 사업명 공백 문자열 행 수:", blank_project_name)
print("- 사업명 결측 비율:", round(missing_project_name / total_rows * 100, 2), "%")
print("- 사업명 공백 문자열 비율:", round(blank_project_name / total_rows * 100, 2), "%")

# ------------------------------------------------------------
# 5) 참고 열 결측 상태 확인
# ------------------------------------------------------------
# 주의:
# 03번에서는 평가종류, 사업비합계, 보조금, 사업자부담 결측을 이유로 행을 제외하지 않습니다.
# 다만 V1 데이터 상태 이해를 위해 참고용으로만 확인합니다.

reference_cols = ['평가종류', '사업비합계', '보조금', '사업자부담']
existing_reference_cols = [col for col in reference_cols if col in df.columns]

print("\n참고 열 결측 상태")
print("※ 아래 열의 결측은 03번 사업명 텍스트 분석에서 행 제외 기준으로 사용하지 않습니다.")

if existing_reference_cols:
    reference_missing_summary = (
        df[existing_reference_cols]
        .isna()
        .sum()
        .reset_index()
    )
    reference_missing_summary.columns = ['열 이름', '결측 행 수']
    reference_missing_summary['전체 행 수'] = total_rows
    reference_missing_summary['결측 비율(%)'] = (
        reference_missing_summary['결측 행 수'] / total_rows * 100
    ).round(2)

    display(reference_missing_summary)
else:
    print("참고 열이 현재 데이터에 없습니다:", reference_cols)

# ------------------------------------------------------------
# 6) 사업명 샘플 확인
# ------------------------------------------------------------

print("\n사업명 샘플 20개")
display(
    df[['사업명']]
    .head(20)
)

V1 데이터 불러오기 완료
- 행 수: 79276
- 열 수: 12

열 이름 목록:
01. 시도
02. 지자체명
03. 파일상태
04. 원파일명
05. 파일경로
06. 사업명
07. 보조사업자
08. 사업비합계
09. 보조금
10. 사업자부담
11. 평가결과
12. 평가종류

03번 핵심 열 확인
- 필요한 열: ['사업명']
- 누락된 열: []

사업명 열 기본 상태
- 전체 행 수: 79276
- 사업명 결측 행 수: 14
- 사업명 공백 문자열 행 수: 0
- 사업명 결측 비율: 0.02 %
- 사업명 공백 문자열 비율: 0.0 %

참고 열 결측 상태
※ 아래 열의 결측은 03번 사업명 텍스트 분석에서 행 제외 기준으로 사용하지 않습니다.

    열 이름  결측 행 수  전체 행 수  결측 비율(%)
0   평가종류    1479   79276      1.87
1  사업비합계    2684   79276      3.39
2    보조금    4190   79276      5.29
3  사업자부담    9815   79276     12.38

사업명 샘플 20개

                                     사업명
0                          마늘재배 영농지원단 지원
1      2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영
2                   자유민주주의신장 및 자유선진의식 고취
3                            보물섬 독서학교 지원
4                           참전경찰유공자 보훈활동
5                          무공수훈자회 운영비 보조
6                              행복나눔센터 운영
7                           경로당 양곡구입비 지원
8                           장애인직업재활 자활교육
9              어린이집 운전기사 인건비 (미조지역영유아수송)
10                           아동 일일나들이 행사
11                               문화학교 운영
12                         남중권생활체육 교류 지원
13               전국대회 운영(구급차, 응급의료 등) 지원
14                         레포츠 자격증 취득 지원
15                         수산물 상생할인 지원사업
16                               마을어장 개발
17       자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회)
18  2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원)
19           농촌신활력 플러스사업 (추진단사무국상근직원인건비)

03-3. 사업명 원자료 기본 점검
1. 이 단계의 목적

이 단계는 원본 사업명 열을 수정하지 않고, 텍스트 분석 전에 확인해야 할 기초 문제를 점검하는 단계입니다.

주로 다음을 확인합니다.

사업명 결측 14행이 어떤 행인지
사업명 길이가 지나치게 짧거나 긴 사례가 있는지
줄바꿈, 탭, 중복 공백, 앞뒤 공백이 있는지
합계, 소계, 총계 같은 합계행 의심 사례가 있는지
동일한 사업명이 얼마나 반복되는지

아직 사업명_clean은 만들지 않습니다.

In [ ]:
# 03-3. 사업명 원자료 기본 점검

# ------------------------------------------------------------
# 1) 원본 사업명 열을 확인용 변수로 분리
# ------------------------------------------------------------
# 주의:
# project_name_raw는 원본 df['사업명']을 참조하는 변수입니다.
# 이 단계에서는 df['사업명'] 값을 절대 수정하지 않습니다.

project_name_raw = df['사업명']

# 결측값은 확인 편의를 위해 임시로 빈 문자열로 바꿉니다.
# 이 변수는 진단용이며, 원본 df에는 영향을 주지 않습니다.
project_name_text = project_name_raw.fillna('').astype(str)

# 앞뒤 공백을 제거한 임시 텍스트
project_name_stripped = project_name_text.str.strip()

total_rows = len(df)

print("03-3. 사업명 원자료 기본 점검")
print("- 전체 행 수:", total_rows)
print("- 원본 사업명 열 수정 여부: 수정하지 않음")


# ------------------------------------------------------------
# 2) 결측 및 공백 사업명 행 확인
# ------------------------------------------------------------

missing_mask = project_name_raw.isna()
blank_mask = project_name_raw.notna() & project_name_stripped.eq('')

missing_or_blank_mask = missing_mask | blank_mask

# 확인할 때 같이 보면 좋은 열들만 선택합니다.
# 데이터에 없는 열은 자동으로 제외됩니다.
context_cols = [
    '시도', '시군구', '지자체명', '지자체유형',
    '원본파일명', 'source_file', 'file_name',
    '사업명', '보조사업자', '평가결과', '평가종류',
    '사업비합계', '보조금', '사업자부담'
]

existing_context_cols = [col for col in context_cols if col in df.columns]

missing_project_name_rows = df.loc[missing_or_blank_mask, existing_context_cols].copy()

print("\n[1] 사업명 결측/공백 행")
print("- 사업명 결측 행 수:", int(missing_mask.sum()))
print("- 사업명 공백 문자열 행 수:", int(blank_mask.sum()))
print("- 결측 또는 공백 전체 행 수:", len(missing_project_name_rows))

display(missing_project_name_rows.head(30))


# ------------------------------------------------------------
# 3) 사업명 길이 분포 확인
# ------------------------------------------------------------

# 결측/공백이 아닌 사업명만 대상으로 길이 계산
valid_project_name = project_name_stripped[~missing_or_blank_mask]
project_name_length = valid_project_name.str.len()

print("\n[2] 사업명 길이 분포")
display(project_name_length.describe().to_frame(name='사업명_글자수'))

# 너무 짧은 사업명 후보
# 기준은 우선 3글자 이하로 잡고, 실제 사례를 본 뒤 조정할 수 있습니다.
short_mask = (~missing_or_blank_mask) & (project_name_stripped.str.len() <= 3)
short_project_name_rows = df.loc[short_mask, existing_context_cols].copy()

print("\n[3] 너무 짧은 사업명 후보")
print("- 3글자 이하 사업명 수:", len(short_project_name_rows))
display(short_project_name_rows.head(30))

# 너무 긴 사업명 후보
# 기준은 우선 80글자 이상으로 잡고, 실제 사례를 본 뒤 조정할 수 있습니다.
long_mask = (~missing_or_blank_mask) & (project_name_stripped.str.len() >= 80)
long_project_name_rows = df.loc[long_mask, existing_context_cols].copy()

print("\n[4] 너무 긴 사업명 후보")
print("- 80글자 이상 사업명 수:", len(long_project_name_rows))
display(long_project_name_rows.head(30))


# ------------------------------------------------------------
# 4) 공백·줄바꿈·탭 등 기본 형식 문제 확인
# ------------------------------------------------------------

newline_mask = project_name_text.str.contains(r'\n|\r', regex=True, na=False)
tab_mask = project_name_text.str.contains(r'\t', regex=True, na=False)
multi_space_mask = project_name_text.str.contains(r' {2,}', regex=True, na=False)
leading_trailing_space_mask = project_name_raw.notna() & (project_name_text != project_name_stripped)

# 특수 따옴표나 이상한 공백 후보
# 예: ‘ ’ “ ”, non-breaking space(\u00A0)
special_quote_mask = project_name_text.str.contains(r'[‘’“”]', regex=True, na=False)
nbsp_mask = project_name_text.str.contains('\u00A0', regex=False, na=False)

issue_summary = pd.DataFrame({
    '점검항목': [
        '사업명 결측',
        '사업명 공백 문자열',
        '줄바꿈 포함',
        '탭 포함',
        '연속 공백 2칸 이상 포함',
        '앞뒤 공백 포함',
        '특수 따옴표 포함',
        'NBSP 특수공백 포함'
    ],
    '행 수': [
        int(missing_mask.sum()),
        int(blank_mask.sum()),
        int(newline_mask.sum()),
        int(tab_mask.sum()),
        int(multi_space_mask.sum()),
        int(leading_trailing_space_mask.sum()),
        int(special_quote_mask.sum()),
        int(nbsp_mask.sum())
    ]
})

issue_summary['전체 대비 비율(%)'] = (issue_summary['행 수'] / total_rows * 100).round(3)

print("\n[5] 사업명 기본 형식 문제 요약")
display(issue_summary)


# ------------------------------------------------------------
# 5) 형식 문제별 샘플 확인
# ------------------------------------------------------------

def show_issue_sample(mask, title, n=10):
    """문제 후보 행을 보기 좋게 출력하는 보조 함수"""
    sample = df.loc[mask, existing_context_cols].head(n).copy()
    print(f"\n{title}")
    print("- 후보 행 수:", int(mask.sum()))
    display(sample)

show_issue_sample(newline_mask, "[샘플] 줄바꿈 포함 사업명")
show_issue_sample(multi_space_mask, "[샘플] 연속 공백 2칸 이상 포함 사업명")
show_issue_sample(leading_trailing_space_mask, "[샘플] 앞뒤 공백 포함 사업명")
show_issue_sample(special_quote_mask, "[샘플] 특수 따옴표 포함 사업명")
show_issue_sample(nbsp_mask, "[샘플] NBSP 특수공백 포함 사업명")


# ------------------------------------------------------------
# 6) 합계행/소계행/총계행 의심 사례 확인
# ------------------------------------------------------------
# 주의:
# 이 단계에서는 실제로 제외하지 않습니다.
# '합계', '소계', '총계'라는 단어가 포함된 사업명이 실제 사업명일 수도 있으므로
# 반드시 사람이 확인해야 합니다.

total_keyword_mask = project_name_text.str.contains(r'합계|소계|총계', regex=True, na=False)
suspected_total_rows = df.loc[total_keyword_mask, existing_context_cols].copy()

print("\n[6] 합계행/소계행/총계행 의심 사례")
print("- 후보 행 수:", len(suspected_total_rows))
display(suspected_total_rows.head(30))


# ------------------------------------------------------------
# 7) 반복 등장 사업명 확인
# ------------------------------------------------------------
# 동일한 사업명이 반복 등장하는 것은 오류일 수도 있고,
# 여러 지자체에서 같은 이름의 사업을 운영한 정상 사례일 수도 있습니다.
# 여기서는 상위 반복 사업명만 확인합니다.

duplicate_project_names = (
    project_name_stripped[~missing_or_blank_mask]
    .value_counts()
    .reset_index()
)

duplicate_project_names.columns = ['사업명', '반복횟수']
duplicate_project_names = duplicate_project_names[duplicate_project_names['반복횟수'] >= 2]

print("\n[7] 반복 등장 사업명 상위 30개")
print("- 2회 이상 반복 등장한 사업명 종류 수:", len(duplicate_project_names))
display(duplicate_project_names.head(30))


# ------------------------------------------------------------
# 8) 다음 단계 판단을 위한 요약 출력
# ------------------------------------------------------------

print("\n03-3 점검 완료")
print("다음 단계로 넘어가기 전에 아래를 확인하세요.")
print("1) 사업명 결측 14행이 실제로 분석 제외 후보인지")
print("2) 줄바꿈/연속공백/앞뒤공백이 사업명_clean에서 정리 가능한 수준인지")
print("3) 합계/소계/총계 후보가 실제 합계행인지")
print("4) 반복 등장 사업명이 오류가 아니라 정상 반복인지")
print("5) 특수 따옴표·특수공백이 정제 규칙에 포함되어야 하는지")

03-3. 사업명 원자료 기본 점검
- 전체 행 수: 79276
- 원본 사업명 열 수정 여부: 수정하지 않음

[1] 사업명 결측/공백 행
- 사업명 결측 행 수: 14
- 사업명 공백 문자열 행 수: 0
- 결측 또는 공백 전체 행 수: 14

       시도 지자체명   사업명                보조사업자  평가결과  평가종류 사업비합계   보조금 사업자부담
16390  서울  금천구  <NA>  (사)서울시지체장애인협회 금천구지회    우수  성과평가  1400  1250   150
17126  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17127  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17235  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17236  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17344  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17345  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17437  서울   본청  <NA>          서울시 25개 자치구  매우우수  <NA>   255   255     -
17453  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17454  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17562  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17563  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17671  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
17672  서울   본청  <NA>                 <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

[2] 사업명 길이 분포

            사업명_글자수
count  79262.000000
mean      15.003772
std        5.578485
min        2.000000
25%       11.000000
50%       14.000000
75%       18.000000
max       95.000000

[3] 너무 짧은 사업명 후보
- 3글자 이하 사업명 수: 64

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
313,경남,산청군,유지비,산청공공스포츠클럽,보통,성과평가,10000,10000,0
1632,경남,양산시,운영비,황전새마을작은도서관 외 44개관,우수,성과평가,111,100,11
7967,경남,창녕군,퇴비사,축산농가,보통,성과평가/유지필요성평가,"75,140","20,000","55,140"
15424,서울,종로구,운영비,청암지역아동센터,보통,성과평가,5959,5959,-
15425,서울,종로구,운영비,세종지역아동센터,보통,성과평가,6000,6000,-
15426,서울,종로구,운영비,성터지역아동센터,보통,성과평가,6000,6000,-
15427,서울,종로구,운영비,종로지역아동센터,보통,성과평가,6000,6000,-
15428,서울,종로구,운영비,마로니에지역아동센터,보통,성과평가,6000,6000,-
15429,서울,종로구,운영비,한누리지역아동센터,보통,성과평가,6000,6000,-
15430,서울,종로구,운영비,중앙지역아동센터,보통,성과평가,6000,6000,-
22348,울산,동구,운영비,울산동구 새마을회,보통,성과평가,49610,45810,3800
22353,울산,동구,운영비,바르게살기운동 울산동구협의회,보통,성과평가,39100,35900,3200
22360,울산,동구,운영비,민주평화통일자문회의 울산동구협의회,보통,성과평가,21740,21740,0
22364,울산,동구,운영비,한국자유총연맹 울산 동구지회,보통,성과평가,27720,26520,1200
22421,울산,동구,운영비,대한민국상이군경회 울산광역시동구지회,우수,성과평가,14820,14820,0
22425,울산,동구,운영비,대한민국 전몰군경유족회 울산광역시동구지회,우수,성과평가,14110,14110,0
22429,울산,동구,운영비,대한민국 전몰군경미망인회 울산광역시동구지회,매우우수,성과평가,13900,13900,0
22433,울산,동구,운영비,대한민국 무공수훈자회 울산광역시동구지회,우수,성과평가,14370,14370,0
22437,울산,동구,운영비,대한민국 6.25참전유공자회 울산광역시동구지회,우수,성과평가,18790,18790,0
22442,울산,동구,운영비,대한민국 고엽제전우회 울산광역시동구지회,우수,성과평가,18490,18490,0
22447,울산,동구,운영비,대한민국 월남전참전자회 울산광역시동구지회,매우우수,성과평가,15960,15960,0
22450,울산,동구,운영비,대한민국 특수임무유공자회 울산광역시동구지회,우수,성과평가,3300,3300,0
22453,울산,동구,운영비,대한민국 재향군인회 울산광역시동구지회,우수,성과평가,10560,10560,0
22483,울산,동구,운영비,(사)울산광역시 지체장애인협회 동구지회,보통,성과평가,35273,31980,3293
22487,울산,동구,운영비,(사)울산광역시 지적발달장애인 복지협회 동구지부,보통,성과평가,11990,10910,1080
22490,울산,동구,운영비,(사)한국시각장애 여성연합 동구지회,보통,유지필요성평가,11210,10910,300
22492,울산,동구,운영비,(사)울산뇌병변장애 인권협회 동구지회,보통,유지필요성평가,10080,8580,1500
25892,충남,부여군,광복회,대한민군 전몰군경유족회 부여군지회,우수,성과평가,11900,11900,0
25899,충남,부여군,인건비,대한민국 월남전참전자회 부여군지회,우수,성과평가,11900,11900,0
25908,충남,부여군,광복회,대한민국 6.25참전유공자회 부여군지회,우수,성과평가,2375,2375,0

[4] 너무 긴 사업명 후보
- 80글자 이상 사업명 수: 2

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
10376,인천,계양구,계양학 마을길 운영 <2021> 계양학학습길운영<2022> 계양학마을길운영<2023...,계양문화원,우수,유지필요성평가,7000,7000,0
10383,인천,계양구,"지역사회보장협의체 운영 동 보장협의체 지역주민복지사업비 지원(2021, 2022) ...",12개 동 보장협의체,우수,유지필요성평가,14000,14000,0

[5] 사업명 기본 형식 문제 요약

             점검항목   행 수  전체 대비 비율(%)
0          사업명 결측    14        0.018
1      사업명 공백 문자열     0        0.000
2          줄바꿈 포함  1346        1.698
3            탭 포함     0        0.000
4  연속 공백 2칸 이상 포함   274        0.346
5        앞뒤 공백 포함   549        0.693
6       특수 따옴표 포함    54        0.068
7    NBSP 특수공백 포함     0        0.000

[샘플] 줄바꿈 포함 사업명
- 후보 행 수: 1346

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
13134,부산,연제구,보훈단체 지원 및 보훈회관 운영 (보훈단체 나라사랑 전적지 순례 지원),연제구 보훈단체장협의회,보통,유지필요성평가,5000,5000,0
13135,부산,연제구,대한노인회 연제구지회 운영 지원 (노인복지사업 추진),대한노인회 연제구지회,보통,유지필요성평가,25000,25000,0
13136,부산,연제구,대한노인회 연제구지회 운영 지원 (대한노인회 운영비),대한노인회 연제구지회,보통,유지필요성평가,6000,6000,0
13141,부산,연제구,연제형 공동육아 사업 (연제형 공동육아 사업 운영),연제 밤골 육아나눔터 외 4개소,보통,유지필요성평가,27000,27000,0
13142,부산,연제구,연제형 공동육아 사업 (연제형 공동육아 사업 공간 조성),연제 밤골 육아나눔터 외 4개소,매우미흡,유지필요성평가,10000,10000,0
13143,부산,연제구,장애인복지사업 추진 (장애인 사회참여 활동지원),연제구 장애인협회,보통,유지필요성평가,15000,12000,3000
13144,부산,연제구,장애인복지사업 추진 (장애인가족 발전전진대회),연제구 장애인협회,매우우수,유지필요성평가,12054,7000,5054
13149,부산,연제구,다행복교육지구 운영 (마을교육공동체 지원사업),아리아리 외 2개 단체,매우미흡,유지필요성평가,15000,15000,0
14282,서울,노원구,"장애인의날기념식 및 장애인복지박람회 장애인무료해변캠프,물놀이행사",노원구장애인총연합회,매우우수,성과평가,43070.0,43070,0.0
14283,서울,노원구,저소득층 청각장애인 문화체험활동 서울시농아인한마음체육대회,(사)서울시농아인협회노원구지회,매우우수,성과평가,8000.0,8000,0.0

[샘플] 연속 공백 2칸 이상 포함 사업명
- 후보 행 수: 274

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
5276,경남,함안군,아라농촌마을재생사업 기본사업비,윤형한 외 11명,매우 우수,성과평가/유지필요성평가,100000,100000,0
5277,경남,함안군,아라농촌마을재생사업 우수마을 상사업비,윤형한 외 5명,매우 우수,성과평가/유지필요성평가,10000,10000,0
5331,경남,함안군,한국미술협회 함안지부 제11회 아름다운 함안전,한국미술협회 함안지부,보통,성과평가/유지필요성평가,4950,4500,450
5402,경남,함안군,보훈단체 등 행사지원 6.25참전유공자회 전적지순례,6.25참전유공자 회 함안군지회,미흡,성과평가/유지필요성평가,3500,3500,0
46832,경기,하남시,새마을운동 하남시지회 각동 협의회 운영비,새마을운동 하남시지회,보통,성과평가,23400,23400,-
46833,경기,하남시,새마을운동 하남시지회 각동 부녀회 운영비,새마을운동 하남시지회,미흡,성과평가,25200,25200,-
46850,경기,하남시,적십자봉사회 저소득 어르신 희망나눔사업 ―어르신 단풍놀이,대한적십자사봉사회 하남지구 협의회,매우미흡,성과평가,-,-,-
46851,경기,하남시,적십자봉사회 저소득 어르신 희망나눔사업 ―어르신 잔치한마당,대한적십자사봉사회 하남지구 협의회,우수,성과평가,5400,4400,1000
46885,경기,하남시,중소기업 노사 한마음 교육문화행사개최,사단법인 하남시 기업인 협의회,우수,성과평가,26270,26270,-
46895,경기,하남시,시군 및 읍면동 지역사회보장협의체활성화 지원사업(자체),하남시지역사회보장협의체,보통,성과평가,8062,8062,-

[샘플] 앞뒤 공백 포함 사업명
- 후보 행 수: 549

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
13766,부산,사상구,공동주택 시설 개선 지원,관내 공동주택 10개소,우수,유지필요성평가,342.9,70.0,272.9
14118,서울,노원구,"동 부녀회(협의회)사업, 김장나누기 등",노원구새마을회,미흡,성과평가/유지필요성평가,94615.0,78000,16615.0
14130,서울,노원구,"국악 버스킹, 풍류(음악회)",노원국악협회,미흡,성과평가/유지필요성평가,3300.0,3000,300.0
14146,서울,노원구,비대면 중심 수어교육,농아인협회,미흡,성과평가/유지필요성평가,7900.0,7000,900.0
14245,서울,노원구,구 지역사회보장협의체 운영,노원구지역사회보장협의체,보통,성과평가,10000.0,10000,<NA>
14328,서울,노원구,어린이집 운영 및 개선,관내 어린이집 280개소,보통,성과평가,4475800.0,4475800,0.0
16461,서울,성북구,대한노인회성북구지회 인건비 지원,(사)대한노인회 성북구지회,보통,성과평가,69583.0,69583,0.0
16755,서울,성북구,동 새마을문고 사업 활성화,새마을문고 성북구지부,미흡,성과평가,66000.0,55000,11000.0
22504,울산,동구,어린이집 급간식비 지원,가온어린이집 외 65개소,매우미흡,유지필요성평가,46800,46800,0
34082,충북,음성군,소규모 식품산업 및 전통주 육성,(이모네)오O순,보통,성과평가/유지필요성,20000000,10000000,10000000

[샘플] 특수 따옴표 포함 사업명
- 후보 행 수: 54

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
1,경남,남해군,2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영,사단법인진주지역범죄피 해자지원센터남해지부,미흡,유지필요성평가,3,3,0
21,경남,남해군,2023년 범죄피해자 지원 및 지원센터‘등불’운영,사)진주지역범죄피해자지 원 센 터 ‘ 등 불 ’,보통,유지필요성평가,22,20,2
834,경남,진주시,지역 문화 진흥 공모사업 (문화자원활용 지원 (별이 빛나는 밤“藝”(예))),새노리,우수,성과평가,20,20,0
3537,경남,거창군,청년동아리‘너나 들이’지원사업,페인팅 메이트 등 6개 동아리,보통,성과평가,10.0,10.0,0.0
8078,경남,본청,“한눈에 보는 진례” 안내지도 만들기(주민참여),김해시,보통,성과평가,<NA>,<NA>,<NA>
8084,경남,본청,"김해시 외동, “걷고 싶은 거리” 조성 사업(주민참여)",김해시,보통,성과평가,<NA>,<NA>,<NA>
8092,경남,본청,‘걷고 싶은 문동저수지’ 달빛 산책로 조성사업(주민참여),거제시,보통,성과평가,<NA>,<NA>,<NA>
8305,경남,본청,경남도민예술단 순회공연 : (함양) 이 땅에 내린 신명 ‘대(竹)광대 유희,함양,미흡,성과평가,<NA>,<NA>,<NA>
8939,경남,본청,“우리 자녀를 위한 감성코칭” 라떼파파 문화예술학교,한국공예문화예술 연합회,미흡,성과평가,<NA>,<NA>,<NA>
8943,경남,본청,이웃 간 마음 거리두기 해제 ‘꽃피는 우리 마을’,맘토닥 마을공동체,미흡,성과평가,<NA>,<NA>,<NA>

[샘플] NBSP 특수공백 포함 사업명
- 후보 행 수: 0

Empty DataFrame
Columns: [시도, 지자체명, 사업명, 보조사업자, 평가결과, 평가종류, 사업비합계, 보조금, 사업자부담]
Index: []

[6] 합계행/소계행/총계행 의심 사례
- 후보 행 수: 2

,시도,지자체명,사업명,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
2606,경남,창원시,봄맞이 꽃바람 축제(소계동 산벚꽃축제),소계동청년회,매우우수,성과평가,16,9,7
59668,경북,영천시,염소계량용저울지원사업,염소농가,미흡,성과평가,11000.0,5500.0,5500.0

[7] 반복 등장 사업명 상위 30개
- 2회 이상 반복 등장한 사업명 종류 수: 3138

                         사업명  반복횟수
0               공동주택 관리지원 사업    69
1         보안등 전기요금 및 교체비용 지원    58
2             작은도서관 도서구입비 지원    55
3                  공동주택 지원사업    54
4                   경로당 개보수비    53
5     공동주택 유지관리 지원 공동주택관리지원금    44
6               작은도서관 운영비 지원    40
7               어린이집 냉난방비 지원    37
8        소규모 노후 공동주택 유지관리 지원    36
9                    보훈단체 지원    35
10                시민평생교육사업운영    34
11      이웃 안녕 자원봉사 프로그램 공모사업    34
12                작은도서관 운영지원    33
13               양성평등주간 기념행사    33
14               보훈단체 운영비 지원    33
15                       운영비    31
16                    보훈단체관리    31
17           지역아동센터 냉·난방비 지원    31
18                 공동주택사업 지원    30
19              지역아동센터 운영 지원    30
20         도서관 중심 독서공동체 지원사업    30
21           작은도서관 도서 및 서가구입    29
22             큰나무 가지치기 지원사업    27
23              신선농산물 예냉고 지원    26
24                 지역아동센터 지원    25
25            첨단산업전시회 참가비 지원    25
26                마을공동체 지원사업    24
27  안전한 외식문화조성사업 주방문화개선 등 지원    23
28        지역아동센터 프로그램 사업비 지원    23
29               독서동아리 지원 사업    23

03-3 점검 완료
다음 단계로 넘어가기 전에 아래를 확인하세요.
1) 사업명 결측 14행이 실제로 분석 제외 후보인지
2) 줄바꿈/연속공백/앞뒤공백이 사업명_clean에서 정리 가능한 수준인지
3) 합계/소계/총계 후보가 실제 합계행인지
4) 반복 등장 사업명이 오류가 아니라 정상 반복인지
5) 특수 따옴표·특수공백이 정제 규칙에 포함되어야 하는지

03-4. 사업명_clean 생성 및 정제 전후 비교
1. 이 단계의 목적

이 단계에서는 원본 사업명 열을 절대 수정하지 않고, 분석용 새 열인 사업명_clean을 생성합니다.

이번 정제는 의미를 바꾸는 작업이 아니라, 텍스트 분석 전에 필요한 최소한의 형식 정리입니다.

정리 대상은 다음입니다.

줄바꿈 \n, \r → 공백으로 변환
탭 \t → 공백으로 변환
특수공백 → 일반 공백으로 변환
연속 공백 2칸 이상 → 1칸으로 축소
앞뒤 공백 제거
특수 따옴표 일부 정규화
한글 유니코드 정규화

아직 글자 간 공백 오류를 고치지는 않습니다.
예를 들어 도 내 행 사장 같은 유형은 별도 진단 단계에서 확인합니다.

2. 입력 데이터

이전 단계까지 사용한 원본 데이터프레임입니다.

df

필수 열은 다음입니다.

사업명

3. 생성할 변수 또는 출력
| 생성 변수                 | 의미                  |
| --------------------- | ------------------- |
| `사업명_clean`           | 분석용으로 최소 정제한 사업명    |
| `사업명_key`             | 중복·비교용 사업명 키        |
| `사업명_is_missing`      | 원본 사업명 결측 여부        |
| `사업명_clean_is_empty`  | 정제 후 빈 문자열 여부       |
| `사업명_clean_changed`   | 원본과 정제본이 달라졌는지 여부   |
| `사업명_clean_length`    | 정제 후 글자 수           |
| `clean_change_sample` | 정제 전후가 달라진 사례 확인용 표 |

이 셀에서는 아직 파일 저장을 하지 않습니다.
먼저 정제 결과가 안전한지 화면에서 확인합니다.

In [ ]:
# 03-4. 사업명_clean 생성 및 정제 전후 비교

# ------------------------------------------------------------
# 0) 유니코드 정규화를 위한 라이브러리
# ------------------------------------------------------------

import unicodedata

# ------------------------------------------------------------
# 1) 사업명 정제 함수 정의
# ------------------------------------------------------------
# 주의:
# 이 함수는 원본 df['사업명']을 직접 수정하지 않습니다.
# 새 열 df['사업명_clean']을 만들 때만 사용합니다.

def clean_project_name(value):
    """
    사업명 텍스트를 분석용으로 최소 정제하는 함수입니다.

    정제 원칙:
    - 원본 의미를 바꾸지 않는다.
    - 모든 공백을 제거하지 않는다.
    - 줄바꿈, 탭, 특수공백, 중복공백, 앞뒤공백만 정리한다.
    - 글자 간 공백 오류는 이 단계에서 고치지 않는다.
    """

    # 결측값은 그대로 pd.NA로 둡니다.
    if pd.isna(value):
        return pd.NA

    # 문자열로 변환
    text = str(value)

    # 한글 유니코드 정규화
    # Colab/Drive에서 한글이 분해형으로 보이는 경우가 있어 NFC로 통일합니다.
    text = unicodedata.normalize('NFC', text)

    # 특수공백을 일반 공백으로 변환
    text = text.replace('\u00A0', ' ')  # NBSP
    text = text.replace('\u200B', '')   # zero-width space

    # 줄바꿈과 탭을 공백으로 변환
    text = re.sub(r'[\r\n\t]+', ' ', text)

    # 특수 따옴표를 일반 따옴표로 통일
    # 의미를 제거하지 않고 형태만 통일합니다.
    text = text.replace('‘', "'").replace('’', "'")
    text = text.replace('“', '"').replace('”', '"')

    # 연속 공백을 하나의 공백으로 축소
    text = re.sub(r'\s+', ' ', text)

    # 앞뒤 공백 제거
    text = text.strip()

    # 정제 후 빈 문자열이면 pd.NA 처리
    if text == '':
        return pd.NA

    return text


# ------------------------------------------------------------
# 2) 원본 보존 상태에서 분석용 새 열 생성
# ------------------------------------------------------------

# 원본 사업명 결측 여부
df['사업명_is_missing'] = df['사업명'].isna()

# 분석용 정제 사업명
df['사업명_clean'] = df['사업명'].apply(clean_project_name)

# 비교·중복 확인용 key
# 현재는 사업명_clean과 같게 두되, 나중에 괄호/연도 제거 버전이 필요하면 별도 key를 만들 수 있습니다.
df['사업명_key'] = df['사업명_clean']

# 정제 후 빈 값 여부
df['사업명_clean_is_empty'] = df['사업명_clean'].isna()

# 정제 후 글자 수
df['사업명_clean_length'] = df['사업명_clean'].astype('string').str.len()

# 원본과 정제본이 달라졌는지 확인
# 결측 비교 오류를 피하기 위해 문자열 임시값으로 비교합니다.
original_for_compare = df['사업명'].fillna('<NA>').astype(str)
clean_for_compare = df['사업명_clean'].fillna('<NA>').astype(str)

df['사업명_clean_changed'] = original_for_compare != clean_for_compare


# ------------------------------------------------------------
# 3) 정제 결과 요약
# ------------------------------------------------------------

clean_summary = pd.DataFrame({
    '항목': [
        '전체 행 수',
        '원본 사업명 결측 행 수',
        '정제 후 사업명_clean 결측 행 수',
        '정제 전후 변경 행 수',
        '정제 후 3글자 이하 행 수',
        '정제 후 80글자 이상 행 수'
    ],
    '값': [
        len(df),
        int(df['사업명_is_missing'].sum()),
        int(df['사업명_clean_is_empty'].sum()),
        int(df['사업명_clean_changed'].sum()),
        int((df['사업명_clean_length'] <= 3).sum()),
        int((df['사업명_clean_length'] >= 80).sum())
    ]
})

print("03-4. 사업명_clean 생성 완료")
display(clean_summary)


# ------------------------------------------------------------
# 4) 정제 전후 변경 사례 확인
# ------------------------------------------------------------
# repr()을 사용하면 눈에 잘 보이지 않는 앞뒤 공백, 줄바꿈, 따옴표 차이를 확인할 수 있습니다.

clean_change_sample = (
    df.loc[df['사업명_clean_changed'], ['사업명', '사업명_clean']]
    .head(30)
    .copy()
)

clean_change_sample['사업명_repr'] = clean_change_sample['사업명'].apply(lambda x: repr(x))
clean_change_sample['사업명_clean_repr'] = clean_change_sample['사업명_clean'].apply(lambda x: repr(x))

print("\n[1] 사업명 정제 전후 변경 사례 30개")
display(clean_change_sample[['사업명_repr', '사업명_clean_repr']])


# ------------------------------------------------------------
# 5) 사업명_clean 결측 행 확인
# ------------------------------------------------------------
# 원본 사업명이 결측이면 사업명_clean도 결측이어야 정상입니다.

context_cols = [
    '시도', '시군구', '지자체명', '지자체유형',
    '원본파일명', 'source_file', 'file_name',
    '사업명', '사업명_clean',
    '보조사업자', '평가결과', '평가종류',
    '사업비합계', '보조금', '사업자부담'
]

existing_context_cols = [col for col in context_cols if col in df.columns]

print("\n[2] 사업명_clean 결측 행")
display(
    df.loc[df['사업명_clean_is_empty'], existing_context_cols]
    .head(30)
)


# ------------------------------------------------------------
# 6) 정제 후에도 남아 있는 기본 형식 문제 재점검
# ------------------------------------------------------------

clean_text = df['사업명_clean'].fillna('').astype(str)

clean_newline_count = clean_text.str.contains(r'\n|\r', regex=True).sum()
clean_tab_count = clean_text.str.contains(r'\t', regex=True).sum()
clean_multi_space_count = clean_text.str.contains(r' {2,}', regex=True).sum()
clean_leading_trailing_count = (clean_text != clean_text.str.strip()).sum()
clean_special_quote_count = clean_text.str.contains(r'[‘’“”]', regex=True).sum()
clean_nbsp_count = clean_text.str.contains('\u00A0', regex=False).sum()

clean_issue_summary = pd.DataFrame({
    '점검항목': [
        '줄바꿈 포함',
        '탭 포함',
        '연속 공백 2칸 이상 포함',
        '앞뒤 공백 포함',
        '특수 따옴표 포함',
        'NBSP 특수공백 포함'
    ],
    '정제 후 행 수': [
        int(clean_newline_count),
        int(clean_tab_count),
        int(clean_multi_space_count),
        int(clean_leading_trailing_count),
        int(clean_special_quote_count),
        int(clean_nbsp_count)
    ]
})

print("\n[3] 사업명_clean 기본 형식 문제 재점검")
display(clean_issue_summary)


# ------------------------------------------------------------
# 7) 다음 단계용 텍스트 분석 대상 행 수 확인
# ------------------------------------------------------------
# 03번 텍스트 분석에서는 사업명_clean이 있는 행을 기본 대상으로 사용합니다.
# 원본 df에서는 행을 삭제하지 않고, 분석용 df_text를 따로 만듭니다.

df_text = df.loc[~df['사업명_clean_is_empty']].copy()

print("\n[4] 다음 단계 텍스트 분석 대상")
print("- 원본 df 행 수:", len(df))
print("- 사업명_clean이 있는 df_text 행 수:", len(df_text))
print("- 사업명_clean 결측으로 제외되는 행 수:", len(df) - len(df_text))

print("\n03-4 완료")
print("다음 단계에서는 df_text를 기준으로 글자 간 공백 오류 의심 사례를 진단합니다.")

03-4. 사업명_clean 생성 완료

                      항목      값
0                 전체 행 수  79276
1          원본 사업명 결측 행 수     14
2  정제 후 사업명_clean 결측 행 수     14
3           정제 전후 변경 행 수   2049
4        정제 후 3글자 이하 행 수     64
5       정제 후 80글자 이상 행 수      2

[1] 사업명 정제 전후 변경 사례 30개

,사업명_repr,사업명_clean_repr
1,'2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영',"""2023년 사)진주지역범죄피해자지원센터'등불 '남해지부 운영"""
21,'2023년 범죄피해자 지원 및 지원센터‘등불’운영',"""2023년 범죄피해자 지원 및 지원센터'등불'운영"""
834,'지역 문화 진흥 공모사업 (문화자원활용 지원 (별이 빛나는 밤“藝”(예)))',"'지역 문화 진흥 공모사업 (문화자원활용 지원 (별이 빛나는 밤""藝""(예)))'"
3537,'청년동아리‘너나 들이’지원사업',"""청년동아리'너나 들이'지원사업"""
5276,'아라농촌마을재생사업 기본사업비','아라농촌마을재생사업 기본사업비'
5277,'아라농촌마을재생사업 우수마을 상사업비','아라농촌마을재생사업 우수마을 상사업비'
5331,'한국미술협회 함안지부 제11회 아름다운 함안전','한국미술협회 함안지부 제11회 아름다운 함안전'
5402,'보훈단체 등 행사지원 6.25참전유공자회 전적지순례','보훈단체 등 행사지원 6.25참전유공자회 전적지순례'
8078,'“한눈에 보는 진례” 안내지도 만들기(주민참여)',"'""한눈에 보는 진례"" 안내지도 만들기(주민참여)'"
8084,"'김해시 외동, “걷고 싶은 거리” 조성 사업(주민참여)'","'김해시 외동, ""걷고 싶은 거리"" 조성 사업(주민참여)'"
8092,'‘걷고 싶은 문동저수지’ 달빛 산책로 조성사업(주민참여)',"""'걷고 싶은 문동저수지' 달빛 산책로 조성사업(주민참여)"""
8305,'경남도민예술단 순회공연 : (함양) 이 땅에 내린 신명 ‘대(竹)광대 유희',"""경남도민예술단 순회공연 : (함양) 이 땅에 내린 신명 '대(竹)광대 유희"""
8939,'“우리 자녀를 위한 감성코칭” 라떼파파 문화예술학교',"'""우리 자녀를 위한 감성코칭"" 라떼파파 문화예술학교'"
8943,'이웃 간 마음 거리두기 해제 ‘꽃피는 우리 마을’',"""이웃 간 마음 거리두기 해제 '꽃피는 우리 마을'"""
8945,'건강한 하천 만들기 “흙꽁이를 하천에 보내주세요”',"'건강한 하천 만들기 ""흙꽁이를 하천에 보내주세요""'"
8946,'인문학과 도시가 만나 세대를 아우르다‘도시 인문 기행을 통한 세대공감',"""인문학과 도시가 만나 세대를 아우르다'도시 인문 기행을 통한 세대공감"""
8949,'행복을 말하다!‘다문화말하기대회’',"""행복을 말하다!'다문화말하기대회'"""
8960,'8.14 세계 일본군 ‘위안부’ 평화 기림사업 <남해 기억의 길 > 제7회 숙이나...,"""8.14 세계 일본군 '위안부' 평화 기림사업 <남해 기억의 길 > 제7회 숙이나..."
8971,'나눔의 행복 – 노노(老老)케어','나눔의 행복 – 노노(老老)케어'
8975,'폐지수집가의 안전한 활동을 돕는 ‘안전하게 보람되게’',"""폐지수집가의 안전한 활동을 돕는 '안전하게 보람되게'"""
9063,'국악관현악단과 함께하는 “2023 오색찬란 콘서트”',"'국악관현악단과 함께하는 ""2023 오색찬란 콘서트""'"
9276,"'장애인 재활프로그램 운영 (2023년 장애 학생들을 위한 미술 재능계발, 재활치료...","'장애인 재활프로그램 운영 (2023년 장애 학생들을 위한 미술 재능계발, 재활치료..."
9333,'여성시리즈 ‘여성운동을 합창하다’',"""여성시리즈 '여성운동을 합창하다'"""
9347,'여성주의 글쓰기 ‘우리의 진짜 이야기’',"""여성주의 글쓰기 '우리의 진짜 이야기'"""
9348,'“우·아·솔!”우리아이와 솔직한 성교육',"'""우·아·솔!""우리아이와 솔직한 성교육'"
9951,'장애인의 자기표현 개발을 위한 “소통”',"'장애인의 자기표현 개발을 위한 ""소통""'"
10393,"'특성별 지역아동센터 추가 지원(‘21) 지역아동센터특성별추가지원(’22, ‘23)...","""특성별 지역아동센터 추가 지원('21) 지역아동센터특성별추가지원('22, '23)..."
11489,'사계절맛있는‘K-김치’나눔',"""사계절맛있는'K-김치'나눔"""
11490,'바른먹거리‘K-요리수업’나눔',"""바른먹거리'K-요리수업'나눔"""
12726,'바리스타교육 ‘에브리바디스타’',"""바리스타교육 '에브리바디스타'"""

[2] 사업명_clean 결측 행

,시도,지자체명,사업명,사업명_clean,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
16390,서울,금천구,<NA>,<NA>,(사)서울시지체장애인협회 금천구지회,우수,성과평가,1400,1250,150
17126,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17127,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17235,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17236,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17344,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17345,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17437,서울,본청,<NA>,<NA>,서울시 25개 자치구,매우우수,<NA>,255,255,-
17453,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17454,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17562,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17563,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17671,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17672,서울,본청,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

[3] 사업명_clean 기본 형식 문제 재점검

             점검항목  정제 후 행 수
0          줄바꿈 포함         0
1            탭 포함         0
2  연속 공백 2칸 이상 포함         0
3        앞뒤 공백 포함         0
4       특수 따옴표 포함         0
5    NBSP 특수공백 포함         0

[4] 다음 단계 텍스트 분석 대상
- 원본 df 행 수: 79276
- 사업명_clean이 있는 df_text 행 수: 79262
- 사업명_clean 결측으로 제외되는 행 수: 14

03-4 완료
다음 단계에서는 df_text를 기준으로 글자 간 공백 오류 의심 사례를 진단합니다.

03-5. 글자 간 공백 오류 의심 사례 진단
1. 이 단계의 목적

이 단계는 사업명_clean에서 글자 사이가 비정상적으로 띄어진 사업명 후보를 찾는 단계입니다.

예를 들면 아래와 같은 사례를 의심합니다.

도 내 행 사장
문 화 예 술
지 역 사 회

다만 정상적인 띄어쓰기와 구분이 어렵기 때문에, 이 단계에서는 자동 수정하지 않습니다.
후보를 뽑고 사람이 직접 확인한 뒤, 반복되는 패턴이 있을 때만 다음 단계에서 규칙화합니다.

2. 입력 데이터

이전 단계에서 만든 텍스트 분석용 데이터프레임입니다
df_text

필수 열은 다음입니다.
사업명_clean

3. 생성할 변수 또는 출력
| 변수명                      | 의미                |
| ------------------------ | ----------------- |
| `char_space_issue_rows`  | 글자 간 공백 오류 의심 사례  |
| `char_space_summary`     | 의심 사례 수 요약        |
| `char_space_run_text`    | 의심되는 한글 1글자 연속 구간 |
| `char_space_run_count`   | 의심 구간 개수          |
| `char_space_max_run_len` | 가장 긴 1글자 연속 구간 길이 |

In [ ]:
# 03-5. 글자 간 공백 오류 의심 사례 진단

# ------------------------------------------------------------
# 1) 글자 간 공백 의심 구간을 찾는 함수 정의
# ------------------------------------------------------------

def find_single_hangul_runs(text, min_run_len=3):
    """
    한글 1글자 토큰이 공백을 사이에 두고 연속으로 등장하는 구간을 찾습니다.

    예:
    - '도 내 행 사장' -> ['도 내 행']
    - '문 화 예 술 행사' -> ['문 화 예 술']

    주의:
    - 이 함수는 오류를 확정하지 않습니다.
    - 정상적인 표현도 후보로 잡힐 수 있으므로 사람이 직접 확인해야 합니다.
    """

    if pd.isna(text):
        return []

    tokens = str(text).split()

    runs = []
    current_run = []

    for tok in tokens:
        # 한글 1글자 토큰인지 확인
        if re.fullmatch(r'[가-힣]', tok):
            current_run.append(tok)
        else:
            # 지금까지 쌓인 1글자 토큰 연속 구간이 기준 이상이면 저장
            if len(current_run) >= min_run_len:
                runs.append(' '.join(current_run))
            current_run = []

    # 마지막 구간 처리
    if len(current_run) >= min_run_len:
        runs.append(' '.join(current_run))

    return runs


# ------------------------------------------------------------
# 2) df_text에 의심 구간 정보 생성
# ------------------------------------------------------------
# 주의:
# 원본 df가 아니라 df_text에만 진단용 열을 추가합니다.

df_text['char_space_runs'] = df_text['사업명_clean'].apply(find_single_hangul_runs)

df_text['char_space_run_count'] = df_text['char_space_runs'].apply(len)

df_text['char_space_max_run_len'] = df_text['char_space_runs'].apply(
    lambda runs: max([len(run.split()) for run in runs], default=0)
)

df_text['char_space_issue_flag'] = df_text['char_space_run_count'] > 0

# 사람이 보기 쉽게 의심 구간을 문자열로 합칩니다.
df_text['char_space_run_text'] = df_text['char_space_runs'].apply(
    lambda runs: ' | '.join(runs) if len(runs) > 0 else ''
)


# ------------------------------------------------------------
# 3) 의심 사례 요약
# ------------------------------------------------------------

char_space_issue_rows = df_text.loc[df_text['char_space_issue_flag']].copy()

char_space_summary = pd.DataFrame({
    '항목': [
        '텍스트 분석 대상 행 수',
        '글자 간 공백 의심 행 수',
        '글자 간 공백 의심 비율(%)',
        '최대 1글자 연속 구간 길이'
    ],
    '값': [
        len(df_text),
        len(char_space_issue_rows),
        round(len(char_space_issue_rows) / len(df_text) * 100, 3),
        int(df_text['char_space_max_run_len'].max())
    ]
})

print("03-5. 글자 간 공백 오류 의심 사례 진단")
display(char_space_summary)


# ------------------------------------------------------------
# 4) 의심 사례 샘플 확인
# ------------------------------------------------------------

context_cols = [
    '시도', '시군구', '지자체명', '지자체유형',
    '원본파일명', 'source_file', 'file_name',
    '사업명', '사업명_clean',
    'char_space_run_text',
    'char_space_run_count',
    'char_space_max_run_len',
    '보조사업자', '평가결과', '평가종류'
]

existing_context_cols = [col for col in context_cols if col in df_text.columns]

print("\n[1] 글자 간 공백 의심 사례 상위 50개")
display(
    char_space_issue_rows
    .sort_values(['char_space_max_run_len', 'char_space_run_count'], ascending=False)
    [existing_context_cols]
    .head(50)
)


# ------------------------------------------------------------
# 5) 의심 구간 빈도 확인
# ------------------------------------------------------------
# 같은 의심 구간이 반복되면 실제 오류일 가능성이 상대적으로 높습니다.

char_space_run_freq = (
    char_space_issue_rows['char_space_runs']
    .explode()
    .dropna()
    .value_counts()
    .reset_index()
)

char_space_run_freq.columns = ['의심구간', '빈도']

print("\n[2] 반복되는 글자 간 공백 의심 구간 상위 30개")
display(char_space_run_freq.head(30))


# ------------------------------------------------------------
# 6) 기준 완화/강화 참고용: 1글자 연속 길이별 분포
# ------------------------------------------------------------

run_len_distribution = (
    df_text.loc[df_text['char_space_max_run_len'] > 0, 'char_space_max_run_len']
    .value_counts()
    .sort_index()
    .reset_index()
)

run_len_distribution.columns = ['가장 긴 1글자 연속 구간 길이', '행 수']

print("\n[3] 1글자 연속 구간 길이별 분포")
display(run_len_distribution)


# ------------------------------------------------------------
# 7) 다음 단계 안내
# ------------------------------------------------------------

print("\n03-5 완료")
print("이 단계에서는 후보만 찾았습니다.")
print("다음으로 확인할 것:")
print("1) 의심 사례 상위 50개가 실제 오류인지")
print("2) 반복 의심 구간이 특정 지자체나 파일에 몰려 있는지")
print("3) 정상 표현이 많이 잡힌다면 기준을 더 엄격하게 조정할지")
print("4) 실제 오류 패턴이 확인되면 자동 수정이 아니라 규칙 후보로 기록할지")

03-5. 글자 간 공백 오류 의심 사례 진단

                 항목          값
0     텍스트 분석 대상 행 수  79262.000
1    글자 간 공백 의심 행 수     27.000
2  글자 간 공백 의심 비율(%)      0.034
3   최대 1글자 연속 구간 길이     12.000

[1] 글자 간 공백 의심 사례 상위 50개

,시도,지자체명,사업명,사업명_clean,char_space_run_text,char_space_run_count,char_space_max_run_len,보조사업자,평가결과,평가종류
71055,전남,본청,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터,1,12,서부학대피해노인전용쉼터,미흡,성과평가
71080,전남,본청,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터,1,12,전라남도장애인단체총연합 회,보통,성과평가
71158,전남,본청,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회,1,11,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71382,전남,본청,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회,1,11,전라남도자율방범연합회,우수,성과평가
71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전...,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전 라 남 도 선 비 문 화 포 럼 | 성 균 관 청 년 유 도 회,2,10,성균관청년유도회 전남본부(박태성),보통,성과평가
71195,전남,본청,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의,1,10,민주평화통일자문회의 전남지역회의(우승하),우수,성과평가
71391,전남,본청,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학,1,10,전남농업마이스터대학,보통,성과평가
71351,전남,본청,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치,1,9,(사)전라남도종가회,매우우수,성과평가
71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 ...,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),학 술 회 | 성 균 관 청 년 유 도 회,2,8,성균관청년유도회 전남본부(박태성),보통,성과평가
71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유...,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),유 림 대 회 | 성 균 관 청 년 유 도 회,2,8,성균관청년유도회 전남본부(박태성),보통,성과평가
70996,전남,본청,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관,1,8,상이군경회 전남지부,미흡,성과평가
71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회...,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),성 균 관 여 성 유 도 회,1,8,성균관여성유도회 전남본부(박정재),보통,성과평가
71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 ...","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학",수 산 단 체 | 수 산 업 경 영 인,2,6,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남...,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),회 복 사 업 | 성 균 관 유 도 회,2,6,성균관유도회 전남본부(문영수),미흡,성과평가
71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,1,6,성균관유도회 전남본부(문영수),보통,성과평가
71296,전남,본청,전남 유림신문 발 간 ( 성 균 관...,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,1,6,성균관유도회 전남본부(문영수),보통,성과평가
71311,전남,본청,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회,1,6,한국장애인문화전라남도협 회(이동기),우수,성과평가
71231,전남,본청,소 비 자 권 익 보호사업(공모사업),소 비 자 권 익 보호사업(공모사업),소 비 자 권 익,1,5,한국소비자연맹전남목포지 회(박난숙) 한국부인회전남도지부(최두 례) 소비자교육중앙회전...,우수,성과평가
71300,전남,본청,유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자,1,5,전남향교재단(박대하),보통,성과평가
71407,전남,본청,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자,1,5,한국임업후계자협회(정재동),매우우수,성과평가
71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 ...,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),운 영 지 원 | 노 인 돌 봄,2,4,전남사회서비스원,우수,성과평가
71383,전남,본청,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도,1,4,전라남도 지역특화작목발전협회(정병 준),보통,성과평가
26155,충남,부여군,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도,1,3,부여군체육회,보통,성과평가
29885,충북,청주시,송범 춤 그 후,송범 춤 그 후,춤 그 후,1,3,송범춤사업회,미흡,유지필요성평가
35489,충북,제천시,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞,1,3,박명옥,매우우수,유지필요성평가
52824,경기,안양시,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예 방 및 홍보활동,예 방 및,1,3,안양재향경우회,보통,성과평가
53062,경기,안양시,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행 사 보조,날 행 사,1,3,안양기독교 청년회 (안양YMCA),보통,성과평가/유지필요성평가

[2] 반복되는 글자 간 공백 의심 구간 상위 30개

                       의심구간  빈도
0               성 균 관 유 도 회   3
1           성 균 관 청 년 유 도 회   3
2                     내 집 앞   1
3                     춤 그 후   1
4                     군 및 도   1
5           상 이 군 경 복 지 회 관   1
6                   운 영 지 원   1
7                   노 인 돌 봄   1
8   서 부 학 대 피 해 노 인 전 용 쉼 터   1
9   장 애 인 일 자 리 종 합 지 원 센 터   1
10                  수 산 단 체   1
11                    예 방 및   1
12                    날 행 사   1
13    한 국 수 산 업 경 영 인 연 합 회   1
14              수 산 업 경 영 인   1
15                소 비 자 권 익   1
16      민 주 평 화 통 일 자 문 회 의   1
17                  회 복 사 업   1
18      전 라 남 도 선 비 문 화 포 럼   1
19                    학 술 회   1
20                  유 림 대 회   1
21                유 림 지 도 자   1
22          성 균 관 여 성 유 도 회   1
23              문 화 혁 신 대 회   1
24        남 도 음 식 문 화 큰 잔 치   1
25    전 라 남 도 자 율 방 범 연 합 회   1
26                  전 라 남 도   1
27      전 남 농 업 마 이 스 터 대 학   1
28                임 업 후 계 자   1

[3] 1글자 연속 구간 길이별 분포

   가장 긴 1글자 연속 구간 길이  행 수
0                  3    5
1                  4    2
2                  5    3
3                  6    5
4                  8    4
5                  9    1
6                 10    3
7                 11    2
8                 12    2

03-5 완료
이 단계에서는 후보만 찾았습니다.
다음으로 확인할 것:
1) 의심 사례 상위 50개가 실제 오류인지
2) 반복 의심 구간이 특정 지자체나 파일에 몰려 있는지
3) 정상 표현이 많이 잡힌다면 기준을 더 엄격하게 조정할지
4) 실제 오류 패턴이 확인되면 자동 수정이 아니라 규칙 후보로 기록할지

03-6. 글자 간 공백 의심 사례 검토표 저장
1. 이 단계의 목적

이 단계는 03-5에서 탐지한 글자 간 공백 의심 사례 27건을 별도 검토표로 저장하는 단계입니다.

아직 자동 수정하지 않습니다.
대신 다음과 같은 검토용 열을 추가합니다.

검토판단
수정필요여부
수정후_사업명_clean
검토메모

이 표를 보고 사람이 직접 판단한 뒤, 이후 반복 가능한 보정 규칙을 만들지 결정합니다.

2. 입력 데이터

이전 단계에서 생성된 데이터입니다.

df_text
char_space_issue_rows

필수 열은 다음입니다.

사업명
사업명_clean
char_space_run_text
char_space_run_count
char_space_max_run_len

3. 생성할 변수 또는 출력
| 변수 또는 파일                                               | 의미                    |
| ------------------------------------------------------ | --------------------- |
| `char_space_review`                                    | 글자 간 공백 의심 사례 검토표     |
| `03_char_space_issue_candidates_v1_YYYYMMDD_HHMM.xlsx` | Drive에 저장되는 검토용 Excel |
| `03_char_space_issue_candidates_v1_YYYYMMDD_HHMM.csv`  | Drive에 저장되는 검토용 CSV   |

저장 위치는 03번 산출물 폴더의 tables입니다.

03_v1_사업명텍스트분석/tables

In [ ]:
# 03-6. 글자 간 공백 의심 사례 검토표 저장

# ------------------------------------------------------------
# 1) 검토표에 포함할 열 정리
# ------------------------------------------------------------

review_cols = [
    '시도', '시군구', '지자체명', '지자체유형',
    '원본파일명', 'source_file', 'file_name',
    '사업명',
    '사업명_clean',
    'char_space_run_text',
    'char_space_run_count',
    'char_space_max_run_len',
    '보조사업자',
    '평가결과',
    '평가종류',
    '사업비합계',
    '보조금',
    '사업자부담'
]

existing_review_cols = [col for col in review_cols if col in char_space_issue_rows.columns]

# ------------------------------------------------------------
# 2) 글자 간 공백 의심 사례 검토표 생성
# ------------------------------------------------------------

char_space_review = (
    char_space_issue_rows
    .sort_values(
        ['char_space_max_run_len', 'char_space_run_count'],
        ascending=False
    )
    [existing_review_cols]
    .copy()
)

# 원래 데이터의 index를 남겨두면 나중에 df_text와 연결하기 쉽습니다.
char_space_review = char_space_review.reset_index().rename(columns={'index': '원본_index'})

# ------------------------------------------------------------
# 3) 수동 검토용 빈 열 추가
# ------------------------------------------------------------
# 이 열들은 사람이 직접 채우기 위한 열입니다.
# 코드가 임의로 수정값을 만들지 않습니다.

char_space_review['검토판단'] = ''
char_space_review['수정필요여부'] = ''
char_space_review['수정후_사업명_clean'] = ''
char_space_review['검토메모'] = ''

# 보기 편하도록 검토용 열을 앞쪽에 배치합니다.
front_cols = [
    '원본_index',
    '시도',
    '지자체명',
    '사업명',
    '사업명_clean',
    'char_space_run_text',
    '검토판단',
    '수정필요여부',
    '수정후_사업명_clean',
    '검토메모'
]

front_cols = [col for col in front_cols if col in char_space_review.columns]
other_cols = [col for col in char_space_review.columns if col not in front_cols]

char_space_review = char_space_review[front_cols + other_cols]

# ------------------------------------------------------------
# 4) 저장 파일명 설정
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

char_space_review_xlsx = TABLE_DIR / f'03_char_space_issue_candidates_v1_{timestamp}.xlsx'
char_space_review_csv = TABLE_DIR / f'03_char_space_issue_candidates_v1_{timestamp}.csv'

# ------------------------------------------------------------
# 5) 검토표 저장
# ------------------------------------------------------------

char_space_review.to_excel(char_space_review_xlsx, index=False)
char_space_review.to_csv(char_space_review_csv, index=False, encoding='utf-8-sig')

# ------------------------------------------------------------
# 6) 저장 결과 및 검토표 확인
# ------------------------------------------------------------

print("03-6. 글자 간 공백 의심 사례 검토표 저장 완료")
print("- 검토 대상 행 수:", len(char_space_review))
print("- Excel 저장 경로:", char_space_review_xlsx)
print("- CSV 저장 경로:", char_space_review_csv)

print("\n저장 파일 존재 여부")
print("- Excel:", char_space_review_xlsx.exists())
print("- CSV:", char_space_review_csv.exists())

print("\n[검토표 미리보기]")
display(char_space_review.head(30))

03-6. 글자 간 공백 의심 사례 검토표 저장 완료
- 검토 대상 행 수: 27
- Excel 저장 경로: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_char_space_issue_candidates_v1_20260526_1654.xlsx
- CSV 저장 경로: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_char_space_issue_candidates_v1_20260526_1654.csv

저장 파일 존재 여부
- Excel: True
- CSV: True

[검토표 미리보기]

,원본_index,시도,지자체명,사업명,사업명_clean,char_space_run_text,검토판단,수정필요여부,수정후_사업명_clean,검토메모,char_space_run_count,char_space_max_run_len,보조사업자,평가결과,평가종류,사업비합계,보조금,사업자부담
0,71055,전남,본청,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터,,,,,1,12,서부학대피해노인전용쉼터,미흡,성과평가,194825,194825,0
1,71080,전남,본청,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터,,,,,1,12,전라남도장애인단체총연합 회,보통,성과평가,149541,149541,0
2,71158,전남,본청,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회,,,,,1,11,(사)한국수산업경영영인 전라남도연합회,보통,성과평가,70000,70000,0
3,71382,전남,본청,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회,,,,,1,11,전라남도자율방범연합회,우수,성과평가,30000,30000,0
4,71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전...,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전 라 남 도 선 비 문 화 포 럼 | 성 균 관 청 년 유 도 회,,,,,2,10,성균관청년유도회 전남본부(박태성),보통,성과평가,30790,12000,18790
5,71195,전남,본청,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의,,,,,1,10,민주평화통일자문회의 전남지역회의(우승하),우수,성과평가,15000,15000,0
6,71391,전남,본청,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학,,,,,1,10,전남농업마이스터대학,보통,성과평가,20000,20000,0
7,71351,전남,본청,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치,,,,,1,9,(사)전라남도종가회,매우우수,성과평가,50000,50000,0
8,71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 ...,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),학 술 회 | 성 균 관 청 년 유 도 회,,,,,2,8,성균관청년유도회 전남본부(박태성),보통,성과평가,22000,20000,2000
9,71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유...,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),유 림 대 회 | 성 균 관 청 년 유 도 회,,,,,2,8,성균관청년유도회 전남본부(박태성),보통,성과평가,30000,30000,0
10,70996,전남,본청,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관,,,,,1,8,상이군경회 전남지부,미흡,성과평가,30000,30000,0
11,71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회...,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),성 균 관 여 성 유 도 회,,,,,1,8,성균관여성유도회 전남본부(박정재),보통,성과평가,20000,20000,0
12,71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 ...","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학",수 산 단 체 | 수 산 업 경 영 인,,,,,2,6,(사)한국수산업경영영인 전라남도연합회,보통,성과평가,13000,10000,3000
13,71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남...,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),회 복 사 업 | 성 균 관 유 도 회,,,,,2,6,성균관유도회 전남본부(문영수),미흡,성과평가,40000,40000,0
14,71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,,,,,1,6,성균관유도회 전남본부(문영수),보통,성과평가,20000,20000,0
15,71296,전남,본청,전남 유림신문 발 간 ( 성 균 관...,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,,,,,1,6,성균관유도회 전남본부(문영수),보통,성과평가,30000,30000,0
16,71311,전남,본청,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회,,,,,1,6,한국장애인문화전라남도협 회(이동기),우수,성과평가,5500,5000,500
17,71231,전남,본청,소 비 자 권 익 보호사업(공모사업),소 비 자 권 익 보호사업(공모사업),소 비 자 권 익,,,,,1,5,한국소비자연맹전남목포지 회(박난숙) 한국부인회전남도지부(최두 례) 소비자교육중앙회전...,우수,성과평가,77350,70000,7350
18,71300,전남,본청,유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자,,,,,1,5,전남향교재단(박대하),보통,성과평가,30000,30000,0
19,71407,전남,본청,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자,,,,,1,5,한국임업후계자협회(정재동),매우우수,성과평가,30000,30000,0
20,71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 ...,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),운 영 지 원 | 노 인 돌 봄,,,,,2,4,전남사회서비스원,우수,성과평가,8640,8640,0
21,71383,전남,본청,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도,,,,,1,4,전라남도 지역특화작목발전협회(정병 준),보통,성과평가,10000,10000,0
22,26155,충남,부여군,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도,,,,,1,3,부여군체육회,보통,성과평가,67370,67370,0
23,29885,충북,청주시,송범 춤 그 후,송범 춤 그 후,춤 그 후,,,,,1,3,송범춤사업회,미흡,유지필요성평가,13.0,12.0,1.0
24,35489,충북,제천시,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞,,,,,1,3,박명옥,매우우수,유지필요성평가,5.3,3.0,2.3
25,52824,경기,안양시,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예 방 및 홍보활동,예 방 및,,,,,1,3,안양재향경우회,보통,성과평가,9270,5900,3370.0
26,53062,경기,안양시,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행 사 보조,날 행 사,,,,,1,3,안양기독교 청년회 (안양YMCA),보통,성과평가/유지필요성평가,15000,15000,0.0

03-7. 형태소 분석기 설치 및 테스트
1. 이 단계의 목적

이 단계는 사업명 토큰화를 하기 전에 한국어 형태소 분석기인 kiwipiepy를 설치하고, 실제 사업명 몇 개에 대해 형태소 분석이 제대로 작동하는지 확인하는 단계입니다.

아직 전체 데이터에 토큰화를 적용하지 않습니다.
먼저 샘플 몇 개만 분석해서 명사·고유명사·외래어 등이 어떻게 분리되는지 확인합니다.

2. 입력 데이터

이전 단계에서 만든 텍스트 분석용 데이터프레임입니다.

df_text

필수 열은 다음입니다.

사업명_clean

3. 생성할 변수 또는 출력
| 변수명                | 의미                 |
| ------------------ | ------------------ |
| `kiwi`             | Kiwi 형태소 분석기 객체    |
| `sample_names`     | 형태소 분석 테스트용 사업명 샘플 |
| `kiwi_test_result` | 샘플 사업명의 형태소 분석 결과표 |

In [ ]:
# 03-7. 형태소 분석기 설치 및 테스트

# ------------------------------------------------------------
# 1) kiwipiepy 설치
# ------------------------------------------------------------
# Colab 런타임에서 처음 실행하는 경우 설치가 필요합니다.
# 이미 설치되어 있으면 빠르게 넘어갑니다.

!pip install -q kiwipiepy

# ------------------------------------------------------------
# 2) 라이브러리 불러오기
# ------------------------------------------------------------

from kiwipiepy import Kiwi

# 형태소 분석기 객체 생성
kiwi = Kiwi()

print("kiwipiepy 설치 및 Kiwi 객체 생성 완료")


# ------------------------------------------------------------
# 3) 테스트용 사업명 샘플 구성
# ------------------------------------------------------------
# 다양한 유형의 사업명이 잘 분석되는지 보기 위해
# 일반 사업명, 복지, 문화, 농업, 괄호 포함, 글자 간 공백 의심 사례를 섞어 확인합니다.

sample_names = [
    '마늘재배 영농지원단 지원',
    '장애인직업재활 자활교육',
    '문화학교 운영',
    '수산물 상생할인 지원사업',
    '농촌신활력 플러스사업 (추진단사무국상근직원인건비)',
    '자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회)',
    '2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원)',
    '서 부 학 대 피 해 노 인 전 용 쉼 터 지원',
    '장 애 인 일 자 리 종 합 지 원 센 터 운영'
]


# ------------------------------------------------------------
# 4) 형태소 분석 결과를 표로 정리
# ------------------------------------------------------------

kiwi_test_rows = []

for name in sample_names:
    analyzed = kiwi.tokenize(name)

    for token in analyzed:
        kiwi_test_rows.append({
            '사업명_clean': name,
            '형태소': token.form,
            '품사': token.tag,
            '시작위치': token.start,
            '길이': token.len
        })

kiwi_test_result = pd.DataFrame(kiwi_test_rows)

print("\n[1] 형태소 분석 테스트 결과")
display(kiwi_test_result)


# ------------------------------------------------------------
# 5) 명사 계열만 따로 보기
# ------------------------------------------------------------
# NNG: 일반명사
# NNP: 고유명사
# SL : 외국어/영문
# SN : 숫자
# 필요 여부는 다음 단계에서 조정합니다.

noun_like_tags = ['NNG', 'NNP', 'SL', 'SN']

kiwi_test_nouns = kiwi_test_result[
    kiwi_test_result['품사'].isin(noun_like_tags)
].copy()

print("\n[2] 명사 계열 형태소만 확인")
display(kiwi_test_nouns)


# ------------------------------------------------------------
# 6) 사업명별 명사 계열 토큰 묶어서 확인
# ------------------------------------------------------------

sample_token_summary = (
    kiwi_test_nouns
    .groupby('사업명_clean')['형태소']
    .apply(list)
    .reset_index()
    .rename(columns={'형태소': '명사계열_토큰'})
)

print("\n[3] 사업명별 명사 계열 토큰 요약")
display(sample_token_summary)


print("\n03-7 완료")
print("다음 단계에서는 전체 df_text에 tokens_raw 열을 생성합니다.")
print("단, 샘플 분석 결과에서 복합어 분해가 심하거나 글자 간 공백 오류가 문제되면 먼저 확인합니다.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 24.4 MB/s eta 0:00:00
  Building wheel for kiwipiepy_model (setup.py) ... done
kiwipiepy 설치 및 Kiwi 객체 생성 완료

[1] 형태소 분석 테스트 결과

                     사업명_clean  형태소   품사  시작위치  길이
0                마늘재배 영농지원단 지원   마늘  NNG     0   2
1                마늘재배 영농지원단 지원   재배  NNG     2   2
2                마늘재배 영농지원단 지원   영농  NNG     5   2
3                마늘재배 영농지원단 지원  지원단  NNG     7   3
4                마늘재배 영농지원단 지원   지원  NNG    11   2
..                         ...  ...  ...   ...  ..
82  장 애 인 일 자 리 종 합 지 원 센 터 운영    지  NNG    16   1
83  장 애 인 일 자 리 종 합 지 원 센 터 운영    원  NNG    18   1
84  장 애 인 일 자 리 종 합 지 원 센 터 운영    센  NNP    20   1
85  장 애 인 일 자 리 종 합 지 원 센 터 운영    터  NNG    22   1
86  장 애 인 일 자 리 종 합 지 원 센 터 운영   운영  NNG    24   2

[87 rows x 5 columns]

[2] 명사 계열 형태소만 확인

                     사업명_clean  형태소   품사  시작위치  길이
0                마늘재배 영농지원단 지원   마늘  NNG     0   2
1                마늘재배 영농지원단 지원   재배  NNG     2   2
2                마늘재배 영농지원단 지원   영농  NNG     5   2
3                마늘재배 영농지원단 지원  지원단  NNG     7   3
4                마늘재배 영농지원단 지원   지원  NNG    11   2
..                         ...  ...  ...   ...  ..
82  장 애 인 일 자 리 종 합 지 원 센 터 운영    지  NNG    16   1
83  장 애 인 일 자 리 종 합 지 원 센 터 운영    원  NNG    18   1
84  장 애 인 일 자 리 종 합 지 원 센 터 운영    센  NNP    20   1
85  장 애 인 일 자 리 종 합 지 원 센 터 운영    터  NNG    22   1
86  장 애 인 일 자 리 종 합 지 원 센 터 운영   운영  NNG    24   2

[69 rows x 5 columns]

[3] 사업명별 명사 계열 토큰 요약

,사업명_clean,명사계열_토큰
0,2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),"[2023, 음식점, 위생, 환경, 개선, 사업, 시설, 환경, 개선, 입식, 테이..."
1,농촌신활력 플러스사업 (추진단사무국상근직원인건비),"[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원, 인건비]"
2,마늘재배 영농지원단 지원,"[마늘, 재배, 영농, 지원단, 지원]"
3,문화학교 운영,"[문화, 학교, 운영]"
4,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,"[서, 부, 학, 피, 노, 인, 용, 터, 지원]"
5,수산물 상생할인 지원사업,"[수산물, 상생, 할인, 지원, 사업]"
6,자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),"[자연, 환경, 보전, 활동, 사업, 자연보호, 정화, 활동, 군, 수기, 경진, 대회]"
7,장 애 인 일 자 리 종 합 지 원 센 터 운영,"[장, 애, 자, 리, 종, 합, 지, 원, 센, 터, 운영]"
8,장애인직업재활 자활교육,"[장애인, 직업, 재활, 자활, 교육]"

03-7 완료
다음 단계에서는 전체 df_text에 tokens_raw 열을 생성합니다.
단, 샘플 분석 결과에서 복합어 분해가 심하거나 글자 간 공백 오류가 문제되면 먼저 확인합니다.

03-8. 글자 간 공백 명확 오류 보정 열 생성
1. 이 단계의 목적

이 단계는 03-5에서 찾은 글자 간 공백 의심 사례 중 명확한 오류만 보정하여, 토큰화에 사용할 새 열 사업명_clean_spacefix를 만드는 단계입니다.

중요한 점은 다음입니다.

원본 사업명은 수정하지 않음
기존 사업명_clean도 덮어쓰지 않음
새 열 사업명_clean_spacefix를 만듦
정상 표현으로 보이는 내 집 앞, 군 및 도, 춤 그 후 같은 사례는 보정하지 않음
보정 여부를 spacefix_applied 열로 남김

In [ ]:
# 03-8. 글자 간 공백 명확 오류 보정 열 생성

# ------------------------------------------------------------
# 1) 원본 보존 원칙
# ------------------------------------------------------------
# df_text['사업명_clean']은 덮어쓰지 않습니다.
# 글자 간 공백이 명확히 잘못된 사례만 새 열에서 보정합니다.

df_text['사업명_clean_spacefix'] = df_text['사업명_clean'].copy()

# ------------------------------------------------------------
# 2) 명확한 글자 간 공백 오류 보정 사전
# ------------------------------------------------------------
# key   : 원본_index
# value : 보정 후 사업명
#
# 주의:
# 아래는 03-5 출력에서 명확히 오류로 보이는 사례만 우선 반영한 초안입니다.
# 애매한 사례는 넣지 않습니다.
# 예: '내 집 앞', '군 및 도', '춤 그 후'는 정상 표현 가능성이 있으므로 제외합니다.

spacefix_map = {
    71055: '서부 학대 피해 노인 전용 쉼터 지원',
    71080: '장애인 일자리 종합지원센터 운영',
    71158: '한국수산업경영인연합회 전국대회 지원',
    71382: '전라남도 자율방범연합회 운영비 지원',
    71195: '민주평화통일자문회의 전남지역회의 운영',
    71391: '전남 농업마이스터대학 교육과정장 지원',
    71351: '남도 음식문화 큰잔치 종가음식전시 지원',
    70996: '상이군경복지회관 기능보강사업',
    71311: '문화혁신대회 장애인청소년예술제',
    71231: '소비자 권익 보호사업(공모사업)',
    71300: '유림지도자 교양강좌(전남유교대학)',
    71407: '임업후계자 전국대회참가·교육지원',
    71383: '전라남도 지역특화작목발전협회 지원',
    52824: '재향경우회 보이스피싱 예방 및 홍보활동',
    53062: '찾아가는 에너지의 날 행사 보조'
}

# ------------------------------------------------------------
# 3) 보정 적용
# ------------------------------------------------------------

# 보정 여부 초기값
df_text['spacefix_applied'] = False

# 원본 index 기준으로 보정 적용
for idx, fixed_name in spacefix_map.items():
    if idx in df_text.index:
        df_text.loc[idx, '사업명_clean_spacefix'] = fixed_name
        df_text.loc[idx, 'spacefix_applied'] = True
    else:
        print(f"주의: index {idx}가 df_text에 없습니다.")

# ------------------------------------------------------------
# 4) 보정 결과 확인표 생성
# ------------------------------------------------------------

spacefix_review_cols = [
    '시도', '지자체명',
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'char_space_run_text',
    'spacefix_applied',
    '보조사업자',
    '평가결과',
    '평가종류'
]

existing_spacefix_review_cols = [
    col for col in spacefix_review_cols
    if col in df_text.columns
]

spacefix_review = (
    df_text.loc[df_text['char_space_issue_flag'], existing_spacefix_review_cols]
    .copy()
)

print("03-8. 글자 간 공백 명확 오류 보정 열 생성 완료")
print("- 글자 간 공백 의심 행 수:", int(df_text['char_space_issue_flag'].sum()))
print("- 보정 적용 행 수:", int(df_text['spacefix_applied'].sum()))
print("- 미보정 의심 행 수:", int(df_text['char_space_issue_flag'].sum() - df_text['spacefix_applied'].sum()))

print("\n[1] 글자 간 공백 의심 사례 보정 전후 확인")
display(spacefix_review)

# ------------------------------------------------------------
# 5) 보정 후에도 1글자 연속 구간이 남아 있는지 재진단
# ------------------------------------------------------------

df_text['char_space_runs_after_fix'] = df_text['사업명_clean_spacefix'].apply(find_single_hangul_runs)
df_text['char_space_run_count_after_fix'] = df_text['char_space_runs_after_fix'].apply(len)
df_text['char_space_issue_after_fix'] = df_text['char_space_run_count_after_fix'] > 0

after_fix_issue_rows = df_text.loc[df_text['char_space_issue_after_fix']].copy()

print("\n[2] 보정 후 글자 간 공백 의심 행 수")
print("- 보정 전 의심 행 수:", int(df_text['char_space_issue_flag'].sum()))
print("- 보정 후 의심 행 수:", int(df_text['char_space_issue_after_fix'].sum()))

print("\n[3] 보정 후에도 남은 의심 사례")
display(
    after_fix_issue_rows[
        [col for col in [
            '시도', '지자체명',
            '사업명_clean_spacefix',
            'char_space_runs_after_fix',
            '보조사업자',
            '평가결과'
        ] if col in after_fix_issue_rows.columns]
    ].head(30)
)

print("\n03-8 완료")
print("다음 단계에서는 사업명_clean_spacefix를 기준으로 전체 tokens_raw를 생성합니다.")

03-8. 글자 간 공백 명확 오류 보정 열 생성 완료
- 글자 간 공백 의심 행 수: 27
- 보정 적용 행 수: 15
- 미보정 의심 행 수: 12

[1] 글자 간 공백 의심 사례 보정 전후 확인

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,char_space_run_text,spacefix_applied,보조사업자,평가결과,평가종류
26155,충남,부여군,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도,False,부여군체육회,보통,성과평가
29885,충북,청주시,송범 춤 그 후,송범 춤 그 후,송범 춤 그 후,춤 그 후,False,송범춤사업회,미흡,유지필요성평가
35489,충북,제천시,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞,False,박명옥,매우우수,유지필요성평가
52824,경기,안양시,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예방 및 홍보활동,예 방 및,True,안양재향경우회,보통,성과평가
53062,경기,안양시,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행사 보조,날 행 사,True,안양기독교 청년회 (안양YMCA),보통,성과평가/유지필요성평가
70996,전남,본청,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관 기능보강사업,상이군경복지회관 기능보강사업,상 이 군 경 복 지 회 관,True,상이군경회 전남지부,미흡,성과평가
71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 ...,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),운 영 지 원 | 노 인 돌 봄,False,전남사회서비스원,우수,성과평가
71055,전남,본청,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서부 학대 피해 노인 전용 쉼터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터,True,서부학대피해노인전용쉼터,미흡,성과평가
71080,전남,본청,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터 운영,장애인 일자리 종합지원센터 운영,장 애 인 일 자 리 종 합 지 원 센 터,True,전라남도장애인단체총연합 회,보통,성과평가
71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 ...","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학",수 산 단 체 | 수 산 업 경 영 인,False,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71158,전남,본청,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한국수산업경영인연합회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회,True,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71195,전남,본청,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민주평화통일자문회의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의,True,민주평화통일자문회의 전남지역회의(우승하),우수,성과평가
71231,전남,본청,소 비 자 권 익 보호사업(공모사업),소 비 자 권 익 보호사업(공모사업),소비자 권익 보호사업(공모사업),소 비 자 권 익,True,한국소비자연맹전남목포지 회(박난숙) 한국부인회전남도지부(최두 례) 소비자교육중앙회전...,우수,성과평가
71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남...,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),회 복 사 업 | 성 균 관 유 도 회,False,성균관유도회 전남본부(문영수),미흡,성과평가
71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,False,성균관유도회 전남본부(문영수),보통,성과평가
71296,전남,본청,전남 유림신문 발 간 ( 성 균 관...,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),성 균 관 유 도 회,False,성균관유도회 전남본부(문영수),보통,성과평가
71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전...,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전 라 남 도 선 비 문 화 포 럼 | 성 균 관 청 년 유 도 회,False,성균관청년유도회 전남본부(박태성),보통,성과평가
71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 ...,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),학 술 회 | 성 균 관 청 년 유 도 회,False,성균관청년유도회 전남본부(박태성),보통,성과평가
71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유...,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),유 림 대 회 | 성 균 관 청 년 유 도 회,False,성균관청년유도회 전남본부(박태성),보통,성과평가
71300,전남,본청,유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자 교양강좌(전남유교대학),유림지도자 교양강좌(전남유교대학),유 림 지 도 자,True,전남향교재단(박대하),보통,성과평가
71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회...,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),성 균 관 여 성 유 도 회,False,성균관여성유도회 전남본부(박정재),보통,성과평가
71311,전남,본청,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회 장애인청소년예술제,문화혁신대회 장애인청소년예술제,문 화 혁 신 대 회,True,한국장애인문화전라남도협 회(이동기),우수,성과평가
71351,전남,본청,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남도 음식문화 큰잔치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치,True,(사)전라남도종가회,매우우수,성과평가
71382,전남,본청,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전라남도 자율방범연합회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회,True,전라남도자율방범연합회,우수,성과평가
71383,전남,본청,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도 지역특화작목발전협회 지원,전라남도 지역특화작목발전협회 지원,전 라 남 도,True,전라남도 지역특화작목발전협회(정병 준),보통,성과평가
71391,전남,본청,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전남 농업마이스터대학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학,True,전남농업마이스터대학,보통,성과평가
71407,전남,본청,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자 전국대회참가·교육지원,임업후계자 전국대회참가·교육지원,임 업 후 계 자,True,한국임업후계자협회(정재동),매우우수,성과평가

[2] 보정 후 글자 간 공백 의심 행 수
- 보정 전 의심 행 수: 27
- 보정 후 의심 행 수: 12

[3] 보정 후에도 남은 의심 사례

,시도,지자체명,사업명_clean_spacefix,char_space_runs_after_fix,보조사업자,평가결과
26155,충남,부여군,군 및 도 주관 생활체육대회 출전지원,[군 및 도],부여군체육회,보통
29885,충북,청주시,송범 춤 그 후,[춤 그 후],송범춤사업회,미흡
35489,충북,제천시,내 집 앞 주차장 갖기 사업,[내 집 앞],박명옥,매우우수
71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),"[운 영 지 원, 노 인 돌 봄]",전남사회서비스원,우수
71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학","[수 산 단 체, 수 산 업 경 영 인]",(사)한국수산업경영영인 전라남도연합회,보통
71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),"[회 복 사 업, 성 균 관 유 도 회]",성균관유도회 전남본부(문영수),미흡
71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),[성 균 관 유 도 회],성균관유도회 전남본부(문영수),보통
71296,전남,본청,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),[성 균 관 유 도 회],성균관유도회 전남본부(문영수),보통
71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),"[전 라 남 도 선 비 문 화 포 럼, 성 균 관 청 년 유 도 회]",성균관청년유도회 전남본부(박태성),보통
71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),"[학 술 회, 성 균 관 청 년 유 도 회]",성균관청년유도회 전남본부(박태성),보통
71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),"[유 림 대 회, 성 균 관 청 년 유 도 회]",성균관청년유도회 전남본부(박태성),보통
71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),[성 균 관 여 성 유 도 회],성균관여성유도회 전남본부(박정재),보통

03-8 완료
다음 단계에서는 사업명_clean_spacefix를 기준으로 전체 tokens_raw를 생성합니다.

03-8B. 남은 글자 간 공백 오류 추가 보정
1. 이 단계의 목적

03-8 이후에도 남아 있는 글자 간 공백 의심 사례 12개 중, 실제 오류로 보이는 9개만 추가 보정합니다.

원본 사업명, 기존 사업명_clean은 그대로 두고, 사업명_clean_spacefix만 수정합니다.

In [ ]:
# 03-8B. 남은 글자 간 공백 오류 추가 보정

# ------------------------------------------------------------
# 1) 보정 메모 열이 없으면 생성
# ------------------------------------------------------------

if 'spacefix_note' not in df_text.columns:
    df_text['spacefix_note'] = ''

# ------------------------------------------------------------
# 2) 추가 보정 사전
# ------------------------------------------------------------
# 원본 index 기준으로 명확한 오류만 보정합니다.
# 정상 표현으로 판단한 26155, 29885, 35489는 제외합니다.

additional_spacefix_map = {
    71048: '노인돌봄 광역지원기관 운영 지원 (노인돌봄 광역지원기관 종사자 처우개선)',
    71156: '수산단체 (수산업경영인, 여성어업인) 국내 선진지 현장견학',
    71294: '유림지도자 교육 및 도덕성 회복사업 (성균관유도회 전라남도본부)',
    71295: '도내 초중고생 효행실천수기집 발간 (성균관유도회 전라남도본부)',
    71296: '전남 유림신문 발간 (성균관유도회 전라남도본부)',
    71297: '전라남도 선비문화포럼 (성균관청년유도회 전라남도본부)',
    71298: '영호남 유교문화 교류 학술회 (성균관청년유도회 전라남도본부)',
    71299: '제11회 대한민국 청년 유림대회 (성균관청년유도회 전라남도본부)',
    71302: '제15회 맹모삼천지교 포럼 (성균관여성유도회 전라남도본부)'
}

# ------------------------------------------------------------
# 3) 추가 보정 적용
# ------------------------------------------------------------

for idx, fixed_name in additional_spacefix_map.items():
    if idx in df_text.index:
        df_text.loc[idx, '사업명_clean_spacefix'] = fixed_name
        df_text.loc[idx, 'spacefix_applied'] = True
        df_text.loc[idx, 'spacefix_note'] = '03-8B 추가 보정: 글자 간 공백 오류'
    else:
        print(f"주의: index {idx}가 df_text에 없습니다.")

# ------------------------------------------------------------
# 4) 추가 보정 전후 확인표
# ------------------------------------------------------------

additional_spacefix_review_cols = [
    '시도', '지자체명',
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'char_space_run_text',
    'spacefix_applied',
    'spacefix_note',
    '보조사업자',
    '평가결과',
    '평가종류'
]

existing_additional_spacefix_review_cols = [
    col for col in additional_spacefix_review_cols
    if col in df_text.columns
]

additional_spacefix_review = (
    df_text.loc[list(additional_spacefix_map.keys()), existing_additional_spacefix_review_cols]
    .copy()
)

print("03-8B. 남은 글자 간 공백 오류 추가 보정 완료")
print("- 추가 보정 적용 행 수:", len(additional_spacefix_map))

print("\n[1] 추가 보정 전후 확인")
display(additional_spacefix_review)

# ------------------------------------------------------------
# 5) 추가 보정 후 글자 간 공백 의심 사례 재진단
# ------------------------------------------------------------

df_text['char_space_runs_after_fix2'] = df_text['사업명_clean_spacefix'].apply(find_single_hangul_runs)
df_text['char_space_run_count_after_fix2'] = df_text['char_space_runs_after_fix2'].apply(len)
df_text['char_space_issue_after_fix2'] = df_text['char_space_run_count_after_fix2'] > 0

after_fix2_issue_rows = df_text.loc[df_text['char_space_issue_after_fix2']].copy()

print("\n[2] 추가 보정 후 글자 간 공백 의심 행 수")
print("- 03-8 이후 남은 의심 행 수:", int(df_text['char_space_issue_after_fix'].sum()))
print("- 03-8B 이후 남은 의심 행 수:", int(df_text['char_space_issue_after_fix2'].sum()))

print("\n[3] 추가 보정 후에도 남은 의심 사례")
display(
    after_fix2_issue_rows[
        [col for col in [
            '시도', '지자체명',
            '사업명_clean_spacefix',
            'char_space_runs_after_fix2',
            '보조사업자',
            '평가결과'
        ] if col in after_fix2_issue_rows.columns]
    ].head(30)
)

print("\n03-8B 완료")
print("남은 의심 사례가 '군 및 도', '춤 그 후', '내 집 앞' 정도라면 정상 표현으로 보고 다음 토큰화 단계로 넘어가면 됩니다.")

03-8B. 남은 글자 간 공백 오류 추가 보정 완료
- 추가 보정 적용 행 수: 9

[1] 추가 보정 전후 확인

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,char_space_run_text,spacefix_applied,spacefix_note,보조사업자,평가결과,평가종류
71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 ...,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),노인돌봄 광역지원기관 운영 지원 (노인돌봄 광역지원기관 종사자 처우개선),운 영 지 원 | 노 인 돌 봄,True,03-8B 추가 보정: 글자 간 공백 오류,전남사회서비스원,우수,성과평가
71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 ...","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학","수산단체 (수산업경영인, 여성어업인) 국내 선진지 현장견학",수 산 단 체 | 수 산 업 경 영 인,True,03-8B 추가 보정: 글자 간 공백 오류,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남...,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),유림지도자 교육 및 도덕성 회복사업 (성균관유도회 전라남도본부),회 복 사 업 | 성 균 관 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관유도회 전남본부(문영수),미흡,성과평가
71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발간 (성균관유도회 전라남도본부),성 균 관 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관유도회 전남본부(문영수),보통,성과평가
71296,전남,본청,전남 유림신문 발 간 ( 성 균 관...,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),전남 유림신문 발간 (성균관유도회 전라남도본부),성 균 관 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관유도회 전남본부(문영수),보통,성과평가
71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전...,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전라남도 선비문화포럼 (성균관청년유도회 전라남도본부),전 라 남 도 선 비 문 화 포 럼 | 성 균 관 청 년 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관청년유도회 전남본부(박태성),보통,성과평가
71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 ...,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),영호남 유교문화 교류 학술회 (성균관청년유도회 전라남도본부),학 술 회 | 성 균 관 청 년 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관청년유도회 전남본부(박태성),보통,성과평가
71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유...,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),제11회 대한민국 청년 유림대회 (성균관청년유도회 전라남도본부),유 림 대 회 | 성 균 관 청 년 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관청년유도회 전남본부(박태성),보통,성과평가
71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회...,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),제15회 맹모삼천지교 포럼 (성균관여성유도회 전라남도본부),성 균 관 여 성 유 도 회,True,03-8B 추가 보정: 글자 간 공백 오류,성균관여성유도회 전남본부(박정재),보통,성과평가

[2] 추가 보정 후 글자 간 공백 의심 행 수
- 03-8 이후 남은 의심 행 수: 12
- 03-8B 이후 남은 의심 행 수: 3

[3] 추가 보정 후에도 남은 의심 사례

       시도 지자체명    사업명_clean_spacefix char_space_runs_after_fix2   보조사업자  평가결과
26155  충남  부여군  군 및 도 주관 생활체육대회 출전지원                    [군 및 도]  부여군체육회    보통
29885  충북  청주시              송범 춤 그 후                    [춤 그 후]  송범춤사업회    미흡
35489  충북  제천시       내 집 앞 주차장 갖기 사업                    [내 집 앞]     박명옥  매우우수

03-8B 완료
남은 의심 사례가 '군 및 도', '춤 그 후', '내 집 앞' 정도라면 정상 표현으로 보고 다음 토큰화 단계로 넘어가면 됩니다.

In [ ]:
# 03-8C. 글자 간 공백 보정 최종 확인용 열 생성

# 보정 후 남은 의심 구간을 사람이 보기 쉬운 문자열로 변환
df_text['char_space_run_text_after_fix2'] = df_text['char_space_runs_after_fix2'].apply(
    lambda runs: ' | '.join(runs) if len(runs) > 0 else ''
)

# 최종 확인표
final_spacefix_check = df_text.loc[
    df_text['char_space_issue_after_fix2'],
    [
        '시도',
        '지자체명',
        '사업명',
        '사업명_clean',
        '사업명_clean_spacefix',
        'char_space_run_text',
        'char_space_run_text_after_fix2',
        'spacefix_applied',
        'spacefix_note',
        '보조사업자',
        '평가결과'
    ]
].copy()

print("03-8C. 글자 간 공백 보정 최종 확인")
print("- 보정 후 남은 의심 행 수:", len(final_spacefix_check))

display(final_spacefix_check)

03-8C. 글자 간 공백 보정 최종 확인
- 보정 후 남은 의심 행 수: 3

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,char_space_run_text,char_space_run_text_after_fix2,spacefix_applied,spacefix_note,보조사업자,평가결과
26155,충남,부여군,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도 주관 생활체육대회 출전지원,군 및 도,군 및 도,False,,부여군체육회,보통
29885,충북,청주시,송범 춤 그 후,송범 춤 그 후,송범 춤 그 후,춤 그 후,춤 그 후,False,,송범춤사업회,미흡
35489,충북,제천시,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞 주차장 갖기 사업,내 집 앞,내 집 앞,False,,박명옥,매우우수

03-9. 전체 tokens_raw 생성
1. 이 단계의 목적

이 단계는 사업명_clean_spacefix를 기준으로 전체 사업명에 형태소 분석을 적용하여, 분석용 원시 토큰 열인 tokens_raw를 생성하는 단계입니다.

중요한 점은 다음입니다.

원본 사업명은 수정하지 않습니다.
사업명_clean도 수정하지 않습니다.
글자 간 공백 보정이 반영된 사업명_clean_spacefix를 기준으로 토큰화합니다.
이 단계에서는 아직 불용어를 제거하지 않습니다.
지원, 사업, 운영, 숫자, 지역명 등도 일단 tokens_raw에는 남깁니다.
불용어 제거는 다음 단계에서 빈도표와 실제 사례를 본 뒤 진행합니다.


2. 입력 데이터

이전 단계까지 만든 데이터프레임입니다.

df_text


필수 열은 다음입니다.

사업명_clean_spacefix


그리고 03-7에서 생성한 형태소 분석기 객체가 필요합니다.

kiwi

| 변수명                    | 의미                      |
| ---------------------- | ----------------------- |
| `noun_like_tags`       | 추출할 품사 목록               |
| `extract_tokens_raw()` | 사업명에서 명사 계열 토큰을 추출하는 함수 |
| `tokens_raw`           | 형태소 분석 후 추출한 원시 토큰 리스트  |
| `tokens_raw_count`     | 행별 원시 토큰 개수             |
| `tokens_raw_empty`     | 토큰이 비어 있는지 여부           |
| `token_check_sample`   | 토큰화 결과 확인용 샘플           |

In [ ]:
# 03-9. 전체 tokens_raw 생성

# ------------------------------------------------------------
# 1) tqdm 불러오기
# ------------------------------------------------------------
# tqdm은 전체 79,262행 토큰화 진행률을 보기 위한 도구입니다.

from tqdm.auto import tqdm

tqdm.pandas()


# ------------------------------------------------------------
# 2) 형태소 분석기 객체 확인
# ------------------------------------------------------------
# 03-7을 실행했다면 kiwi 객체가 이미 있어야 합니다.
# 만약 런타임이 초기화되어 kiwi가 없다면 다시 생성합니다.

try:
    kiwi
    print("기존 kiwi 객체를 사용합니다.")
except NameError:
    from kiwipiepy import Kiwi
    kiwi = Kiwi()
    print("kiwi 객체가 없어 새로 생성했습니다.")


# ------------------------------------------------------------
# 3) 추출할 품사 기준 설정
# ------------------------------------------------------------
# NNG: 일반명사
# NNP: 고유명사
# SL : 외국어/영문
# SN : 숫자
#
# 주의:
# 숫자(SN)는 일단 tokens_raw에는 남겨둡니다.
# 이후 tokens_filtered 단계에서 연도/숫자 토큰 제거 여부를 판단합니다.

noun_like_tags = ['NNG', 'NNP', 'SL', 'SN']


# ------------------------------------------------------------
# 4) 원시 토큰 추출 함수 정의
# ------------------------------------------------------------

def extract_tokens_raw(text):
    """
    사업명 텍스트에서 명사 계열 토큰을 추출합니다.

    입력:
    - text: 사업명_clean_spacefix

    출력:
    - 명사 계열 토큰 리스트

    주의:
    - 이 함수는 불용어를 제거하지 않습니다.
    - 숫자, 지역명, 행정 일반어도 일단 보존합니다.
    - 불용어 제거는 다음 단계에서 별도로 수행합니다.
    """

    if pd.isna(text):
        return []

    text = str(text).strip()

    if text == '':
        return []

    analyzed = kiwi.tokenize(text)

    tokens = []

    for token in analyzed:
        token_text = token.form.strip()
        token_tag = token.tag

        # 명사 계열 품사만 우선 추출
        if token_tag in noun_like_tags and token_text != '':
            tokens.append(token_text)

    return tokens


# ------------------------------------------------------------
# 5) 전체 df_text에 tokens_raw 생성
# ------------------------------------------------------------
# 기준 열은 사업명_clean_spacefix입니다.
# 글자 간 공백 보정이 반영된 열을 사용해야 합니다.

df_text['tokens_raw'] = df_text['사업명_clean_spacefix'].progress_apply(extract_tokens_raw)

# 행별 토큰 개수
df_text['tokens_raw_count'] = df_text['tokens_raw'].apply(len)

# 토큰이 비어 있는지 여부
df_text['tokens_raw_empty'] = df_text['tokens_raw_count'].eq(0)


# ------------------------------------------------------------
# 6) tokens_raw 생성 결과 요약
# ------------------------------------------------------------

tokens_raw_summary = pd.DataFrame({
    '항목': [
        '텍스트 분석 대상 행 수',
        'tokens_raw 생성 행 수',
        'tokens_raw 빈 행 수',
        'tokens_raw 빈 행 비율(%)',
        '행별 평균 토큰 수',
        '행별 최소 토큰 수',
        '행별 최대 토큰 수'
    ],
    '값': [
        len(df_text),
        df_text['tokens_raw'].notna().sum(),
        int(df_text['tokens_raw_empty'].sum()),
        round(df_text['tokens_raw_empty'].mean() * 100, 3),
        round(df_text['tokens_raw_count'].mean(), 3),
        int(df_text['tokens_raw_count'].min()),
        int(df_text['tokens_raw_count'].max())
    ]
})

print("03-9. 전체 tokens_raw 생성 완료")
display(tokens_raw_summary)


# ------------------------------------------------------------
# 7) 토큰화 결과 샘플 확인
# ------------------------------------------------------------
# 일반 샘플과 글자 간 공백 보정 적용 사례를 함께 확인합니다.

sample_cols = [
    '시도',
    '지자체명',
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'spacefix_applied',
    'tokens_raw',
    'tokens_raw_count',
    '보조사업자',
    '평가결과',
    '평가종류'
]

existing_sample_cols = [col for col in sample_cols if col in df_text.columns]

print("\n[1] 전체 토큰화 결과 샘플 30개")
display(
    df_text[existing_sample_cols]
    .head(30)
)


print("\n[2] 글자 간 공백 보정 적용 행의 토큰화 결과")
display(
    df_text.loc[
        df_text['spacefix_applied'],
        existing_sample_cols
    ].head(30)
)


# ------------------------------------------------------------
# 8) tokens_raw가 비어 있는 행 확인
# ------------------------------------------------------------

empty_token_rows = df_text.loc[df_text['tokens_raw_empty'], existing_sample_cols].copy()

print("\n[3] tokens_raw가 비어 있는 행")
print("- 빈 토큰 행 수:", len(empty_token_rows))
display(empty_token_rows.head(30))


# ------------------------------------------------------------
# 9) 토큰 개수가 많은 행 확인
# ------------------------------------------------------------
# 너무 많은 토큰이 생성된 행은 괄호 안 설명이 길거나 여러 사업명이 붙어 있을 수 있습니다.

print("\n[4] tokens_raw_count 상위 30개")
display(
    df_text
    .sort_values('tokens_raw_count', ascending=False)
    [existing_sample_cols]
    .head(30)
)


print("\n03-9 완료")
print("다음 단계에서는 tokens_raw 전체 빈도표를 만들고, 불용어 후보를 검토합니다.")

기존 kiwi 객체를 사용합니다.

  0%|          | 0/79262 [00:00<?, ?it/s]

03-9. 전체 tokens_raw 생성 완료

                     항목          값
0         텍스트 분석 대상 행 수  79262.000
1     tokens_raw 생성 행 수  79262.000
2      tokens_raw 빈 행 수      4.000
3  tokens_raw 빈 행 비율(%)      0.005
4            행별 평균 토큰 수      5.263
5            행별 최소 토큰 수      0.000
6            행별 최대 토큰 수     24.000

[1] 전체 토큰화 결과 샘플 30개

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,spacefix_applied,tokens_raw,tokens_raw_count,보조사업자,평가결과,평가종류
0,경남,남해군,마늘재배 영농지원단 지원,마늘재배 영농지원단 지원,마늘재배 영농지원단 지원,False,"[마늘, 재배, 영농, 지원단, 지원]",5,농협중앙회 남해군지부,매우우수,유지필요성평가
1,경남,남해군,2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영,2023년 사)진주지역범죄피해자지원센터'등불 '남해지부 운영,2023년 사)진주지역범죄피해자지원센터'등불 '남해지부 운영,False,"[2023, 진주, 지역, 범죄, 피해자, 지원, 센터, 등불, 남해, 지부, 운영]",11,사단법인진주지역범죄피 해자지원센터남해지부,미흡,유지필요성평가
2,경남,남해군,자유민주주의신장 및 자유선진의식 고취,자유민주주의신장 및 자유선진의식 고취,자유민주주의신장 및 자유선진의식 고취,False,"[자유, 민주주의, 신장, 자유선진, 의식, 고취]",6,한국자유총연맹남해군지 회,미흡,유지필요성평가
3,경남,남해군,보물섬 독서학교 지원,보물섬 독서학교 지원,보물섬 독서학교 지원,False,"[보물섬, 독서, 학교, 지원]",4,보물섬남해독서학교,미흡,유지필요성평가
4,경남,남해군,참전경찰유공자 보훈활동,참전경찰유공자 보훈활동,참전경찰유공자 보훈활동,False,"[참전, 경찰, 유공자, 보훈, 활동]",5,한국참전경찰유공자회,미흡,유지필요성평가
5,경남,남해군,무공수훈자회 운영비 보조,무공수훈자회 운영비 보조,무공수훈자회 운영비 보조,False,"[무공, 수훈자, 회, 운영비, 보조]",5,대한민국무공수훈자회남 해 군 지 회,미흡,유지필요성평가
6,경남,남해군,행복나눔센터 운영,행복나눔센터 운영,행복나눔센터 운영,False,"[행복, 센터, 운영]",3,남해군지역사회보장협의 체,미흡,유지필요성평가
7,경남,남해군,경로당 양곡구입비 지원,경로당 양곡구입비 지원,경로당 양곡구입비 지원,False,"[경로당, 양곡, 구입비, 지원]",4,봉내경로당 외 10개소,미흡,유지필요성평가
8,경남,남해군,장애인직업재활 자활교육,장애인직업재활 자활교육,장애인직업재활 자활교육,False,"[장애인, 직업, 재활, 자활, 교육]",5,남해장애인종합복지관,미흡,유지필요성평가
9,경남,남해군,어린이집 운전기사 인건비 (미조지역영유아수송),어린이집 운전기사 인건비 (미조지역영유아수송),어린이집 운전기사 인건비 (미조지역영유아수송),False,"[어린이집, 운전기사, 인건비, 미조, 지역, 영유아, 수송]",7,모 모 어 린 이 집,미흡,유지필요성평가
10,경남,남해군,아동 일일나들이 행사,아동 일일나들이 행사,아동 일일나들이 행사,False,"[아동, 일일, 나들이, 행사]",4,남해군아동위원 협의회,미흡,유지필요성평가
11,경남,남해군,문화학교 운영,문화학교 운영,문화학교 운영,False,"[문화, 학교, 운영]",3,남 해 문 화 원,미흡,유지필요성평가
12,경남,남해군,남중권생활체육 교류 지원,남중권생활체육 교류 지원,남중권생활체육 교류 지원,False,"[남, 생활, 체육, 교류, 지원]",5,남 해 군 체 육 회,미흡,유지필요성평가
13,경남,남해군,"전국대회 운영(구급차, 응급의료 등) 지원","전국대회 운영(구급차, 응급의료 등) 지원","전국대회 운영(구급차, 응급의료 등) 지원",False,"[전국, 대회, 운영, 구급차, 응급, 의료, 지원]",7,남 해 군 체 육 회,미흡,유지필요성평가
14,경남,남해군,레포츠 자격증 취득 지원,레포츠 자격증 취득 지원,레포츠 자격증 취득 지원,False,"[레포츠, 자격증, 취득, 지원]",4,남 해 군 체 육 회,미흡,유지필요성평가
15,경남,남해군,수산물 상생할인 지원사업,수산물 상생할인 지원사업,수산물 상생할인 지원사업,False,"[수산물, 상생, 할인, 지원, 사업]",5,남 해 군 수 협,미흡,유지필요성평가
16,경남,남해군,마을어장 개발,마을어장 개발,마을어장 개발,False,"[마을, 어장, 개발]",3,갈화어촌계 외 6 개소,미흡,유지필요성평가
17,경남,남해군,자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),False,"[자연, 환경, 보전, 활동, 사업, 자연보호, 정화, 활동, 군, 수기, 경진, 대회]",12,(사)자연보호연맹남해군협의회,미흡,유지필요성평가
18,경남,남해군,2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),False,"[2023, 음식점, 위생, 환경, 개선, 사업, 시설, 환경, 개선, 입식, 테이...",12,갯내음 외 1 9 개소,미흡,유지필요성평가
19,경남,남해군,농촌신활력 플러스사업 (추진단사무국상근직원인건비),농촌신활력 플러스사업 (추진단사무국상근직원인건비),농촌신활력 플러스사업 (추진단사무국상근직원인건비),False,"[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원, 인건비]",7,남해군신활력플러스사업추진단,미흡,유지필요성평가
20,경남,남해군,GAP 인증농산물 포장재 지원사업,GAP 인증농산물 포장재 지원사업,GAP 인증농산물 포장재 지원사업,False,"[GAP, 인증, 농산물, 포장재, 지원, 사업]",6,남해느루농원 외 3개소,미흡,유지필요성평가
21,경남,남해군,2023년 범죄피해자 지원 및 지원센터‘등불’운영,2023년 범죄피해자 지원 및 지원센터'등불'운영,2023년 범죄피해자 지원 및 지원센터'등불'운영,False,"[2023, 범죄, 피해자, 지원, 지원, 센터, 등불, 운영]",8,사)진주지역범죄피해자지 원 센 터 ‘ 등 불 ’,보통,유지필요성평가
22,경남,남해군,2023년 보물섬 남해포럼 운영,2023년 보물섬 남해포럼 운영,2023년 보물섬 남해포럼 운영,False,"[2023, 보물섬, 남해, 포럼, 운영]",5,보물섬 남해포럼,보통,유지필요성평가
23,경남,남해군,전입세대 빈집수리 지원,전입세대 빈집수리 지원,전입세대 빈집수리 지원,False,"[전입, 세대, 빈집, 수리, 지원]",5,형 O O 외 1 명,보통,유지필요성평가
24,경남,남해군,제13회 새마을의 날 기념식,제13회 새마을의 날 기념식,제13회 새마을의 날 기념식,False,"[13, 마을, 날, 기념식]",4,새마을운동남해군지회,보통,유지필요성평가
25,경남,남해군,2023년 남해군 새마을지도자 대회,2023년 남해군 새마을지도자 대회,2023년 남해군 새마을지도자 대회,False,"[2023, 남해군, 마을, 지도자, 대회]",5,새마을운동남해군지회,보통,유지필요성평가
26,경남,남해군,새마을지도자 화합한마음대회,새마을지도자 화합한마음대회,새마을지도자 화합한마음대회,False,"[새마을, 지도자, 화합, 마음, 대회]",5,새마을운동남해군지회,보통,유지필요성평가
27,경남,남해군,국민의식개혁 및 기초질서확립운동,국민의식개혁 및 기초질서확립운동,국민의식개혁 및 기초질서확립운동,False,"[국민, 의식, 개혁, 기초, 질서, 확립, 운동]",7,바르게살기운동남해군협 의 회,보통,유지필요성평가
28,경남,남해군,방범활동 및 남해바다 수중정화활동,방범활동 및 남해바다 수중정화활동,방범활동 및 남해바다 수중정화활동,False,"[방범, 활동, 남해, 바다, 수중, 정화, 활동]",7,해병대남해군전우,보통,유지필요성평가
29,경남,남해군,바르게살기운동남해군협의회 운영비 지원,바르게살기운동남해군협의회 운영비 지원,바르게살기운동남해군협의회 운영비 지원,False,"[운동, 남, 해군, 협의회, 운영비, 지원]",6,바르게살기운동남해군협 의 회,보통,유지필요성평가

[2] 글자 간 공백 보정 적용 행의 토큰화 결과

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,spacefix_applied,tokens_raw,tokens_raw_count,보조사업자,평가결과,평가종류
52824,경기,안양시,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예 방 및 홍보활동,재향경우회 보이스피싱 예방 및 홍보활동,True,"[재향경우회, 보이스피싱, 예방, 홍보, 활동]",5,안양재향경우회,보통,성과평가
53062,경기,안양시,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행 사 보조,찾아가는 에너지의 날 행사 보조,True,"[에너지, 날, 행사, 보조]",4,안양기독교 청년회 (안양YMCA),보통,성과평가/유지필요성평가
70996,전남,본청,상 이 군 경 복 지 회 관 기능보강사업,상 이 군 경 복 지 회 관 기능보강사업,상이군경복지회관 기능보강사업,True,"[상이, 군경, 복지, 회관, 기능, 보강, 사업]",7,상이군경회 전남지부,미흡,성과평가
71048,전남,본청,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 ...,노인돌봄 광역지원기관 운 영 지 원 ( 노 인 돌 봄 광역지원기관 종사자 처우개선),노인돌봄 광역지원기관 운영 지원 (노인돌봄 광역지원기관 종사자 처우개선),True,"[노인, 돌봄, 광역, 지원, 기관, 운영, 지원, 노인, 돌봄, 광역, 지원, 기...",15,전남사회서비스원,우수,성과평가
71055,전남,본청,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서 부 학 대 피 해 노 인 전 용 쉼 터 지원,서부 학대 피해 노인 전용 쉼터 지원,True,"[서부, 학대, 피해, 노인, 전용, 쉼터, 지원]",7,서부학대피해노인전용쉼터,미흡,성과평가
71080,전남,본청,장 애 인 일 자 리 종 합 지 원 센 터 운영,장 애 인 일 자 리 종 합 지 원 센 터 운영,장애인 일자리 종합지원센터 운영,True,"[장애인, 일자리, 종합, 지원, 센터, 운영]",6,전라남도장애인단체총연합 회,보통,성과평가
71156,전남,본청,"수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 ...","수 산 단 체 ( 수 산 업 경 영 인 , 여성어업인) 국내 선진지 현장견학","수산단체 (수산업경영인, 여성어업인) 국내 선진지 현장견학",True,"[수산, 단체, 수산업, 경영인, 여성, 어업인, 국내, 선진, 지, 현장, 견학]",11,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71158,전남,본청,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한 국 수 산 업 경 영 인 연 합 회 전국대회 지원,한국수산업경영인연합회 전국대회 지원,True,"[한국, 수산업, 경영인, 연합회, 전국, 대회, 지원]",7,(사)한국수산업경영영인 전라남도연합회,보통,성과평가
71195,전남,본청,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민 주 평 화 통 일 자 문 회 의 전남지역회의 운영,민주평화통일자문회의 전남지역회의 운영,True,"[민주, 평화, 통일, 자문, 회의, 전남, 지역, 회의, 운영]",9,민주평화통일자문회의 전남지역회의(우승하),우수,성과평가
71231,전남,본청,소 비 자 권 익 보호사업(공모사업),소 비 자 권 익 보호사업(공모사업),소비자 권익 보호사업(공모사업),True,"[소비자, 권익, 보호, 사업, 공모사업]",5,한국소비자연맹전남목포지 회(박난숙) 한국부인회전남도지부(최두 례) 소비자교육중앙회전...,우수,성과평가
71294,전남,본청,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남...,유림지도자 교육 및 도덕성 회 복 사 업 ( 성 균 관 유 도 회 전라남도본부),유림지도자 교육 및 도덕성 회복사업 (성균관유도회 전라남도본부),True,"[유림, 지도자, 교육, 도덕, 회복, 사업, 성균관, 유도회, 전라남도, 본부]",10,성균관유도회 전남본부(문영수),미흡,성과평가
71295,전남,본청,도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발 간 ( 성 균 관 유 도 회 전라남도본부),도내 초중고생 효행실천수기집 발간 (성균관유도회 전라남도본부),True,"[도내, 초, 중, 고, 효행, 실천, 수기, 발간, 성균관, 유도회, 전라남도, 본부]",12,성균관유도회 전남본부(문영수),보통,성과평가
71296,전남,본청,전남 유림신문 발 간 ( 성 균 관...,전남 유림신문 발 간 ( 성 균 관 유 도 회 전라남도본부),전남 유림신문 발간 (성균관유도회 전라남도본부),True,"[전남, 유림, 신문, 발간, 성균관, 유도회, 전라남도, 본부]",8,성균관유도회 전남본부(문영수),보통,성과평가
71297,전남,본청,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전...,전 라 남 도 선 비 문 화 포 럼 ( 성 균 관 청 년 유 도 회 전라남도본부),전라남도 선비문화포럼 (성균관청년유도회 전라남도본부),True,"[전라남도, 선비, 문화, 포럼, 성균관청년유도회, 전라남도, 본부]",7,성균관청년유도회 전남본부(박태성),보통,성과평가
71298,전남,본청,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 ...,영호남 유교문화 교류 학 술 회 ( 성 균 관 청 년 유 도 회 전라남도본부),영호남 유교문화 교류 학술회 (성균관청년유도회 전라남도본부),True,"[영호남, 유교, 문화, 교류, 학술, 회, 성균관, 청년, 유도, 회, 전라남도,...",12,성균관청년유도회 전남본부(박태성),보통,성과평가
71299,전남,본청,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유...,제11회 대한민국 청년 유 림 대 회 ( 성 균 관 청 년 유 도 회 전라남도본부),제11회 대한민국 청년 유림대회 (성균관청년유도회 전라남도본부),True,"[11, 대한민국, 청년, 유림대회, 성균관, 청년, 유도, 회, 전라남도, 본부]",10,성균관청년유도회 전남본부(박태성),보통,성과평가
71300,전남,본청,유 림 지 도 자 교양강좌(전남유교대학),유 림 지 도 자 교양강좌(전남유교대학),유림지도자 교양강좌(전남유교대학),True,"[유림, 지도자, 교양, 강좌, 전남, 유교, 대학]",7,전남향교재단(박대하),보통,성과평가
71302,전남,본청,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회...,제15회 맹모삼천지교 포 럼 ( 성 균 관 여 성 유 도 회 전라남도본부),제15회 맹모삼천지교 포럼 (성균관여성유도회 전라남도본부),True,"[15, 맹모삼천, 지, 교, 포럼, 성균관, 여성, 유도, 회, 전라남도, 본부]",11,성균관여성유도회 전남본부(박정재),보통,성과평가
71311,전남,본청,문 화 혁 신 대 회 장애인청소년예술제,문 화 혁 신 대 회 장애인청소년예술제,문화혁신대회 장애인청소년예술제,True,"[문화, 혁신, 대회, 장애인, 청소년, 예술제]",6,한국장애인문화전라남도협 회(이동기),우수,성과평가
71351,전남,본청,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남 도 음 식 문 화 큰 잔 치 종가음식전시 지원,남도 음식문화 큰잔치 종가음식전시 지원,True,"[남도, 음식, 문화, 잔치, 종가, 음식, 전시, 지원]",8,(사)전라남도종가회,매우우수,성과평가
71382,전남,본청,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전 라 남 도 자 율 방 범 연 합 회 운영비 지원,전라남도 자율방범연합회 운영비 지원,True,"[전라남도, 자율, 방범, 연합회, 운영비, 지원]",6,전라남도자율방범연합회,우수,성과평가
71383,전남,본청,전 라 남 도 지역특화작목발전협회 지원,전 라 남 도 지역특화작목발전협회 지원,전라남도 지역특화작목발전협회 지원,True,"[전라남도, 지역, 특화, 작목, 발전, 협회, 지원]",7,전라남도 지역특화작목발전협회(정병 준),보통,성과평가
71391,전남,본청,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전 남 농 업 마 이 스 터 대 학 교육과정장 지원,전남 농업마이스터대학 교육과정장 지원,True,"[전남, 농업, 마이스터, 대학, 교육, 과정, 장, 지원]",8,전남농업마이스터대학,보통,성과평가
71407,전남,본청,임 업 후 계 자 전국대회참가·교육지원,임 업 후 계 자 전국대회참가·교육지원,임업후계자 전국대회참가·교육지원,True,"[임업, 후계자, 전국, 대회, 참가, 교육, 지원]",7,한국임업후계자협회(정재동),매우우수,성과평가

[3] tokens_raw가 비어 있는 행
- 빈 토큰 행 수: 4

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,spacefix_applied,tokens_raw,tokens_raw_count,보조사업자,평가결과,평가종류
1841,경남,창원시,열아홉을 위하여,열아홉을 위하여,열아홉을 위하여,False,[],0,경남도민일보,미흡,유지필요성평가
9374,경남,본청,다함께 해 봄,다함께 해 봄,다함께 해 봄,False,[],0,창원여성의집,보통,성과평가
9387,경남,본청,왔노라 보았노라 통했노라,왔노라 보았노라 통했노라,왔노라 보았노라 통했노라,False,[],0,한국해양소년단경 남남부연맹,보통,성과평가
22417,울산,동구,함께 나누며 느껴요,함께 나누며 느껴요,함께 나누며 느껴요,False,[],0,동구여성전문봉사회,매우우수,성과평가

[4] tokens_raw_count 상위 30개

,시도,지자체명,사업명,사업명_clean,사업명_clean_spacefix,spacefix_applied,tokens_raw,tokens_raw_count,보조사업자,평가결과,평가종류
10383,인천,계양구,"지역사회보장협의체 운영 동 보장협의체 지역주민복지사업비 지원(2021, 2022) ...","지역사회보장협의체 운영 동 보장협의체 지역주민복지사업비 지원(2021, 2022) ...","지역사회보장협의체 운영 동 보장협의체 지역주민복지사업비 지원(2021, 2022) ...",False,"[지역, 사회, 보장, 협의체, 운영, 동, 보장협의체, 지역, 주민, 복지, 사업...",24,12개 동 보장협의체,우수,유지필요성평가
40255,강원,속초시,"어구보수보관장 시설지원 사업 (청호어촌계 어구보수보관장 비가림 공사, 교통어촌계 어...","어구보수보관장 시설지원 사업 (청호어촌계 어구보수보관장 비가림 공사, 교통어촌계 어...","어구보수보관장 시설지원 사업 (청호어촌계 어구보수보관장 비가림 공사, 교통어촌계 어...",False,"[어구, 보수, 보관, 장, 시설, 지원, 사업, 청호, 어촌계, 어구, 보수, 보...",23,속초시 수산업협동조합,보통,성과평가/유지필요성평가
12423,대전,본청,시소유공영주차장유지관리 ―대흥동제1노외공영주차장(중구) ―원내동공영주차장등 18개소...,시소유공영주차장유지관리 ―대흥동제1노외공영주차장(중구) ―원내동공영주차장등 18개소...,시소유공영주차장유지관리 ―대흥동제1노외공영주차장(중구) ―원내동공영주차장등 18개소...,False,"[시, 소유, 공영, 주차장, 유지, 관리, 대흥동, 1, 노외공영주차장, 중구, ...",23,"중구청, 유성구청, 대덕구청",매우우수,성과평가
8409,경남,본청,국제 및 전국규모 스포츠대회 유치지원(전문체육) (통영) 윤덕주배 제35회 연맹회장...,국제 및 전국규모 스포츠대회 유치지원(전문체육) (통영) 윤덕주배 제35회 연맹회장...,국제 및 전국규모 스포츠대회 유치지원(전문체육) (통영) 윤덕주배 제35회 연맹회장...,False,"[국제, 전국, 규모, 스포츠, 대회, 유치, 지원, 전문, 체육, 통영, 윤, 덕...",22,통영시,보통,성과평가
10393,인천,계양구,"특성별 지역아동센터 추가 지원(‘21) 지역아동센터특성별추가지원(’22, ‘23) ...","특성별 지역아동센터 추가 지원('21) 지역아동센터특성별추가지원('22, '23) ...","특성별 지역아동센터 추가 지원('21) 지역아동센터특성별추가지원('22, '23) ...",False,"[특성, 지역, 아동, 센터, 추가, 지원, 21, 지역, 아동, 센터, 특성, 추...",22,관내 지역아동센터 7개소,우수,유지필요성평가
8419,경남,본청,국제 및 전국규모 스포츠대회 유치지원(생활체육) (밀양) 제31회 문화체육관광부장관...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (밀양) 제31회 문화체육관광부장관...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (밀양) 제31회 문화체육관광부장관...,False,"[국제, 전국, 규모, 스포츠, 대회, 유치, 지원, 생활, 체육, 밀양, 31, ...",21,밀양시,우수,성과평가
12375,대전,본청,"FTA대비축산농가지원 ―한우브랜드육성지원, 축산농가조사료공급, 한우수정란이식지원, ...","FTA대비축산농가지원 ―한우브랜드육성지원, 축산농가조사료공급, 한우수정란이식지원, ...","FTA대비축산농가지원 ―한우브랜드육성지원, 축산농가조사료공급, 한우수정란이식지원, ...",False,"[FTA, 대비, 축산, 농가, 지원, 한우, 브랜드, 육성, 지원, 축산, 농가,...",21,대전축협,매우우수,성과평가
828,경남,진주시,지역 문화 진흥 공모사업 (문화유산 재발견 (진주교방음식의 전망과 과제진주와 평양의...,지역 문화 진흥 공모사업 (문화유산 재발견 (진주교방음식의 전망과 과제진주와 평양의...,지역 문화 진흥 공모사업 (문화유산 재발견 (진주교방음식의 전망과 과제진주와 평양의...,False,"[지역, 문화, 진흥, 공모, 사업, 문화유산, 발견, 진주, 교, 방, 음식, 전...",21,진주향당,보통,성과평가
59193,경북,영주시,"영주농산물 1등 브랜드 프로젝트 사업 ―영주농산물 홍보마케팅 및 국내외시장개척,워크...","영주농산물 1등 브랜드 프로젝트 사업 ―영주농산물 홍보마케팅 및 국내외시장개척,워크...","영주농산물 1등 브랜드 프로젝트 사업 ―영주농산물 홍보마케팅 및 국내외시장개척,워크...",False,"[영주, 농산물, 1, 브랜드, 프로젝트, 사업, 영주, 농산물, 홍보, 마케팅, ...",20,농협경제지주(주)영주시 연합사업단,우수,성과평가
10376,인천,계양구,계양학 마을길 운영 <2021> 계양학학습길운영<2022> 계양학마을길운영<2023...,계양학 마을길 운영 <2021> 계양학학습길운영<2022> 계양학마을길운영<2023...,계양학 마을길 운영 <2021> 계양학학습길운영<2022> 계양학마을길운영<2023...,False,"[계양, 학, 마을, 길, 운영, 2021, 계양학학습길운영, 2022, 계양학마을...",20,계양문화원,우수,유지필요성평가
8410,경남,본청,국제 및 전국규모 스포츠대회 유치지원(전문체육) (사천) 2023년 초등연맹회장기 ...,국제 및 전국규모 스포츠대회 유치지원(전문체육) (사천) 2023년 초등연맹회장기 ...,국제 및 전국규모 스포츠대회 유치지원(전문체육) (사천) 2023년 초등연맹회장기 ...,False,"[국제, 전국, 규모, 스포츠, 대회, 유치, 지원, 전문, 체육, 사천, 2023...",19,사천시,우수,성과평가
12236,대전,본청,"폭력피해이주여성보호시설운영지원(자체, 1개소) -부식비, 피복비등 -종사자특별수당 ...","폭력피해이주여성보호시설운영지원(자체, 1개소) -부식비, 피복비등 -종사자특별수당 ...","폭력피해이주여성보호시설운영지원(자체, 1개소) -부식비, 피복비등 -종사자특별수당 ...",False,"[폭력, 피해, 이주, 여성, 보호, 시설, 운영, 지원, 자체, 1, 부식비, 피...",19,서구,매우우수,성과평가
12258,대전,본청,"한부모가족복지시설지원 -춘계부식비, -월동용김장비, -종사자특별수당, -종사자정액급...","한부모가족복지시설지원 -춘계부식비, -월동용김장비, -종사자특별수당, -종사자정액급...","한부모가족복지시설지원 -춘계부식비, -월동용김장비, -종사자특별수당, -종사자정액급...",False,"[부모, 가족, 복지, 시설, 지원, 춘계, 부식비, 월동, 김장, 비, 종사자, ...",19,"중구, 서구, 대덕구",우수,성과평가
78719,광주,동구,빈집 청년창업 채움 프로젝트 지원(자체)빈집 청년 창업 채움 프로젝트 지원사업 (자...,빈집 청년창업 채움 프로젝트 지원(자체)빈집 청년 창업 채움 프로젝트 지원사업 (자...,빈집 청년창업 채움 프로젝트 지원(자체)빈집 청년 창업 채움 프로젝트 지원사업 (자...,False,"[빈집, 청년, 창업, 프로젝트, 지원, 자, 체, 빈집, 청년, 창업, 프로젝트,...",19,인터미션스튜디오파티룸 외 9,우수,성과평가/유지필요성평가
950,경남,진주시,저소득거동불편 재가노인 식사배달사업 지원 저소득 거동불편 재가노인 식사배달사업 유류...,저소득거동불편 재가노인 식사배달사업 지원 저소득 거동불편 재가노인 식사배달사업 유류...,저소득거동불편 재가노인 식사배달사업 지원 저소득 거동불편 재가노인 식사배달사업 유류...,False,"[소득, 거동, 불편, 재가, 노인, 식사, 배달, 사업, 지원, 소득, 거동, 불...",19,진주재가노인통합 지원센터 외 6개소,미흡,성과평가
12241,대전,본청,"성매매피해자자활지원센터운영지원(자체, 1개소) -종사자특별수당 -종사자정액급식비 -...","성매매피해자자활지원센터운영지원(자체, 1개소) -종사자특별수당 -종사자정액급식비 -...","성매매피해자자활지원센터운영지원(자체, 1개소) -종사자특별수당 -종사자정액급식비 -...",False,"[성매매, 피해자, 자활, 지원, 센터, 운영, 지원, 자체, 1, 종사자, 특별,...",19,중구,미흡,성과평가
7180,경남,김해시,타 지자체 문화예술분야 경연대회 및 국제행사 참가 지원(제19회 평화예술제 전국국악...,타 지자체 문화예술분야 경연대회 및 국제행사 참가 지원(제19회 평화예술제 전국국악...,타 지자체 문화예술분야 경연대회 및 국제행사 참가 지원(제19회 평화예술제 전국국악...,False,"[지자체, 문화, 예술, 분야, 경연, 대회, 국제, 행사, 참가, 지원, 19, ...",18,가야가락예술단,보통,성과평가
808,경남,진주시,지역 문화 진흥 공모사업 (문화예술창작지원(사진진 주 2023 사진축제 (진주 사진...,지역 문화 진흥 공모사업 (문화예술창작지원(사진진 주 2023 사진축제 (진주 사진...,지역 문화 진흥 공모사업 (문화예술창작지원(사진진 주 2023 사진축제 (진주 사진...,False,"[지역, 문화, 진흥, 공모, 사업, 문화, 예술, 창작, 지원, 사진, 진, 주,...",18,사진진주협동조합,보통,성과평가
12108,대전,본청,"아동복지시설운영 -종사자인건비, -기본운영비, -시설운영비, -냉난방비, -종사자특...","아동복지시설운영 -종사자인건비, -기본운영비, -시설운영비, -냉난방비, -종사자특...","아동복지시설운영 -종사자인건비, -기본운영비, -시설운영비, -냉난방비, -종사자특...",False,"[아동, 복지, 시설, 운영, 종사자, 인건비, 기본, 운영비, 시설, 운영비, 냉...",18,5개자치구,매우우수,성과평가
8422,경남,본청,국제 및 전국규모 스포츠대회 유치지원(생활체육) (창녕) 제5회 창녕군수기 전국 남...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (창녕) 제5회 창녕군수기 전국 남...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (창녕) 제5회 창녕군수기 전국 남...,False,"[국제, 전국, 규모, 스포츠, 대회, 유치, 지원, 생활, 체육, 창녕, 5, 창...",18,창녕시,우수,성과평가
12237,대전,본청,"가정폭력피해자보호시설운영지원(자체) -부식비, 피복비등 -종사자특별수당 -종사자정액급식비","가정폭력피해자보호시설운영지원(자체) -부식비, 피복비등 -종사자특별수당 -종사자정액급식비","가정폭력피해자보호시설운영지원(자체) -부식비, 피복비등 -종사자특별수당 -종사자정액급식비",False,"[가정, 폭력, 피해자, 보호, 시설, 운영, 지원, 자, 체, 부식비, 피복, 비...",18,동구,미흡,성과평가
10961,인천,연수구,노인일자리 및 사회활동지원 확대(노인사회활동 지원사업) 시니어항만서포터즈활동 관련 ...,노인일자리 및 사회활동지원 확대(노인사회활동 지원사업) 시니어항만서포터즈활동 관련 ...,노인일자리 및 사회활동지원 확대(노인사회활동 지원사업) 시니어항만서포터즈활동 관련 ...,False,"[노인, 일자리, 사회, 활동, 지원, 확대, 노인, 사회, 활동, 지원, 사업, ...",18,연수구노인인력개발센터,미흡,성과평가
10344,인천,계양구,노인맞춤돌봄서비스 생활지원사 운영비 보조 노인맞춤돌봄서비스 생활지원사 운영비 보조,노인맞춤돌봄서비스 생활지원사 운영비 보조 노인맞춤돌봄서비스 생활지원사 운영비 보조,노인맞춤돌봄서비스 생활지원사 운영비 보조 노인맞춤돌봄서비스 생활지원사 운영비 보조,False,"[노인, 맞춤, 돌봄, 서비스, 생활, 지원, 사, 운영비, 보조, 노인, 맞춤, ...",18,독거노인생활관리사(노인돌봄기본서비스 수행),매우우수,성과평가
59191,경북,영주시,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,False,"[영주, 농산물, 1, 브랜드, 프로젝트, 사업, 프리미엄, 영주, 농산물, PB,...",18,농협경제지주(주)영주시 연합사업단,우수,성과평가
17123,서울,본청,양천자원회수시설 주변영향지역 아파트 관리비 및 주거환경개선사업비 지원 307-02 ...,양천자원회수시설 주변영향지역 아파트 관리비 및 주거환경개선사업비 지원 307-02 ...,양천자원회수시설 주변영향지역 아파트 관리비 및 주거환경개선사업비 지원 307-02 ...,False,"[양천, 자원, 회수, 시설, 주변, 영향, 지역, 아파트, 관리비, 주거, 환경,...",18,목동1단지아파트관리사무소,보통,성과평가
12111,대전,본청,"아동공동생활가정 -냉난방비지원, -아동지원, -종사자인건비부족분지원, 처우개선(종사...","아동공동생활가정 -냉난방비지원, -아동지원, -종사자인건비부족분지원, 처우개선(종사...","아동공동생활가정 -냉난방비지원, -아동지원, -종사자인건비부족분지원, 처우개선(종사...",False,"[아동, 공동생활, 가정, 냉, 난방비, 지원, 아동, 지원, 종사자, 인건비, 부...",18,5개자치구,우수,성과평가
77579,광주,서구,어르 신전 담생 활체 육지 도자 활동 지원 어르신전담생활체육지도자피복비및운동용품,어르 신전 담생 활체 육지 도자 활동 지원 어르신전담생활체육지도자피복비및운동용품,어르 신전 담생 활체 육지 도자 활동 지원 어르신전담생활체육지도자피복비및운동용품,False,"[신전, 담, 생, 활, 체, 육지, 도자, 활동, 지원, 어르신, 전담, 생활, ...",18,서구체육회,보통,성과평가
12099,대전,본청,"지역아동센터 -종사자특별수당, -종사자정액급식비, -종사자명절휴가비, -가족수당(배...","지역아동센터 -종사자특별수당, -종사자정액급식비, -종사자명절휴가비, -가족수당(배...","지역아동센터 -종사자특별수당, -종사자정액급식비, -종사자명절휴가비, -가족수당(배...",False,"[지역, 아동, 센터, 종사자, 특별, 수당, 종사자, 정액, 급식비, 종사자, 명...",18,5개자치구,매우우수,성과평가
59190,경북,영주시,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,영주농산물 1등 브랜드 프로젝트 사업 ―프리미엄 영주농산물 및 PB포장재 지원(보조...,False,"[영주, 농산물, 1, 브랜드, 프로젝트, 사업, 프리미엄, 영주, 농산물, PB,...",18,농협경제지주(주)영주시 연합사업단,우수,성과평가
8421,경남,본청,국제 및 전국규모 스포츠대회 유치지원(생활체육) (양산) 제1회 양산시장배 전국동호...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (양산) 제1회 양산시장배 전국동호...,국제 및 전국규모 스포츠대회 유치지원(생활체육) (양산) 제1회 양산시장배 전국동호...,False,"[국제, 전국, 규모, 스포츠, 대회, 유치, 지원, 생활, 체육, 양산, 1, 양...",18,양산시,우수,성과평가

03-9 완료
다음 단계에서는 tokens_raw 전체 빈도표를 만들고, 불용어 후보를 검토합니다.

03-10. tokens_raw 전체 빈도표 생성 및 불용어 후보 1차 확인
1. 이 단계의 목적

이 단계는 tokens_raw를 전체 행 기준으로 펼쳐서 단어 빈도표를 만드는 단계입니다.

아직 불용어를 제거하지 않습니다.
먼저 어떤 단어가 많이 등장하는지 확인하고, 다음 단계에서 제거할 단어와 보존할 단어를 판단합니다.

특히 아래 항목을 확인합니다.

지원, 사업, 운영 같은 행정 일반어
2023, 1, 13 같은 숫자·연도 토큰
경남, 전남, 서울, 남해 같은 지역명
복지, 문화, 체육, 농업, 교육, 환경, 장애인, 노인, 아동 같은 정책분야 단어
1글자 토큰

In [ ]:
# 03-10. tokens_raw 전체 빈도표 생성 및 불용어 후보 1차 확인

# ------------------------------------------------------------
# 1) tokens_raw를 긴 형태로 펼치기
# ------------------------------------------------------------
# tokens_raw는 각 행마다 리스트 형태입니다.
# 예: ['마늘', '재배', '영농', '지원단', '지원']
#
# explode()를 사용하면 토큰 하나가 한 행이 되는 형태로 바뀝니다.

token_raw_long = (
    df_text[['tokens_raw']]
    .explode('tokens_raw')
    .rename(columns={'tokens_raw': 'token'})
    .dropna()
    .copy()
)

# 혹시 빈 문자열 토큰이 있으면 제거합니다.
token_raw_long['token'] = token_raw_long['token'].astype(str).str.strip()
token_raw_long = token_raw_long[token_raw_long['token'] != '']

print("03-10. tokens_raw 긴 형태 변환 완료")
print("- 원본 df_text 행 수:", len(df_text))
print("- 전체 토큰 수:", len(token_raw_long))
print("- 고유 토큰 수:", token_raw_long['token'].nunique())


# ------------------------------------------------------------
# 2) 전체 원시 토큰 빈도표 생성
# ------------------------------------------------------------

token_freq_raw = (
    token_raw_long['token']
    .value_counts()
    .reset_index()
)

token_freq_raw.columns = ['token', 'freq']

token_freq_raw['ratio_percent'] = (
    token_freq_raw['freq'] / token_freq_raw['freq'].sum() * 100
).round(4)

print("\n[1] tokens_raw 전체 빈도 상위 100개")
display(token_freq_raw.head(100))


# ------------------------------------------------------------
# 3) 1글자 토큰 빈도 확인
# ------------------------------------------------------------
# 1글자 토큰은 의미 있는 경우도 있지만, 형태소 분석 오류나 지역명 분해일 수도 있습니다.
# 예: 동, 구, 군, 회, 장, 비 등

one_char_token_freq = token_freq_raw[
    token_freq_raw['token'].str.len() == 1
].copy()

print("\n[2] 1글자 토큰 빈도 상위 50개")
display(one_char_token_freq.head(50))


# ------------------------------------------------------------
# 4) 숫자 토큰 빈도 확인
# ------------------------------------------------------------
# 연도, 회차, 숫자 등은 정책분야 분석에서는 대체로 제거 후보입니다.
# 다만 제1회, 3·1운동처럼 의미가 있을 수 있으므로 일단 후보로만 봅니다.

number_token_freq = token_freq_raw[
    token_freq_raw['token'].str.fullmatch(r'\d+')
].copy()

print("\n[3] 숫자 토큰 빈도 상위 50개")
display(number_token_freq.head(50))


# ------------------------------------------------------------
# 5) 자주 등장할 가능성이 높은 행정 일반어 후보 확인
# ------------------------------------------------------------
# 이 목록은 확정 불용어가 아닙니다.
# 빈도와 실제 사례를 보고 다음 단계에서 제거 여부를 판단합니다.

admin_general_terms = [
    '지원', '사업', '운영', '추진', '활동', '보조', '관리',
    '개선', '조성', '육성', '활성', '활성화', '행사', '대회',
    '교육', '프로그램', '센터', '시설', '운영비', '인건비',
    '지원사업', '보조금', '공모', '참가', '개최'
]

admin_general_check = token_freq_raw[
    token_freq_raw['token'].isin(admin_general_terms)
].copy()

print("\n[4] 행정 일반어 후보 빈도")
display(admin_general_check)


# ------------------------------------------------------------
# 6) 정책분야 핵심어 후보 확인
# ------------------------------------------------------------
# 이 단어들은 불용어로 제거하면 안 될 가능성이 높습니다.
# 04번 정책분야 분류의 중요한 단서가 될 수 있습니다.

policy_keyword_candidates = [
    '복지', '보건', '의료', '건강',
    '문화', '예술', '체육', '관광',
    '농업', '농촌', '수산', '어업', '축산', '임업',
    '교육', '청소년', '아동', '어린이', '청년',
    '노인', '장애인', '여성', '다문화',
    '환경', '안전', '방범', '재난',
    '일자리', '고용', '창업', '기업', '산업',
    '마을', '공동체', '도시', '주거', '교통'
]

policy_keyword_check = token_freq_raw[
    token_freq_raw['token'].isin(policy_keyword_candidates)
].copy()

print("\n[5] 정책분야 핵심어 후보 빈도")
display(policy_keyword_check)


# ------------------------------------------------------------
# 7) 지역명 후보 1차 확인
# ------------------------------------------------------------
# 전국 데이터에서는 지역명이 상위에 많이 나올 수 있습니다.
# 지역명은 정책분야 단어가 아니므로 제거 후보일 수 있지만,
# 지역 기반 사업명 해석에 필요할 수도 있어 보존/제거 버전 비교가 필요합니다.

region_keyword_candidates = [
    # 광역
    '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
    '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주',
    '서울시', '부산시', '대구시', '인천시', '광주시', '대전시', '울산시',
    '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도',
    '경상북도', '경상남도', '제주도',

    # 일부 샘플에서 이미 보인 지역명
    '남해', '진주', '창원', '김해', '전주', '청주', '부여',
    '안양', '계양', '영주', '속초', '밀양', '양산', '통영',
    '사천', '창녕', '하남', '제천', '연수'
]

region_keyword_check = token_freq_raw[
    token_freq_raw['token'].isin(region_keyword_candidates)
].copy()

print("\n[6] 지역명 후보 빈도")
display(region_keyword_check)


# ------------------------------------------------------------
# 8) 불용어 후보 검토용 표 생성
# ------------------------------------------------------------
# 상위 빈도 토큰을 중심으로, 사람이 제거 여부를 판단할 수 있는 표를 만듭니다.
# 지금은 자동으로 제거하지 않습니다.

candidate_stopword_check = token_freq_raw.head(300).copy()

# 기본 분류 태그를 붙입니다.
# 이 태그는 검토 편의를 위한 초안이며, 확정 판단이 아닙니다.

def classify_candidate_token(token):
    if re.fullmatch(r'\d+', token):
        return '숫자/연도 후보'
    if token in admin_general_terms:
        return '행정 일반어 후보'
    if token in region_keyword_candidates:
        return '지역명 후보'
    if token in policy_keyword_candidates:
        return '정책분야 핵심어 후보'
    if len(token) == 1:
        return '1글자 토큰 후보'
    return '검토필요'

candidate_stopword_check['검토분류_초안'] = candidate_stopword_check['token'].apply(classify_candidate_token)

# 사람이 직접 채울 열
candidate_stopword_check['제거여부'] = ''
candidate_stopword_check['검토메모'] = ''

print("\n[7] 불용어 후보 검토표 상위 100개")
display(candidate_stopword_check.head(100))


# ------------------------------------------------------------
# 9) 결과 저장
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

token_freq_raw_csv = TABLE_DIR / f'03_token_freq_raw_v1_{timestamp}.csv'
candidate_stopword_xlsx = TABLE_DIR / f'03_candidate_stopword_check_v1_{timestamp}.xlsx'
candidate_stopword_csv = TABLE_DIR / f'03_candidate_stopword_check_v1_{timestamp}.csv'

token_freq_raw.to_csv(token_freq_raw_csv, index=False, encoding='utf-8-sig')
candidate_stopword_check.to_excel(candidate_stopword_xlsx, index=False)
candidate_stopword_check.to_csv(candidate_stopword_csv, index=False, encoding='utf-8-sig')

print("\n03-10 저장 완료")
print("- 원시 토큰 빈도표 CSV:", token_freq_raw_csv)
print("- 불용어 후보 검토표 Excel:", candidate_stopword_xlsx)
print("- 불용어 후보 검토표 CSV:", candidate_stopword_csv)

print("\n저장 파일 존재 여부")
print("- token_freq_raw_csv:", token_freq_raw_csv.exists())
print("- candidate_stopword_xlsx:", candidate_stopword_xlsx.exists())
print("- candidate_stopword_csv:", candidate_stopword_csv.exists())


print("\n03-10 완료")
print("다음 단계에서는 상위 빈도 단어와 후보 검토표를 보고 1차 불용어 목록을 만들고, tokens_filtered를 생성합니다.")

03-10. tokens_raw 긴 형태 변환 완료
- 원본 df_text 행 수: 79262
- 전체 토큰 수: 417190
- 고유 토큰 수: 18418

[1] tokens_raw 전체 빈도 상위 100개

   token   freq  ratio_percent
0     지원  35867         8.5973
1     사업  12261         2.9389
2     대회   8704         2.0863
3     운영   7973         1.9111
4    장애인   5392         1.2925
..   ...    ...            ...
95    장비    596         0.1429
96    물품    591         0.1417
97   워크숍    568         0.1361
98    군경    564         0.1352
99    보육    558         0.1338

[100 rows x 3 columns]

[2] 1글자 토큰 빈도 상위 50개

    token  freq  ratio_percent
21      회  1866         0.4473
35      날  1338         0.3207
36      비  1319         0.3162
74      기   739         0.1771
94      도   601         0.1441
104     1   548         0.1314
115     군   491         0.1177
117     쌀   490         0.1175
126     4   461         0.1105
127     동   458         0.1098
131     2   451         0.1081
135     벼   435         0.1043
138     시   425         0.1019
170     리   369         0.0884
184     3   346         0.0829
202     농   319         0.0765
213     지   298         0.0714
218     인   294         0.0705
239     병   276         0.0662
264     배   246         0.0590
278     H   235         0.0563
284     읍   232         0.0556
288     원   229         0.0549
313     장   209         0.0501
320     면   204         0.0489
334     냉   192         0.0460
347     5   185         0.0443
353     선   181         0.0434
359     대   180         0.0431
367     구   174         0.0417
372     집   173         0.0415
383     단   169         0.0405
387     길   167         0.0400
401     6   160         0.0384
418     종   153         0.0367
433     전   147         0.0352
449     밤   144         0.0345
459     차   142         0.0340
480     사   134         0.0321
489     관   131         0.0314
505     홈   126         0.0302
545     산   117         0.0280
553     정   115         0.0276
586     상   109         0.0261
589     급   108         0.0259
591     팀   108         0.0259
606     달   105         0.0252
627     9   102         0.0244
630     료   101         0.0242
643     중    98         0.0235

[3] 숫자 토큰 빈도 상위 50개

     token  freq  ratio_percent
41    2023  1241         0.2975
104      1   548         0.1314
126      4   461         0.1105
131      2   451         0.1081
184      3   346         0.0829
347      5   185         0.0443
401      6   160         0.0384
472     50   138         0.0331
554     10   115         0.0276
583     20   110         0.0264
627      9   102         0.0244
662     12    95         0.0228
664      7    94         0.0225
717     18    85         0.0204
735      8    83         0.0199
750     15    81         0.0194
753     21    80         0.0192
758     13    79         0.0189
778     25    77         0.0185
779     11    77         0.0185
818     14    72         0.0173
822     16    72         0.0173
826     24    71         0.0170
839     19    70         0.0168
864     17    67         0.0161
888     23    66         0.0158
929     22    63         0.0151
988     26    56         0.0134
1135    27    49         0.0117
1204    30    45         0.0108
1292    28    41         0.0098
1309  2024    40         0.0096
1373    31    38         0.0091
1433    33    36         0.0086
1434   100    36         0.0086
1491    43    34         0.0081
1506    35    33         0.0079
1622    29    30         0.0072
1678    32    28         0.0067
1716    34    27         0.0065
1727  2022    27         0.0065
1740    60    27         0.0065
1741    40    27         0.0065
1819   104    25         0.0060
1904    70    23         0.0055
1934    62    23         0.0055
2043    80    21         0.0050
2162    78    19         0.0046
2394   365    16         0.0038
2429    52    16         0.0038

[4] 행정 일반어 후보 빈도

      token   freq  ratio_percent
0        지원  35867         8.5973
1        사업  12261         2.9389
2        대회   8704         2.0863
3        운영   7973         1.9111
6        행사   3885         0.9312
7       운영비   3518         0.8433
8        시설   3395         0.8138
9        센터   2807         0.6728
11       교육   2508         0.6012
16       활동   2324         0.5571
19       개최   1928         0.4621
20       개선   1920         0.4602
22       활성   1807         0.4331
23       참가   1800         0.4315
26       육성   1629         0.3905
32     프로그램   1431         0.3430
40       관리   1244         0.2982
42       조성   1233         0.2955
53      인건비    952         0.2282
60       공모    866         0.2076
66       보조    824         0.1975
106      추진    540         0.1294
217     보조금    295         0.0707
830    지원사업     71         0.0170
17830   활성화      1         0.0002

[5] 정책분야 핵심어 후보 빈도

     token  freq  ratio_percent
4      장애인  5392         1.2925
5       체육  4031         0.9662
10      문화  2728         0.6539
11      교육  2508         0.6012
17      마을  2288         0.5484
18      환경  2051         0.4916
24      복지  1784         0.4276
27      노인  1624         0.3893
28      아동  1588         0.3806
30     청소년  1531         0.3670
34      여성  1374         0.3293
51      농업   963         0.2308
63      예술   840         0.2013
72      안전   783         0.1877
77      청년   697         0.1671
82      농촌   641         0.1536
123    공동체   472         0.1131
130     건강   452         0.1083
133     산업   439         0.1052
149     기업   406         0.0973
153    다문화   397         0.0952
168     관광   371         0.0889
172     도시   364         0.0873
185    어린이   343         0.0822
203     축산   315         0.0755
220     창업   290         0.0695
231     교통   282         0.0676
245    일자리   268         0.0642
374     방범   171         0.0410
389     의료   167         0.0400
436     재난   147         0.0352
590     주거   108         0.0259
767     임업    78         0.0187
835     어업    70         0.0168
1006    수산    55         0.0132
1246    보건    43         0.0103
1537    고용    32         0.0077

[6] 지역명 후보 빈도

     token  freq  ratio_percent
190    경기도   333         0.0798
196     연수   325         0.0779
201     경남   320         0.0767
206     전남   311         0.0745
219     경기   293         0.0702
246     경북   266         0.0638
267    강원도   243         0.0582
283     대전   232         0.0556
295     전북   223         0.0535
321     충북   203         0.0487
339     강원   191         0.0458
361   전라남도   179         0.0429
407     울산   156         0.0374
516     충남   124         0.0297
548     서울   117         0.0280
587     창원   108         0.0259
620     대구   102         0.0244
686   경상북도    90         0.0216
688     광주    90         0.0216
708     진주    87         0.0209
721     김해    85         0.0204
797   충청북도    75         0.0180
851   전라북도    69         0.0165
885     청주    66         0.0158
887     영주    66         0.0158
903     전주    64         0.0153
954   충청남도    61         0.0146
961   경상남도    59         0.0141
995     양산    56         0.0134
1144    인천    48         0.0115
1152    통영    48         0.0115
1332   광주시    39         0.0093
1400    부산    37         0.0089
1412    창녕    36         0.0086
1501    안양    33         0.0079
1531    속초    32         0.0077
1567    하남    31         0.0074
1590    제천    31         0.0074
1619    사천    30         0.0072
1674    남해    28         0.0067
1789   서울시    26         0.0062
2235    세종    18         0.0043
2282    부여    17         0.0041
2628    계양    14         0.0034
2840    제주    12         0.0029
2882    밀양    12         0.0029
3591   대구시     8         0.0019
4987   인천시     4         0.0010
5119   부산시     4         0.0010
5511   제주도     3         0.0007
8926   울산시     1         0.0002

[7] 불용어 후보 검토표 상위 100개

   token   freq  ratio_percent      검토분류_초안 제거여부 검토메모
0     지원  35867         8.5973    행정 일반어 후보
1     사업  12261         2.9389    행정 일반어 후보
2     대회   8704         2.0863    행정 일반어 후보
3     운영   7973         1.9111    행정 일반어 후보
4    장애인   5392         1.2925  정책분야 핵심어 후보
..   ...    ...            ...          ...  ...  ...
95    장비    596         0.1429         검토필요
96    물품    591         0.1417         검토필요
97   워크숍    568         0.1361         검토필요
98    군경    564         0.1352         검토필요
99    보육    558         0.1338         검토필요

[100 rows x 6 columns]

03-10 저장 완료
- 원시 토큰 빈도표 CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_raw_v1_20260526_1752.csv
- 불용어 후보 검토표 Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_candidate_stopword_check_v1_20260526_1752.xlsx
- 불용어 후보 검토표 CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_candidate_stopword_check_v1_20260526_1752.csv

저장 파일 존재 여부
- token_freq_raw_csv: True
- candidate_stopword_xlsx: True
- candidate_stopword_csv: True

03-10 완료
다음 단계에서는 상위 빈도 단어와 후보 검토표를 보고 1차 불용어 목록을 만들고, tokens_filtered를 생성합니다.

03-11. 1차 불용어 적용 및 tokens_filtered 생성
1. 이 단계의 목적

이 단계는 tokens_raw에서 분석에 방해가 될 가능성이 큰 토큰을 1차로 제거하여, 두 가지 필터링 토큰 열을 만드는 단계입니다.

이번에는 두 버전을 동시에 만듭니다.

| 열 이름                          | 의미                                 |
| ----------------------------- | ---------------------------------- |
| `tokens_filtered_keep_region` | 숫자·행정 일반어·일부 1글자 잡음은 제거하되, 지역명은 보존 |
| `tokens_filtered_no_region`   | 위 기준에 더해 지역명 후보까지 제거               |


지역명을 바로 완전히 제거하지 않고 두 버전을 만드는 이유는, 이후 빈도 분석과 06A 네트워크 분석에서 지역명이 결과를 얼마나 좌우하는지 비교하기 위해서입니다.

In [ ]:
# 03-11. 1차 불용어 적용 및 tokens_filtered 생성

# ------------------------------------------------------------
# 1) 1차 기본 불용어 목록 설정
# ------------------------------------------------------------
# 주의:
# 이 목록은 확정 불용어가 아니라 1차 분석용 초안입니다.
# 정책분야를 구분하는 단어는 최대한 보존합니다.
#
# 예를 들어 '교육', '복지', '문화', '체육', '농업', '환경',
# '장애인', '노인', '아동', '청소년' 등은 제거하지 않습니다.

basic_stopwords = {
    # 매우 일반적인 행정·보조사업 표현
    '지원', '사업', '운영', '보조', '추진',
    '지원사업', '보조금',

    # 비용·운영 관련 일반 표현
    '운영비', '인건비',

    # 행정 처리·절차 성격이 강한 표현
    '관리', '개최', '참가'
}

# ------------------------------------------------------------
# 2) 1글자 잡음 후보 설정
# ------------------------------------------------------------
# 모든 1글자 토큰을 제거하지는 않습니다.
# '쌀', '벼', '집', '길'처럼 의미가 있는 1글자 단어도 있기 때문입니다.
# 여기서는 빈도표에서 잡음 가능성이 높은 1글자만 보수적으로 제거합니다.

one_char_stopwords = {
    '회', '기', '도', '군', '동', '시', '리', '지', '인',
    '원', '장', '면', '대', '구', '단', '종', '전', '사',
    '관', '정', '상', '급', '료', '중'
}

# 보존할 정책분야 핵심어
# 혹시 basic_stopwords나 one_char_stopwords에 들어가더라도 이 목록은 최종 제거하지 않도록 보호합니다.
policy_preserve_terms = {
    '장애인', '체육', '문화', '교육', '마을', '환경', '복지',
    '노인', '아동', '청소년', '여성', '농업', '예술', '안전',
    '청년', '농촌', '공동체', '건강', '산업', '기업', '다문화',
    '관광', '도시', '어린이', '축산', '창업', '교통', '일자리',
    '방범', '의료', '재난', '주거', '임업', '어업', '수산', '보건',
    '고용'
}

# 보호 목록에 있는 단어는 불용어에서 제거
basic_stopwords = basic_stopwords - policy_preserve_terms
one_char_stopwords = one_char_stopwords - policy_preserve_terms


# ------------------------------------------------------------
# 3) 지역명 후보 목록 설정
# ------------------------------------------------------------
# 03-10에서 region_keyword_candidates 변수가 있으면 그대로 사용합니다.
# 없을 경우를 대비해 기본 목록을 다시 정의합니다.

try:
    region_keyword_candidates
except NameError:
    region_keyword_candidates = [
        '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
        '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주',
        '서울시', '부산시', '대구시', '인천시', '광주시', '대전시', '울산시',
        '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도',
        '경상북도', '경상남도', '제주도',
        '남해', '진주', '창원', '김해', '전주', '청주', '부여',
        '안양', '계양', '영주', '속초', '밀양', '양산', '통영',
        '사천', '창녕', '하남', '제천', '연수'
    ]

region_stopwords = set(region_keyword_candidates)

# 정책분야 핵심어와 겹치면 제거하지 않도록 보호
region_stopwords = region_stopwords - policy_preserve_terms


# ------------------------------------------------------------
# 4) 토큰 필터링 함수 정의
# ------------------------------------------------------------

def is_number_token(token):
    """숫자 토큰인지 확인합니다."""
    return bool(re.fullmatch(r'\d+', str(token)))


def filter_tokens(tokens, remove_region=False):
    """
    tokens_raw에서 1차 불용어를 제거합니다.

    remove_region=False:
    - 지역명은 보존합니다.

    remove_region=True:
    - 지역명 후보까지 제거합니다.
    """

    if not isinstance(tokens, list):
        return []

    filtered = []

    for token in tokens:
        token = str(token).strip()

        if token == '':
            continue

        # 숫자 토큰 제거
        if is_number_token(token):
            continue

        # 기본 불용어 제거
        if token in basic_stopwords:
            continue

        # 1글자 잡음 후보 제거
        if token in one_char_stopwords:
            continue

        # 지역명 제거 버전일 때만 지역명 제거
        if remove_region and token in region_stopwords:
            continue

        filtered.append(token)

    return filtered


# ------------------------------------------------------------
# 5) 두 가지 tokens_filtered 열 생성
# ------------------------------------------------------------

df_text['tokens_filtered_keep_region'] = df_text['tokens_raw'].apply(
    lambda tokens: filter_tokens(tokens, remove_region=False)
)

df_text['tokens_filtered_no_region'] = df_text['tokens_raw'].apply(
    lambda tokens: filter_tokens(tokens, remove_region=True)
)

df_text['tokens_filtered_keep_region_count'] = df_text['tokens_filtered_keep_region'].apply(len)
df_text['tokens_filtered_no_region_count'] = df_text['tokens_filtered_no_region'].apply(len)

df_text['tokens_filtered_keep_region_empty'] = df_text['tokens_filtered_keep_region_count'].eq(0)
df_text['tokens_filtered_no_region_empty'] = df_text['tokens_filtered_no_region_count'].eq(0)


# ------------------------------------------------------------
# 6) 필터링 결과 요약
# ------------------------------------------------------------

filter_summary = pd.DataFrame({
    '항목': [
        '분석 대상 행 수',
        'tokens_raw 전체 토큰 수',
        '지역명 보존 버전 전체 토큰 수',
        '지역명 제거 버전 전체 토큰 수',
        '지역명 보존 버전 빈 행 수',
        '지역명 제거 버전 빈 행 수',
        '지역명 보존 버전 평균 토큰 수',
        '지역명 제거 버전 평균 토큰 수'
    ],
    '값': [
        len(df_text),
        int(df_text['tokens_raw_count'].sum()),
        int(df_text['tokens_filtered_keep_region_count'].sum()),
        int(df_text['tokens_filtered_no_region_count'].sum()),
        int(df_text['tokens_filtered_keep_region_empty'].sum()),
        int(df_text['tokens_filtered_no_region_empty'].sum()),
        round(df_text['tokens_filtered_keep_region_count'].mean(), 3),
        round(df_text['tokens_filtered_no_region_count'].mean(), 3)
    ]
})

print("03-11. 1차 불용어 적용 및 tokens_filtered 생성 완료")
display(filter_summary)


# ------------------------------------------------------------
# 7) 필터링 전후 샘플 확인
# ------------------------------------------------------------

sample_cols = [
    '시도', '지자체명',
    '사업명',
    '사업명_clean_spacefix',
    'tokens_raw',
    'tokens_filtered_keep_region',
    'tokens_filtered_no_region',
    'tokens_raw_count',
    'tokens_filtered_keep_region_count',
    'tokens_filtered_no_region_count',
    '평가결과',
    '평가종류'
]

existing_sample_cols = [col for col in sample_cols if col in df_text.columns]

print("\n[1] 필터링 전후 샘플 30개")
display(df_text[existing_sample_cols].head(30))


# ------------------------------------------------------------
# 8) 필터링 후 빈 토큰 행 확인
# ------------------------------------------------------------

print("\n[2] 지역명 보존 버전에서 빈 토큰이 된 행")
display(
    df_text.loc[
        df_text['tokens_filtered_keep_region_empty'],
        existing_sample_cols
    ].head(30)
)

print("\n[3] 지역명 제거 버전에서 빈 토큰이 된 행")
display(
    df_text.loc[
        df_text['tokens_filtered_no_region_empty'],
        existing_sample_cols
    ].head(30)
)


# ------------------------------------------------------------
# 9) 필터링 버전별 빈도표 생성 함수
# ------------------------------------------------------------

def make_token_freq(df, token_col):
    """리스트 형태 토큰 열을 펼쳐 빈도표를 생성합니다."""

    token_long = (
        df[[token_col]]
        .explode(token_col)
        .rename(columns={token_col: 'token'})
        .dropna()
        .copy()
    )

    token_long['token'] = token_long['token'].astype(str).str.strip()
    token_long = token_long[token_long['token'] != '']

    token_freq = (
        token_long['token']
        .value_counts()
        .reset_index()
    )

    token_freq.columns = ['token', 'freq']
    token_freq['ratio_percent'] = (
        token_freq['freq'] / token_freq['freq'].sum() * 100
    ).round(4)

    return token_freq


token_freq_keep_region = make_token_freq(df_text, 'tokens_filtered_keep_region')
token_freq_no_region = make_token_freq(df_text, 'tokens_filtered_no_region')


print("\n[4] 지역명 보존 버전 빈도 상위 100개")
display(token_freq_keep_region.head(100))

print("\n[5] 지역명 제거 버전 빈도 상위 100개")
display(token_freq_no_region.head(100))


# ------------------------------------------------------------
# 10) 지역명 제거 전후 차이 확인
# ------------------------------------------------------------

region_removed_check = token_freq_keep_region[
    token_freq_keep_region['token'].isin(region_stopwords)
].copy()

print("\n[6] 지역명 보존 버전에 남아 있는 지역명 후보")
display(region_removed_check.head(100))


# ------------------------------------------------------------
# 11) 결과 저장
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

token_freq_keep_region_csv = TABLE_DIR / f'03_token_freq_filtered_keep_region_v1_{timestamp}.csv'
token_freq_no_region_csv = TABLE_DIR / f'03_token_freq_filtered_no_region_v1_{timestamp}.csv'

filter_summary_csv = TABLE_DIR / f'03_token_filter_summary_v1_{timestamp}.csv'

token_freq_keep_region.to_csv(token_freq_keep_region_csv, index=False, encoding='utf-8-sig')
token_freq_no_region.to_csv(token_freq_no_region_csv, index=False, encoding='utf-8-sig')
filter_summary.to_csv(filter_summary_csv, index=False, encoding='utf-8-sig')

print("\n03-11 저장 완료")
print("- 지역명 보존 빈도표:", token_freq_keep_region_csv)
print("- 지역명 제거 빈도표:", token_freq_no_region_csv)
print("- 필터링 요약표:", filter_summary_csv)

print("\n저장 파일 존재 여부")
print("- token_freq_keep_region_csv:", token_freq_keep_region_csv.exists())
print("- token_freq_no_region_csv:", token_freq_no_region_csv.exists())
print("- filter_summary_csv:", filter_summary_csv.exists())

print("\n03-11 완료")
print("다음 단계에서는 두 빈도표를 비교하고, 불용어 목록을 조정할지 판단합니다.")

03-11. 1차 불용어 적용 및 tokens_filtered 생성 완료

                   항목           값
0           분석 대상 행 수   79262.000
1  tokens_raw 전체 토큰 수  417190.000
2   지역명 보존 버전 전체 토큰 수  335859.000
3   지역명 제거 버전 전체 토큰 수  330753.000
4     지역명 보존 버전 빈 행 수      54.000
5     지역명 제거 버전 빈 행 수      63.000
6   지역명 보존 버전 평균 토큰 수       4.237
7   지역명 제거 버전 평균 토큰 수       4.173

[1] 필터링 전후 샘플 30개

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_filtered_keep_region,tokens_filtered_no_region,tokens_raw_count,tokens_filtered_keep_region_count,tokens_filtered_no_region_count,평가결과,평가종류
0,경남,남해군,마늘재배 영농지원단 지원,마늘재배 영농지원단 지원,"[마늘, 재배, 영농, 지원단, 지원]","[마늘, 재배, 영농, 지원단]","[마늘, 재배, 영농, 지원단]",5,4,4,매우우수,유지필요성평가
1,경남,남해군,2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영,2023년 사)진주지역범죄피해자지원센터'등불 '남해지부 운영,"[2023, 진주, 지역, 범죄, 피해자, 지원, 센터, 등불, 남해, 지부, 운영]","[진주, 지역, 범죄, 피해자, 센터, 등불, 남해, 지부]","[지역, 범죄, 피해자, 센터, 등불, 지부]",11,8,6,미흡,유지필요성평가
2,경남,남해군,자유민주주의신장 및 자유선진의식 고취,자유민주주의신장 및 자유선진의식 고취,"[자유, 민주주의, 신장, 자유선진, 의식, 고취]","[자유, 민주주의, 신장, 자유선진, 의식, 고취]","[자유, 민주주의, 신장, 자유선진, 의식, 고취]",6,6,6,미흡,유지필요성평가
3,경남,남해군,보물섬 독서학교 지원,보물섬 독서학교 지원,"[보물섬, 독서, 학교, 지원]","[보물섬, 독서, 학교]","[보물섬, 독서, 학교]",4,3,3,미흡,유지필요성평가
4,경남,남해군,참전경찰유공자 보훈활동,참전경찰유공자 보훈활동,"[참전, 경찰, 유공자, 보훈, 활동]","[참전, 경찰, 유공자, 보훈, 활동]","[참전, 경찰, 유공자, 보훈, 활동]",5,5,5,미흡,유지필요성평가
5,경남,남해군,무공수훈자회 운영비 보조,무공수훈자회 운영비 보조,"[무공, 수훈자, 회, 운영비, 보조]","[무공, 수훈자]","[무공, 수훈자]",5,2,2,미흡,유지필요성평가
6,경남,남해군,행복나눔센터 운영,행복나눔센터 운영,"[행복, 센터, 운영]","[행복, 센터]","[행복, 센터]",3,2,2,미흡,유지필요성평가
7,경남,남해군,경로당 양곡구입비 지원,경로당 양곡구입비 지원,"[경로당, 양곡, 구입비, 지원]","[경로당, 양곡, 구입비]","[경로당, 양곡, 구입비]",4,3,3,미흡,유지필요성평가
8,경남,남해군,장애인직업재활 자활교육,장애인직업재활 자활교육,"[장애인, 직업, 재활, 자활, 교육]","[장애인, 직업, 재활, 자활, 교육]","[장애인, 직업, 재활, 자활, 교육]",5,5,5,미흡,유지필요성평가
9,경남,남해군,어린이집 운전기사 인건비 (미조지역영유아수송),어린이집 운전기사 인건비 (미조지역영유아수송),"[어린이집, 운전기사, 인건비, 미조, 지역, 영유아, 수송]","[어린이집, 운전기사, 미조, 지역, 영유아, 수송]","[어린이집, 운전기사, 미조, 지역, 영유아, 수송]",7,6,6,미흡,유지필요성평가
10,경남,남해군,아동 일일나들이 행사,아동 일일나들이 행사,"[아동, 일일, 나들이, 행사]","[아동, 일일, 나들이, 행사]","[아동, 일일, 나들이, 행사]",4,4,4,미흡,유지필요성평가
11,경남,남해군,문화학교 운영,문화학교 운영,"[문화, 학교, 운영]","[문화, 학교]","[문화, 학교]",3,2,2,미흡,유지필요성평가
12,경남,남해군,남중권생활체육 교류 지원,남중권생활체육 교류 지원,"[남, 생활, 체육, 교류, 지원]","[남, 생활, 체육, 교류]","[남, 생활, 체육, 교류]",5,4,4,미흡,유지필요성평가
13,경남,남해군,"전국대회 운영(구급차, 응급의료 등) 지원","전국대회 운영(구급차, 응급의료 등) 지원","[전국, 대회, 운영, 구급차, 응급, 의료, 지원]","[전국, 대회, 구급차, 응급, 의료]","[전국, 대회, 구급차, 응급, 의료]",7,5,5,미흡,유지필요성평가
14,경남,남해군,레포츠 자격증 취득 지원,레포츠 자격증 취득 지원,"[레포츠, 자격증, 취득, 지원]","[레포츠, 자격증, 취득]","[레포츠, 자격증, 취득]",4,3,3,미흡,유지필요성평가
15,경남,남해군,수산물 상생할인 지원사업,수산물 상생할인 지원사업,"[수산물, 상생, 할인, 지원, 사업]","[수산물, 상생, 할인]","[수산물, 상생, 할인]",5,3,3,미흡,유지필요성평가
16,경남,남해군,마을어장 개발,마을어장 개발,"[마을, 어장, 개발]","[마을, 어장, 개발]","[마을, 어장, 개발]",3,3,3,미흡,유지필요성평가
17,경남,남해군,자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),"[자연, 환경, 보전, 활동, 사업, 자연보호, 정화, 활동, 군, 수기, 경진, 대회]","[자연, 환경, 보전, 활동, 자연보호, 정화, 활동, 수기, 경진, 대회]","[자연, 환경, 보전, 활동, 자연보호, 정화, 활동, 수기, 경진, 대회]",12,10,10,미흡,유지필요성평가
18,경남,남해군,2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),"[2023, 음식점, 위생, 환경, 개선, 사업, 시설, 환경, 개선, 입식, 테이...","[음식점, 위생, 환경, 개선, 시설, 환경, 개선, 입식, 테이블]","[음식점, 위생, 환경, 개선, 시설, 환경, 개선, 입식, 테이블]",12,9,9,미흡,유지필요성평가
19,경남,남해군,농촌신활력 플러스사업 (추진단사무국상근직원인건비),농촌신활력 플러스사업 (추진단사무국상근직원인건비),"[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원, 인건비]","[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원]","[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원]",7,6,6,미흡,유지필요성평가
20,경남,남해군,GAP 인증농산물 포장재 지원사업,GAP 인증농산물 포장재 지원사업,"[GAP, 인증, 농산물, 포장재, 지원, 사업]","[GAP, 인증, 농산물, 포장재]","[GAP, 인증, 농산물, 포장재]",6,4,4,미흡,유지필요성평가
21,경남,남해군,2023년 범죄피해자 지원 및 지원센터‘등불’운영,2023년 범죄피해자 지원 및 지원센터'등불'운영,"[2023, 범죄, 피해자, 지원, 지원, 센터, 등불, 운영]","[범죄, 피해자, 센터, 등불]","[범죄, 피해자, 센터, 등불]",8,4,4,보통,유지필요성평가
22,경남,남해군,2023년 보물섬 남해포럼 운영,2023년 보물섬 남해포럼 운영,"[2023, 보물섬, 남해, 포럼, 운영]","[보물섬, 남해, 포럼]","[보물섬, 포럼]",5,3,2,보통,유지필요성평가
23,경남,남해군,전입세대 빈집수리 지원,전입세대 빈집수리 지원,"[전입, 세대, 빈집, 수리, 지원]","[전입, 세대, 빈집, 수리]","[전입, 세대, 빈집, 수리]",5,4,4,보통,유지필요성평가
24,경남,남해군,제13회 새마을의 날 기념식,제13회 새마을의 날 기념식,"[13, 마을, 날, 기념식]","[마을, 날, 기념식]","[마을, 날, 기념식]",4,3,3,보통,유지필요성평가
25,경남,남해군,2023년 남해군 새마을지도자 대회,2023년 남해군 새마을지도자 대회,"[2023, 남해군, 마을, 지도자, 대회]","[남해군, 마을, 지도자, 대회]","[남해군, 마을, 지도자, 대회]",5,4,4,보통,유지필요성평가
26,경남,남해군,새마을지도자 화합한마음대회,새마을지도자 화합한마음대회,"[새마을, 지도자, 화합, 마음, 대회]","[새마을, 지도자, 화합, 마음, 대회]","[새마을, 지도자, 화합, 마음, 대회]",5,5,5,보통,유지필요성평가
27,경남,남해군,국민의식개혁 및 기초질서확립운동,국민의식개혁 및 기초질서확립운동,"[국민, 의식, 개혁, 기초, 질서, 확립, 운동]","[국민, 의식, 개혁, 기초, 질서, 확립, 운동]","[국민, 의식, 개혁, 기초, 질서, 확립, 운동]",7,7,7,보통,유지필요성평가
28,경남,남해군,방범활동 및 남해바다 수중정화활동,방범활동 및 남해바다 수중정화활동,"[방범, 활동, 남해, 바다, 수중, 정화, 활동]","[방범, 활동, 남해, 바다, 수중, 정화, 활동]","[방범, 활동, 바다, 수중, 정화, 활동]",7,7,6,보통,유지필요성평가
29,경남,남해군,바르게살기운동남해군협의회 운영비 지원,바르게살기운동남해군협의회 운영비 지원,"[운동, 남, 해군, 협의회, 운영비, 지원]","[운동, 남, 해군, 협의회]","[운동, 남, 해군, 협의회]",6,4,4,보통,유지필요성평가

[2] 지역명 보존 버전에서 빈 토큰이 된 행

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_filtered_keep_region,tokens_filtered_no_region,tokens_raw_count,tokens_filtered_keep_region_count,tokens_filtered_no_region_count,평가결과,평가종류
1632,경남,양산시,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
1841,경남,창원시,열아홉을 위하여,열아홉을 위하여,[],[],[],0,0,0,미흡,유지필요성평가
9374,경남,본청,다함께 해 봄,다함께 해 봄,[],[],[],0,0,0,보통,성과평가
9387,경남,본청,왔노라 보았노라 통했노라,왔노라 보았노라 통했노라,[],[],[],0,0,0,보통,성과평가
11159,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,매우우수,유지필요성평가
11174,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,보통,유지필요성평가
11215,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,매우우수,유지필요성평가
15393,서울,종로구,인건비 및 운영비,인건비 및 운영비,"[인건비, 운영비]",[],[],2,0,0,미흡,성과평가
15403,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15404,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15418,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15424,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15425,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15426,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15427,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15428,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15429,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15430,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22348,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22353,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22360,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22364,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22417,울산,동구,함께 나누며 느껴요,함께 나누며 느껴요,[],[],[],0,0,0,매우우수,성과평가
22421,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
22425,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
22429,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,매우우수,성과평가
22433,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
22437,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
22442,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
22447,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,매우우수,성과평가

[3] 지역명 제거 버전에서 빈 토큰이 된 행

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_filtered_keep_region,tokens_filtered_no_region,tokens_raw_count,tokens_filtered_keep_region_count,tokens_filtered_no_region_count,평가결과,평가종류
1632,경남,양산시,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
1841,경남,창원시,열아홉을 위하여,열아홉을 위하여,[],[],[],0,0,0,미흡,유지필요성평가
7472,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,보통,성과평가
7473,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,우수,성과평가
7474,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,보통,성과평가
7475,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,우수,성과평가
7476,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,매우우수,성과평가
7477,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,보통,성과평가
9172,경남,본청,경남을 찾아서 展 지원,경남을 찾아서 展 지원,"[경남, 지원]",[경남],[],2,1,0,보통,성과평가
9374,경남,본청,다함께 해 봄,다함께 해 봄,[],[],[],0,0,0,보통,성과평가
9387,경남,본청,왔노라 보았노라 통했노라,왔노라 보았노라 통했노라,[],[],[],0,0,0,보통,성과평가
11159,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,매우우수,유지필요성평가
11174,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,보통,유지필요성평가
11215,대전,동구,운영지원,운영지원,"[운영, 지원]",[],[],2,0,0,매우우수,유지필요성평가
11778,대전,본청,대전십무,대전십무,[대전],[대전],[],1,1,0,보통,유지필요성평가
15393,서울,종로구,인건비 및 운영비,인건비 및 운영비,"[인건비, 운영비]",[],[],2,0,0,미흡,성과평가
15403,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15404,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15418,서울,종로구,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,매우우수,성과평가
15424,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15425,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15426,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15427,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15428,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15429,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
15430,서울,종로구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22348,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22353,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22360,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가
22364,울산,동구,운영비,운영비,[운영비],[],[],1,0,0,보통,성과평가

[4] 지역명 보존 버전 빈도 상위 100개

   token  freq  ratio_percent
0     대회  8704         2.5916
1    장애인  5392         1.6054
2     체육  4031         1.2002
3     행사  3885         1.1567
4     시설  3395         1.0108
..   ...   ...            ...
95   어르신   517         0.1539
96    참여   511         0.1521
97    추가   510         0.1518
98    가정   509         0.1516
99    품질   492         0.1465

[100 rows x 3 columns]

[5] 지역명 제거 버전 빈도 상위 100개

   token  freq  ratio_percent
0     대회  8704         2.6316
1    장애인  5392         1.6302
2     체육  4031         1.2187
3     행사  3885         1.1746
4     시설  3395         1.0264
..   ...   ...            ...
95   어르신   517         0.1563
96    참여   511         0.1545
97    추가   510         0.1542
98    가정   509         0.1539
99    품질   492         0.1488

[100 rows x 3 columns]

[6] 지역명 보존 버전에 남아 있는 지역명 후보

     token  freq  ratio_percent
168    경기도   333         0.0991
173     연수   325         0.0968
178     경남   320         0.0953
183     전남   311         0.0926
194     경기   293         0.0872
221     경북   266         0.0792
242    강원도   243         0.0724
258     대전   232         0.0691
268     전북   223         0.0664
294     충북   203         0.0604
311     강원   191         0.0569
331   전라남도   179         0.0533
374     울산   156         0.0464
478     충남   124         0.0369
510     서울   117         0.0348
547     창원   108         0.0322
579     대구   102         0.0304
637     광주    90         0.0268
643   경상북도    90         0.0268
656     진주    87         0.0259
670     김해    85         0.0253
739   충청북도    75         0.0223
791   전라북도    69         0.0205
814     청주    66         0.0197
825     영주    66         0.0197
845     전주    64         0.0191
883   충청남도    61         0.0182
899   경상남도    59         0.0176
924     양산    56         0.0167
1076    인천    48         0.0143
1079    통영    48         0.0143
1276   광주시    39         0.0116
1324    부산    37         0.0110
1351    창녕    36         0.0107
1434    안양    33         0.0098
1466    속초    32         0.0095
1498    제천    31         0.0092
1513    하남    31         0.0092
1558    사천    30         0.0089
1600    남해    28         0.0083
1698   서울시    26         0.0077
2125    세종    18         0.0054
2209    부여    17         0.0051
2461    계양    14         0.0042
2733    제주    12         0.0036
2773    밀양    12         0.0036
3355   대구시     8         0.0024
4738   인천시     4         0.0012
5007   부산시     4         0.0012
5908   제주도     3         0.0009
8735   울산시     1         0.0003

03-11 저장 완료
- 지역명 보존 빈도표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_filtered_keep_region_v1_20260526_1828.csv
- 지역명 제거 빈도표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_filtered_no_region_v1_20260526_1828.csv
- 필터링 요약표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_filter_summary_v1_20260526_1828.csv

저장 파일 존재 여부
- token_freq_keep_region_csv: True
- token_freq_no_region_csv: True
- filter_summary_csv: True

03-11 완료
다음 단계에서는 두 빈도표를 비교하고, 불용어 목록을 조정할지 판단합니다.

03-12. 필터링 결과 비교 및 불용어 조정 후보 점검
1. 이 단계의 목적

이 단계는 03-11에서 만든 두 가지 토큰 버전을 비교하는 단계입니다.

비교 대상은 다음입니다.

열	의미
tokens_filtered_keep_region	지역명 보존 버전
tokens_filtered_no_region	지역명 제거 버전

이번 단계에서는 아직 불용어 목록을 수정하지 않습니다.
대신 다음을 확인합니다.

지역명 제거 전후 상위 단어 차이
아직 많이 남아 있는 행정 일반어 후보
정책분야 핵심어가 잘 보존됐는지
빈 토큰 행이 어떤 유형인지
추가 불용어 후보를 만들 필요가 있는지

In [ ]:
# 03-12. 필터링 결과 비교 및 불용어 조정 후보 점검

# ------------------------------------------------------------
# 1) 지역명 보존/제거 버전 빈도 비교표 생성
# ------------------------------------------------------------

freq_compare = token_freq_keep_region.rename(
    columns={
        'freq': 'freq_keep_region',
        'ratio_percent': 'ratio_keep_region'
    }
).merge(
    token_freq_no_region.rename(
        columns={
            'freq': 'freq_no_region',
            'ratio_percent': 'ratio_no_region'
        }
    ),
    on='token',
    how='outer'
)

# 결측은 0으로 채웁니다.
freq_compare[['freq_keep_region', 'ratio_keep_region', 'freq_no_region', 'ratio_no_region']] = (
    freq_compare[['freq_keep_region', 'ratio_keep_region', 'freq_no_region', 'ratio_no_region']]
    .fillna(0)
)

# 빈도 차이 계산
freq_compare['freq_diff_keep_minus_no'] = (
    freq_compare['freq_keep_region'] - freq_compare['freq_no_region']
)

freq_compare['ratio_diff_keep_minus_no'] = (
    freq_compare['ratio_keep_region'] - freq_compare['ratio_no_region']
).round(4)

# 보기 편하게 정렬
freq_compare = freq_compare.sort_values(
    ['freq_keep_region', 'freq_no_region'],
    ascending=False
).reset_index(drop=True)

print("03-12. 필터링 결과 비교")
print("\n[1] 지역명 보존/제거 버전 빈도 비교 상위 100개")
display(freq_compare.head(100))


# ------------------------------------------------------------
# 2) 지역명 제거로 실제 사라진 토큰 확인
# ------------------------------------------------------------
# keep_region에는 있는데 no_region에서는 0인 토큰을 확인합니다.
# 대부분 지역명 후보여야 정상입니다.

removed_by_region_filter = freq_compare[
    (freq_compare['freq_keep_region'] > 0) &
    (freq_compare['freq_no_region'] == 0)
].copy()

print("\n[2] 지역명 제거 버전에서 사라진 토큰 상위 100개")
display(removed_by_region_filter.head(100))


# ------------------------------------------------------------
# 3) 아직 남아 있는 행정 일반어 후보 확인
# ------------------------------------------------------------
# 03-11에서 일부러 보존한 단어들 중,
# 너무 상위에 남아 있는 단어를 검토합니다.
#
# 주의:
# 여기서 나온다고 바로 제거하지 않습니다.
# '교육', '시설', '센터', '대회', '행사'는 정책분야/사업유형 해석에 필요할 수 있습니다.

remaining_admin_terms = [
    '대회', '행사', '시설', '센터', '활동',
    '개선', '조성', '육성', '프로그램',
    '공모', '개발', '교류', '기념', '홍보',
    '보급', '구입', '제작', '정비', '설치',
    '상담', '서비스', '강화', '증진', '확대',
    '참여', '추가'
]

remaining_admin_check = token_freq_no_region[
    token_freq_no_region['token'].isin(remaining_admin_terms)
].copy()

print("\n[3] 지역명 제거 버전에 아직 남아 있는 행정/사업유형 후보")
display(remaining_admin_check)


# ------------------------------------------------------------
# 4) 정책분야 핵심어 보존 여부 확인
# ------------------------------------------------------------
# 정책분야 분류에 중요한 단어들이 필터링 후에도 살아 있는지 확인합니다.

policy_core_terms = [
    '장애인', '체육', '문화', '교육', '마을', '환경', '복지',
    '노인', '아동', '청소년', '여성', '농업', '예술', '안전',
    '청년', '농촌', '공동체', '건강', '산업', '기업', '다문화',
    '관광', '도시', '어린이', '축산', '창업', '교통', '일자리',
    '방범', '의료', '재난', '주거', '임업', '어업', '수산', '보건',
    '고용'
]

preserved_policy_check = token_freq_no_region[
    token_freq_no_region['token'].isin(policy_core_terms)
].copy()

print("\n[4] 정책분야 핵심어 보존 확인")
display(preserved_policy_check)


# ------------------------------------------------------------
# 5) 필터링 후 빈 토큰 행 검토
# ------------------------------------------------------------
# 빈 토큰 행이 많지 않은지, 어떤 유형인지 확인합니다.

empty_token_review_cols = [
    '시도', '지자체명',
    '사업명',
    '사업명_clean_spacefix',
    'tokens_raw',
    'tokens_filtered_keep_region',
    'tokens_filtered_no_region',
    'tokens_raw_count',
    'tokens_filtered_keep_region_count',
    'tokens_filtered_no_region_count',
    '평가결과',
    '평가종류'
]

existing_empty_token_review_cols = [
    col for col in empty_token_review_cols
    if col in df_text.columns
]

empty_token_review = df_text.loc[
    df_text['tokens_filtered_no_region_empty'],
    existing_empty_token_review_cols
].copy()

print("\n[5] 지역명 제거 버전 빈 토큰 행 검토")
print("- 지역명 제거 버전 빈 토큰 행 수:", len(empty_token_review))
display(empty_token_review.head(100))


# ------------------------------------------------------------
# 6) 추가 불용어 후보표 생성
# ------------------------------------------------------------
# 상위 빈도 중 아직 검토가 필요한 단어를 모아둡니다.
# 여기서는 후보만 만들고, 실제 제거는 다음 셀에서 결정합니다.

additional_stopword_candidates = token_freq_no_region.head(200).copy()

def classify_additional_stopword_candidate(token):
    if token in policy_core_terms:
        return '정책분야 핵심어_보존권장'
    if token in remaining_admin_terms:
        return '행정/사업유형 후보_검토필요'
    if len(str(token)) == 1:
        return '1글자 토큰_검토필요'
    return '검토필요'

additional_stopword_candidates['검토분류_초안'] = additional_stopword_candidates['token'].apply(
    classify_additional_stopword_candidate
)

additional_stopword_candidates['추가제거여부'] = ''
additional_stopword_candidates['검토메모'] = ''

print("\n[6] 추가 불용어 후보 검토표 상위 100개")
display(additional_stopword_candidates.head(100))


# ------------------------------------------------------------
# 7) 결과 저장
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

filter_compare_xlsx = TABLE_DIR / f'03_filter_compare_v1_{timestamp}.xlsx'

with pd.ExcelWriter(filter_compare_xlsx, engine='openpyxl') as writer:
    freq_compare.to_excel(writer, sheet_name='freq_compare', index=False)
    removed_by_region_filter.to_excel(writer, sheet_name='removed_by_region', index=False)
    remaining_admin_check.to_excel(writer, sheet_name='remaining_admin', index=False)
    preserved_policy_check.to_excel(writer, sheet_name='policy_core_check', index=False)
    empty_token_review.to_excel(writer, sheet_name='empty_token_review', index=False)
    additional_stopword_candidates.to_excel(writer, sheet_name='additional_candidates', index=False)

print("\n03-12 저장 완료")
print("- 필터링 비교 Excel:", filter_compare_xlsx)
print("- 저장 파일 존재 여부:", filter_compare_xlsx.exists())

print("\n03-12 완료")
print("다음 단계에서는 추가 불용어를 실제로 적용할지 판단합니다.")

03-12. 필터링 결과 비교

[1] 지역명 보존/제거 버전 빈도 비교 상위 100개

,token,freq_keep_region,ratio_keep_region,freq_no_region,ratio_no_region,freq_diff_keep_minus_no,ratio_diff_keep_minus_no
0,대회,8704,2.5916,8704.0,2.6316,0.0,-0.0400
1,장애인,5392,1.6054,5392.0,1.6302,0.0,-0.0248
2,체육,4031,1.2002,4031.0,1.2187,0.0,-0.0185
3,행사,3885,1.1567,3885.0,1.1746,0.0,-0.0179
4,시설,3395,1.0108,3395.0,1.0264,0.0,-0.0156
...,...,...,...,...,...,...,...
95,어르신,517,0.1539,517.0,0.1563,0.0,-0.0024
96,참여,511,0.1521,511.0,0.1545,0.0,-0.0024
97,추가,510,0.1518,510.0,0.1542,0.0,-0.0024
98,가정,509,0.1516,509.0,0.1539,0.0,-0.0023
99,품질,492,0.1465,492.0,0.1488,0.0,-0.0023

[2] 지역명 제거 버전에서 사라진 토큰 상위 100개

,token,freq_keep_region,ratio_keep_region,freq_no_region,ratio_no_region,freq_diff_keep_minus_no,ratio_diff_keep_minus_no
168,경기도,333,0.0991,0.0,0.0,333.0,0.0991
174,연수,325,0.0968,0.0,0.0,325.0,0.0968
179,경남,320,0.0953,0.0,0.0,320.0,0.0953
185,전남,311,0.0926,0.0,0.0,311.0,0.0926
194,경기,293,0.0872,0.0,0.0,293.0,0.0872
221,경북,266,0.0792,0.0,0.0,266.0,0.0792
243,강원도,243,0.0724,0.0,0.0,243.0,0.0724
259,대전,232,0.0691,0.0,0.0,232.0,0.0691
271,전북,223,0.0664,0.0,0.0,223.0,0.0664
295,충북,203,0.0604,0.0,0.0,203.0,0.0604
311,강원,191,0.0569,0.0,0.0,191.0,0.0569
331,전라남도,179,0.0533,0.0,0.0,179.0,0.0533
374,울산,156,0.0464,0.0,0.0,156.0,0.0464
478,충남,124,0.0369,0.0,0.0,124.0,0.0369
511,서울,117,0.0348,0.0,0.0,117.0,0.0348
550,창원,108,0.0322,0.0,0.0,108.0,0.0322
585,대구,102,0.0304,0.0,0.0,102.0,0.0304
643,경상북도,90,0.0268,0.0,0.0,90.0,0.0268
644,광주,90,0.0268,0.0,0.0,90.0,0.0268
661,진주,87,0.0259,0.0,0.0,87.0,0.0259
672,김해,85,0.0253,0.0,0.0,85.0,0.0253
744,충청북도,75,0.0223,0.0,0.0,75.0,0.0223
791,전라북도,69,0.0205,0.0,0.0,69.0,0.0205
826,영주,66,0.0197,0.0,0.0,66.0,0.0197
827,청주,66,0.0197,0.0,0.0,66.0,0.0197
854,전주,64,0.0191,0.0,0.0,64.0,0.0191
891,충청남도,61,0.0182,0.0,0.0,61.0,0.0182
905,경상남도,59,0.0176,0.0,0.0,59.0,0.0176
932,양산,56,0.0167,0.0,0.0,56.0,0.0167
1088,인천,48,0.0143,0.0,0.0,48.0,0.0143
1089,통영,48,0.0143,0.0,0.0,48.0,0.0143
1283,광주시,39,0.0116,0.0,0.0,39.0,0.0116
1340,부산,37,0.0110,0.0,0.0,37.0,0.0110
1366,창녕,36,0.0107,0.0,0.0,36.0,0.0107
1454,안양,33,0.0098,0.0,0.0,33.0,0.0098
1487,속초,32,0.0095,0.0,0.0,32.0,0.0095
1518,제천,31,0.0092,0.0,0.0,31.0,0.0092
1519,하남,31,0.0092,0.0,0.0,31.0,0.0092
1559,사천,30,0.0089,0.0,0.0,30.0,0.0089
1637,남해,28,0.0083,0.0,0.0,28.0,0.0083
1725,서울시,26,0.0077,0.0,0.0,26.0,0.0077
2185,세종,18,0.0054,0.0,0.0,18.0,0.0054
2262,부여,17,0.0051,0.0,0.0,17.0,0.0051
2552,계양,14,0.0042,0.0,0.0,14.0,0.0042
2794,밀양,12,0.0036,0.0,0.0,12.0,0.0036
2795,제주,12,0.0036,0.0,0.0,12.0,0.0036
3536,대구시,8,0.0024,0.0,0.0,8.0,0.0024
5274,부산시,4,0.0012,0.0,0.0,4.0,0.0012
5275,인천시,4,0.0012,0.0,0.0,4.0,0.0012
6283,제주도,3,0.0009,0.0,0.0,3.0,0.0009
18198,울산시,1,0.0003,0.0,0.0,1.0,0.0003

[3] 지역명 제거 버전에 아직 남아 있는 행정/사업유형 후보

    token  freq  ratio_percent
0      대회  8704         2.6316
3      행사  3885         1.1746
4      시설  3395         1.0264
5      센터  2807         0.8487
12     활동  2324         0.7026
15     개선  1920         0.5805
19     육성  1629         0.4925
25   프로그램  1431         0.4326
33     조성  1233         0.3728
37     강화  1117         0.3377
47     설치   896         0.2709
49     구입   869         0.2627
50     공모   866         0.2618
90     보급   550         0.1663
92     정비   536         0.1621
93     홍보   526         0.1590
96     참여   511         0.1545
97     추가   510         0.1542
120    교류   420         0.1270
122   서비스   419         0.1267
140    기념   387         0.1170
155    개발   357         0.1079
158    증진   355         0.1073
231    제작   247         0.0747
239    상담   241         0.0729
344    확대   167         0.0505

[4] 정책분야 핵심어 보존 확인

     token  freq  ratio_percent
1      장애인  5392         1.6302
2       체육  4031         1.2187
6       문화  2728         0.8248
7       교육  2508         0.7583
13      마을  2288         0.6918
14      환경  2051         0.6201
17      복지  1784         0.5394
20      노인  1624         0.4910
21      아동  1588         0.4801
23     청소년  1531         0.4629
27      여성  1374         0.4154
42      농업   963         0.2912
53      예술   840         0.2540
61      안전   783         0.2367
65      청년   697         0.2107
70      농촌   641         0.1938
108    공동체   472         0.1427
112     건강   452         0.1367
114     산업   439         0.1327
129     기업   406         0.1228
133    다문화   397         0.1200
148     관광   371         0.1122
151     도시   364         0.1101
163    어린이   343         0.1037
179     축산   315         0.0952
190     창업   290         0.0877
202     교통   282         0.0853
215    일자리   268         0.0810
332     방범   171         0.0517
346     의료   167         0.0505
388     재난   147         0.0444
531     주거   108         0.0327
696     임업    78         0.0236
761     어업    70         0.0212
905     수산    55         0.0166
1135    보건    43         0.0130
1433    고용    32         0.0097

[5] 지역명 제거 버전 빈 토큰 행 검토
- 지역명 제거 버전 빈 토큰 행 수: 63

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_filtered_keep_region,tokens_filtered_no_region,tokens_raw_count,tokens_filtered_keep_region_count,tokens_filtered_no_region_count,평가결과,평가종류
1632,경남,양산시,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
1841,경남,창원시,열아홉을 위하여,열아홉을 위하여,[],[],[],0,0,0,미흡,유지필요성평가
7472,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,보통,성과평가
7473,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,우수,성과평가
7474,경남,김해시,김해바로알기 운영,김해바로알기 운영,"[김해, 운영]",[김해],[],2,1,0,보통,성과평가
...,...,...,...,...,...,...,...,...,...,...,...,...
49714,경기,화성시,운영비,운영비,[운영비],[],[],1,0,0,우수,성과평가
54060,경기,광명시,"운영비(인건비,운영비)","운영비(인건비,운영비)","[운영비, 인건비, 운영비]",[],[],3,0,0,매우우수,유지필요성평가
62885,전북,장수군,운영비 지원,운영비 지원,"[운영비, 지원]",[],[],2,0,0,보통,성과평가
65337,전북,군산시,나를찾아서 제16집,나를찾아서 제16집,[16],[],[],1,0,0,보통,성과평가
69412,전남,함평군,난 대전 개최사업 지원,난 대전 개최사업 지원,"[대전, 개최, 사업, 지원]",[대전],[],4,1,0,매우우수,성과평가/유지필요성평가

[6] 추가 불용어 후보 검토표 상위 100개

   token  freq  ratio_percent          검토분류_초안 추가제거여부 검토메모
0     대회  8704         2.6316  행정/사업유형 후보_검토필요
1    장애인  5392         1.6302    정책분야 핵심어_보존권장
2     체육  4031         1.2187    정책분야 핵심어_보존권장
3     행사  3885         1.1746  행정/사업유형 후보_검토필요
4     시설  3395         1.0264  행정/사업유형 후보_검토필요
..   ...   ...            ...              ...    ...  ...
95   어르신   517         0.1563             검토필요
96    참여   511         0.1545  행정/사업유형 후보_검토필요
97    추가   510         0.1542  행정/사업유형 후보_검토필요
98    가정   509         0.1539             검토필요
99    품질   492         0.1488             검토필요

[100 rows x 6 columns]

03-12 저장 완료
- 필터링 비교 Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_filter_compare_v1_20260526_1839.xlsx
- 저장 파일 존재 여부: True

03-12 완료
다음 단계에서는 추가 불용어를 실제로 적용할지 판단합니다.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

03-13. 애매 지역명 후보 보정 및 보수적 지역명 제거 버전 생성
1. 이 단계의 목적

이 단계는 03-11에서 만든 tokens_filtered_no_region을 바로 확정하지 않고, 지역명으로 보기 애매한 토큰을 다시 보존하는 보수적 지역명 제거 버전을 만드는 단계입니다.

특히 다음 단어는 자동 지역명 제거에서 제외합니다.

토큰	이유
대전	대전광역시일 수도 있지만, 난 대전, 미술대전처럼 전시·공모 의미일 수 있음
연수	인천 연수구일 수도 있지만, 교육·훈련 의미의 연수일 수 있음
경기	경기도일 수도 있지만, 스포츠 경기·경제 경기 의미일 수 있음

원본 열과 기존 필터링 열은 덮어쓰지 않고, 새 열을 만듭니다.

In [ ]:
# 03-13. 애매 지역명 후보 보정 및 보수적 지역명 제거 버전 생성

# ------------------------------------------------------------
# 1) 애매 지역명 후보 지정
# ------------------------------------------------------------
# 아래 토큰은 지역명일 수도 있지만, 일반명사/사업명 의미일 가능성도 큽니다.
# 따라서 보수적 지역명 제거 버전에서는 제거하지 않고 보존합니다.

ambiguous_region_keep_terms = {
    '대전',  # 대전광역시 vs 대전(大展), 미술대전, 난 대전 등
    '연수',  # 인천 연수구 vs 교육/훈련 연수
    '경기'   # 경기도 vs 스포츠 경기/경제 경기
}

# 기존 region_stopwords에서 애매 토큰 제외
region_stopwords_strict = set(region_stopwords) - ambiguous_region_keep_terms

print("03-13. 애매 지역명 후보 보정")
print("- 기존 지역명 제거 후보 수:", len(region_stopwords))
print("- 애매 지역명 보존 토큰:", sorted(ambiguous_region_keep_terms))
print("- 보수적 지역명 제거 후보 수:", len(region_stopwords_strict))


# ------------------------------------------------------------
# 2) 보수적 지역명 제거 함수 정의
# ------------------------------------------------------------

def filter_tokens_no_region_strict(tokens):
    """
    tokens_raw에서 기본 불용어, 1글자 잡음, 숫자, 보수적 지역명 후보를 제거합니다.

    단, '대전', '연수', '경기'처럼 의미가 애매한 토큰은 지역명으로 자동 제거하지 않습니다.
    """

    if not isinstance(tokens, list):
        return []

    filtered = []

    for token in tokens:
        token = str(token).strip()

        if token == '':
            continue

        # 숫자 토큰 제거
        if is_number_token(token):
            continue

        # 기본 불용어 제거
        if token in basic_stopwords:
            continue

        # 1글자 잡음 후보 제거
        if token in one_char_stopwords:
            continue

        # 보수적 지역명 제거
        if token in region_stopwords_strict:
            continue

        filtered.append(token)

    return filtered


# ------------------------------------------------------------
# 3) 새 열 생성
# ------------------------------------------------------------
# 기존 tokens_filtered_no_region은 덮어쓰지 않습니다.

df_text['tokens_filtered_no_region_strict'] = df_text['tokens_raw'].apply(
    filter_tokens_no_region_strict
)

df_text['tokens_filtered_no_region_strict_count'] = (
    df_text['tokens_filtered_no_region_strict'].apply(len)
)

df_text['tokens_filtered_no_region_strict_empty'] = (
    df_text['tokens_filtered_no_region_strict_count'].eq(0)
)


# ------------------------------------------------------------
# 4) 기존 no_region 버전과 보수적 버전 비교 요약
# ------------------------------------------------------------

strict_region_summary = pd.DataFrame({
    '항목': [
        '분석 대상 행 수',
        '기존 지역명 제거 버전 전체 토큰 수',
        '보수적 지역명 제거 버전 전체 토큰 수',
        '기존 지역명 제거 버전 빈 행 수',
        '보수적 지역명 제거 버전 빈 행 수',
        '복원된 토큰 수',
        '빈 행에서 회복된 행 수'
    ],
    '값': [
        len(df_text),
        int(df_text['tokens_filtered_no_region_count'].sum()),
        int(df_text['tokens_filtered_no_region_strict_count'].sum()),
        int(df_text['tokens_filtered_no_region_empty'].sum()),
        int(df_text['tokens_filtered_no_region_strict_empty'].sum()),
        int(
            df_text['tokens_filtered_no_region_strict_count'].sum()
            - df_text['tokens_filtered_no_region_count'].sum()
        ),
        int(
            (
                df_text['tokens_filtered_no_region_empty']
                & ~df_text['tokens_filtered_no_region_strict_empty']
            ).sum()
        )
    ]
})

print("\n[1] 기존 지역명 제거 버전 vs 보수적 지역명 제거 버전 요약")
display(strict_region_summary)


# ------------------------------------------------------------
# 5) 애매 지역명 토큰이 복원된 행 확인
# ------------------------------------------------------------

def list_recovered_ambiguous_tokens(tokens):
    """tokens_raw 안에 애매 지역명 보존 토큰이 있는지 확인합니다."""
    if not isinstance(tokens, list):
        return []
    return [t for t in tokens if t in ambiguous_region_keep_terms]

df_text['ambiguous_region_tokens_in_raw'] = df_text['tokens_raw'].apply(
    list_recovered_ambiguous_tokens
)

df_text['ambiguous_region_token_count'] = df_text['ambiguous_region_tokens_in_raw'].apply(len)

ambiguous_region_recovery_review = df_text.loc[
    df_text['ambiguous_region_token_count'] > 0,
    [
        '시도',
        '지자체명',
        '사업명',
        '사업명_clean_spacefix',
        'tokens_raw',
        'ambiguous_region_tokens_in_raw',
        'tokens_filtered_no_region',
        'tokens_filtered_no_region_strict',
        'tokens_filtered_no_region_count',
        'tokens_filtered_no_region_strict_count',
        '평가결과',
        '평가종류'
    ]
].copy()

print("\n[2] 애매 지역명 후보 포함 행 검토")
print("- 애매 토큰 포함 행 수:", len(ambiguous_region_recovery_review))
display(ambiguous_region_recovery_review.head(100))


# ------------------------------------------------------------
# 6) 기존 no_region에서는 비었지만 strict 버전에서는 살아난 행 확인
# ------------------------------------------------------------

recovered_empty_rows = df_text.loc[
    df_text['tokens_filtered_no_region_empty']
    & ~df_text['tokens_filtered_no_region_strict_empty'],
    [
        '시도',
        '지자체명',
        '사업명',
        '사업명_clean_spacefix',
        'tokens_raw',
        'tokens_filtered_no_region',
        'tokens_filtered_no_region_strict',
        '평가결과',
        '평가종류'
    ]
].copy()

print("\n[3] 기존 no_region에서는 빈 토큰이었지만 strict 버전에서 회복된 행")
print("- 회복된 행 수:", len(recovered_empty_rows))
display(recovered_empty_rows.head(100))


# ------------------------------------------------------------
# 7) 보수적 지역명 제거 버전 빈도표 생성
# ------------------------------------------------------------

token_freq_no_region_strict = make_token_freq(
    df_text,
    'tokens_filtered_no_region_strict'
)

print("\n[4] 보수적 지역명 제거 버전 빈도 상위 100개")
display(token_freq_no_region_strict.head(100))


# ------------------------------------------------------------
# 8) 아직 남아 있는 지역명 후보 확인
# ------------------------------------------------------------
# 여기에는 대전/연수/경기처럼 의도적으로 보존한 애매 토큰이 포함될 수 있습니다.

remaining_region_in_strict = token_freq_no_region_strict[
    token_freq_no_region_strict['token'].isin(region_stopwords)
].copy()

print("\n[5] 보수적 지역명 제거 버전에 남아 있는 기존 지역명 후보")
display(remaining_region_in_strict.head(100))


# ------------------------------------------------------------
# 9) 결과 저장
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

token_freq_no_region_strict_csv = (
    TABLE_DIR / f'03_token_freq_filtered_no_region_strict_v1_{timestamp}.csv'
)

strict_region_review_xlsx = (
    TABLE_DIR / f'03_region_filter_strict_review_v1_{timestamp}.xlsx'
)

token_freq_no_region_strict.to_csv(
    token_freq_no_region_strict_csv,
    index=False,
    encoding='utf-8-sig'
)

with pd.ExcelWriter(strict_region_review_xlsx, engine='openpyxl') as writer:
    strict_region_summary.to_excel(writer, sheet_name='summary', index=False)
    ambiguous_region_recovery_review.to_excel(writer, sheet_name='ambiguous_token_rows', index=False)
    recovered_empty_rows.to_excel(writer, sheet_name='recovered_empty_rows', index=False)
    token_freq_no_region_strict.to_excel(writer, sheet_name='freq_no_region_strict', index=False)
    remaining_region_in_strict.to_excel(writer, sheet_name='remaining_region_terms', index=False)

print("\n03-13 저장 완료")
print("- 보수적 지역명 제거 빈도표:", token_freq_no_region_strict_csv)
print("- 보수적 지역명 검토 Excel:", strict_region_review_xlsx)

print("\n저장 파일 존재 여부")
print("- token_freq_no_region_strict_csv:", token_freq_no_region_strict_csv.exists())
print("- strict_region_review_xlsx:", strict_region_review_xlsx.exists())

print("\n03-13 완료")
print("다음 단계에서는 보수적 지역명 제거 버전을 기준으로 2차 불용어 적용 여부를 판단합니다.")

03-13. 애매 지역명 후보 보정
- 기존 지역명 제거 후보 수: 52
- 애매 지역명 보존 토큰: ['경기', '대전', '연수']
- 보수적 지역명 제거 후보 수: 49

[1] 기존 지역명 제거 버전 vs 보수적 지역명 제거 버전 요약

                      항목       값
0              분석 대상 행 수   79262
1   기존 지역명 제거 버전 전체 토큰 수  330753
2  보수적 지역명 제거 버전 전체 토큰 수  331603
3     기존 지역명 제거 버전 빈 행 수      63
4    보수적 지역명 제거 버전 빈 행 수      61
5               복원된 토큰 수     850
6          빈 행에서 회복된 행 수       2

[2] 애매 지역명 후보 포함 행 검토
- 애매 토큰 포함 행 수: 841

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,ambiguous_region_tokens_in_raw,tokens_filtered_no_region,tokens_filtered_no_region_strict,tokens_filtered_no_region_count,tokens_filtered_no_region_strict_count,평가결과,평가종류
146,경남,남해군,모범이장 해외연수,모범이장 해외연수,"[모범, 해외, 연수]",[연수],"[모범, 해외]","[모범, 해외, 연수]",2,3,매우우수,성과평가
393,경남,산청군,새마을지도자 연수대회(핵심지도자 워크숍),새마을지도자 연수대회(핵심지도자 워크숍),"[새마을, 지도자, 연수, 대회, 핵심, 지도자, 워크숍]",[연수],"[새마을, 지도자, 대회, 핵심, 지도자, 워크숍]","[새마을, 지도자, 연수, 대회, 핵심, 지도자, 워크숍]",6,7,보통,유지필요성평가
758,경남,진주시,여성경제인 경영 정보화 교육 연수지원,여성경제인 경영 정보화 교육 연수지원,"[여성, 경제인, 경영, 정보, 교육, 연수, 지원]",[연수],"[여성, 경제인, 경영, 정보, 교육]","[여성, 경제인, 경영, 정보, 교육, 연수]",5,6,보통,성과평가
895,경남,진주시,공예품 대전,공예품 대전,"[공예품, 대전]",[대전],[공예품],"[공예품, 대전]",1,2,보통,성과평가
901,경남,진주시,대한민국등 공모대전,대한민국등 공모대전,"[대한민국, 공모, 대전]",[대전],"[대한민국, 공모]","[대한민국, 공모, 대전]",2,3,보통,성과평가
...,...,...,...,...,...,...,...,...,...,...,...,...
10592,인천,본청,체육회 운동경기부 지원,체육회 운동경기부 지원,"[체육회, 운동, 경기, 부, 지원]",[경기],"[체육회, 운동, 부]","[체육회, 운동, 경기, 부]",3,4,우수,성과평가
10624,인천,본청,장애인체육회 직장운동경기부 운영,장애인체육회 직장운동경기부 운영,"[장애인, 체육회, 직장, 운동, 경기, 부, 운영]",[경기],"[장애인, 체육회, 직장, 운동, 부]","[장애인, 체육회, 직장, 운동, 경기, 부]",5,6,보통,성과평가
10627,인천,본청,장애인 경기단체 육성,장애인 경기단체 육성,"[장애인, 경기, 단체, 육성]",[경기],"[장애인, 단체, 육성]","[장애인, 경기, 단체, 육성]",3,4,보통,성과평가
10659,인천,본청,장애인 기능경기대회,장애인 기능경기대회,"[장애인, 기능, 경기, 대회]",[경기],"[장애인, 기능, 대회]","[장애인, 기능, 경기, 대회]",3,4,미흡,성과평가
10701,인천,본청,(사)대한노인회인천시연합회 대의원·직원 비교연수,(사)대한노인회인천시연합회 대의원·직원 비교연수,"[대한노인회, 인천시, 연합회, 대의원, 직원, 비교, 연수]",[연수],"[대한노인회, 연합회, 대의원, 직원, 비교]","[대한노인회, 연합회, 대의원, 직원, 비교, 연수]",5,6,매우미흡,성과평가

[3] 기존 no_region에서는 빈 토큰이었지만 strict 버전에서 회복된 행
- 회복된 행 수: 2

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_filtered_no_region,tokens_filtered_no_region_strict,평가결과,평가종류
11778,대전,본청,대전십무,대전십무,[대전],[],[대전],보통,유지필요성평가
69412,전남,함평군,난 대전 개최사업 지원,난 대전 개최사업 지원,"[대전, 개최, 사업, 지원]",[],[대전],매우우수,성과평가/유지필요성평가

[4] 보수적 지역명 제거 버전 빈도 상위 100개

   token  freq  ratio_percent
0     대회  8704         2.6248
1    장애인  5392         1.6260
2     체육  4031         1.2156
3     행사  3885         1.1716
4     시설  3395         1.0238
..   ...   ...            ...
95   어르신   517         0.1559
96    참여   511         0.1541
97    추가   510         0.1538
98    가정   509         0.1535
99    품질   492         0.1484

[100 rows x 3 columns]

[5] 보수적 지역명 제거 버전에 남아 있는 기존 지역명 후보

    token  freq  ratio_percent
173    연수   325         0.0980
191    경기   293         0.0884
252    대전   232         0.0700

03-13 저장 완료
- 보수적 지역명 제거 빈도표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_filtered_no_region_strict_v1_20260526_1851.csv
- 보수적 지역명 검토 Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_region_filter_strict_review_v1_20260526_1851.xlsx

저장 파일 존재 여부
- token_freq_no_region_strict_csv: True
- strict_region_review_xlsx: True

03-13 완료
다음 단계에서는 보수적 지역명 제거 버전을 기준으로 2차 불용어 적용 여부를 판단합니다.

03-14. 최종 분석용 토큰 기준 설정 및 2차 불용어 후보 비교
1. 이 단계의 목적

이 단계에서는 03번의 기본 분석용 토큰 열을 정합니다.

현재까지 만든 주요 토큰 열은 다음과 같습니다.
| 열                                  | 의미                        |
| ---------------------------------- | ------------------------- |
| `tokens_raw`                       | 형태소 분석 직후 원시 토큰           |
| `tokens_filtered_keep_region`      | 지역명 보존 1차 필터링             |
| `tokens_filtered_no_region`        | 강한 지역명 제거 1차 필터링          |
| `tokens_filtered_no_region_strict` | 애매 지역명은 보존한 보수적 지역명 제거 버전 |

현재 흐름상 기본 분석용 토큰은 tokens_filtered_no_region_strict로 두는 것이 가장 안전합니다.

다만 대회, 행사, 시설, 센터, 활동, 개선, 조성 같은 단어가 여전히 상위에 남아 있으므로, 이들을 추가로 제거했을 때 결과가 얼마나 달라지는지 비교용 버전도 만듭니다

In [ ]:
# 03-14. 최종 분석용 토큰 기준 설정 및 2차 불용어 후보 비교

# ------------------------------------------------------------
# 1) 기본 분석용 토큰 열 설정
# ------------------------------------------------------------
# 현재 기본 분석 후보는 보수적 지역명 제거 버전입니다.
# 기존 열은 보존하고, 분석용 별칭 열을 새로 만듭니다.

df_text['tokens_analysis_primary'] = df_text['tokens_filtered_no_region_strict'].copy()
df_text['tokens_analysis_primary_count'] = df_text['tokens_analysis_primary'].apply(len)
df_text['tokens_analysis_primary_empty'] = df_text['tokens_analysis_primary_count'].eq(0)

print("03-14. 기본 분석용 토큰 설정")
print("- 기본 분석용 토큰 열: tokens_analysis_primary")
print("- 기준 열: tokens_filtered_no_region_strict")


# ------------------------------------------------------------
# 2) 2차 불용어 후보 설정
# ------------------------------------------------------------
# 주의:
# 아래 단어들은 바로 최종 제거 확정이 아닙니다.
# 제거했을 때 결과가 얼마나 달라지는지 비교하기 위한 후보입니다.
#
# '대회', '행사', '시설', '센터', '프로그램'은 일부 정책분야 단서가 될 수 있으므로
# 이번 2차 후보에서는 일단 제외합니다.
#
# 비교적 일반 행정동사/사업수단에 가까운 단어만 보수적으로 후보에 넣습니다.

second_stopword_candidates = {
    '개선', '조성', '육성', '강화',
    '설치', '구입', '보급', '정비',
    '참여', '추가', '제작', '확대'
}

# 정책분야 핵심어 보호
second_stopword_candidates = second_stopword_candidates - policy_preserve_terms

print("\n[1] 2차 불용어 후보")
print(sorted(second_stopword_candidates))


# ------------------------------------------------------------
# 3) 2차 불용어 후보 적용 함수
# ------------------------------------------------------------

def apply_second_filter(tokens):
    """
    기본 분석용 토큰에서 2차 불용어 후보를 제거합니다.

    이 결과는 비교용입니다.
    최종 확정은 빈도 비교 후 결정합니다.
    """
    if not isinstance(tokens, list):
        return []

    return [
        token for token in tokens
        if str(token).strip() != ''
        and token not in second_stopword_candidates
    ]


df_text['tokens_analysis_second_filter'] = df_text['tokens_analysis_primary'].apply(
    apply_second_filter
)

df_text['tokens_analysis_second_filter_count'] = (
    df_text['tokens_analysis_second_filter'].apply(len)
)

df_text['tokens_analysis_second_filter_empty'] = (
    df_text['tokens_analysis_second_filter_count'].eq(0)
)


# ------------------------------------------------------------
# 4) 2차 필터링 영향 요약
# ------------------------------------------------------------

second_filter_summary = pd.DataFrame({
    '항목': [
        '분석 대상 행 수',
        '기본 분석용 토큰 전체 수',
        '2차 필터링 후 토큰 전체 수',
        '2차 필터링으로 제거된 토큰 수',
        '기본 분석용 토큰 빈 행 수',
        '2차 필터링 후 빈 행 수',
        '2차 필터링으로 새로 빈 행 수',
        '기본 분석용 평균 토큰 수',
        '2차 필터링 후 평균 토큰 수'
    ],
    '값': [
        len(df_text),
        int(df_text['tokens_analysis_primary_count'].sum()),
        int(df_text['tokens_analysis_second_filter_count'].sum()),
        int(
            df_text['tokens_analysis_primary_count'].sum()
            - df_text['tokens_analysis_second_filter_count'].sum()
        ),
        int(df_text['tokens_analysis_primary_empty'].sum()),
        int(df_text['tokens_analysis_second_filter_empty'].sum()),
        int(
            (
                ~df_text['tokens_analysis_primary_empty']
                & df_text['tokens_analysis_second_filter_empty']
            ).sum()
        ),
        round(df_text['tokens_analysis_primary_count'].mean(), 3),
        round(df_text['tokens_analysis_second_filter_count'].mean(), 3)
    ]
})

print("\n[2] 2차 필터링 영향 요약")
display(second_filter_summary)


# ------------------------------------------------------------
# 5) 빈 행이 새로 생긴 경우 확인
# ------------------------------------------------------------

new_empty_after_second_filter = df_text.loc[
    ~df_text['tokens_analysis_primary_empty']
    & df_text['tokens_analysis_second_filter_empty'],
    [
        '시도',
        '지자체명',
        '사업명',
        '사업명_clean_spacefix',
        'tokens_raw',
        'tokens_analysis_primary',
        'tokens_analysis_second_filter',
        '평가결과',
        '평가종류'
    ]
].copy()

print("\n[3] 2차 필터링으로 새로 빈 토큰이 된 행")
print("- 새로 빈 행 수:", len(new_empty_after_second_filter))
display(new_empty_after_second_filter.head(100))


# ------------------------------------------------------------
# 6) 기본 버전과 2차 필터링 버전 빈도표 생성
# ------------------------------------------------------------

token_freq_analysis_primary = make_token_freq(
    df_text,
    'tokens_analysis_primary'
)

token_freq_second_filter = make_token_freq(
    df_text,
    'tokens_analysis_second_filter'
)

print("\n[4] 기본 분석용 토큰 빈도 상위 100개")
display(token_freq_analysis_primary.head(100))

print("\n[5] 2차 필터링 비교용 토큰 빈도 상위 100개")
display(token_freq_second_filter.head(100))


# ------------------------------------------------------------
# 7) 기본 버전과 2차 필터링 버전 비교표
# ------------------------------------------------------------

second_filter_compare = token_freq_analysis_primary.rename(
    columns={
        'freq': 'freq_primary',
        'ratio_percent': 'ratio_primary'
    }
).merge(
    token_freq_second_filter.rename(
        columns={
            'freq': 'freq_second_filter',
            'ratio_percent': 'ratio_second_filter'
        }
    ),
    on='token',
    how='outer'
)

second_filter_compare[
    ['freq_primary', 'ratio_primary', 'freq_second_filter', 'ratio_second_filter']
] = second_filter_compare[
    ['freq_primary', 'ratio_primary', 'freq_second_filter', 'ratio_second_filter']
].fillna(0)

second_filter_compare['freq_diff_primary_minus_second'] = (
    second_filter_compare['freq_primary']
    - second_filter_compare['freq_second_filter']
)

second_filter_compare['ratio_diff_primary_minus_second'] = (
    second_filter_compare['ratio_primary']
    - second_filter_compare['ratio_second_filter']
).round(4)

second_filter_compare = second_filter_compare.sort_values(
    ['freq_primary', 'freq_second_filter'],
    ascending=False
).reset_index(drop=True)

print("\n[6] 기본 버전 vs 2차 필터링 버전 비교 상위 100개")
display(second_filter_compare.head(100))


# ------------------------------------------------------------
# 8) 2차 제거 후보가 실제로 제거되었는지 확인
# ------------------------------------------------------------

removed_second_terms_check = second_filter_compare[
    second_filter_compare['token'].isin(second_stopword_candidates)
].copy()

print("\n[7] 2차 불용어 후보 제거 확인")
display(removed_second_terms_check)


# ------------------------------------------------------------
# 9) 결과 저장
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

token_freq_primary_csv = TABLE_DIR / f'03_token_freq_analysis_primary_v1_{timestamp}.csv'
token_freq_second_csv = TABLE_DIR / f'03_token_freq_second_filter_compare_v1_{timestamp}.csv'
second_filter_review_xlsx = TABLE_DIR / f'03_second_filter_review_v1_{timestamp}.xlsx'

token_freq_analysis_primary.to_csv(
    token_freq_primary_csv,
    index=False,
    encoding='utf-8-sig'
)

token_freq_second_filter.to_csv(
    token_freq_second_csv,
    index=False,
    encoding='utf-8-sig'
)

with pd.ExcelWriter(second_filter_review_xlsx, engine='openpyxl') as writer:
    second_filter_summary.to_excel(writer, sheet_name='summary', index=False)
    new_empty_after_second_filter.to_excel(writer, sheet_name='new_empty_rows', index=False)
    token_freq_analysis_primary.to_excel(writer, sheet_name='freq_primary', index=False)
    token_freq_second_filter.to_excel(writer, sheet_name='freq_second_filter', index=False)
    second_filter_compare.to_excel(writer, sheet_name='freq_compare', index=False)
    removed_second_terms_check.to_excel(writer, sheet_name='removed_terms', index=False)

print("\n03-14 저장 완료")
print("- 기본 분석용 토큰 빈도표:", token_freq_primary_csv)
print("- 2차 필터링 비교용 빈도표:", token_freq_second_csv)
print("- 2차 필터링 검토 Excel:", second_filter_review_xlsx)

print("\n저장 파일 존재 여부")
print("- token_freq_primary_csv:", token_freq_primary_csv.exists())
print("- token_freq_second_csv:", token_freq_second_csv.exists())
print("- second_filter_review_xlsx:", second_filter_review_xlsx.exists())

print("\n03-14 완료")
print("다음 단계에서는 2차 필터링을 최종 적용할지, 아니면 기본 분석용 토큰을 유지할지 결정합니다.")

03-14. 기본 분석용 토큰 설정
- 기본 분석용 토큰 열: tokens_analysis_primary
- 기준 열: tokens_filtered_no_region_strict

[1] 2차 불용어 후보
['강화', '개선', '구입', '보급', '설치', '육성', '정비', '제작', '조성', '참여', '추가', '확대']

[2] 2차 필터링 영향 요약

                  항목           값
0          분석 대상 행 수   79262.000
1     기본 분석용 토큰 전체 수  331603.000
2   2차 필터링 후 토큰 전체 수  321418.000
3  2차 필터링으로 제거된 토큰 수   10185.000
4    기본 분석용 토큰 빈 행 수      61.000
5     2차 필터링 후 빈 행 수      62.000
6  2차 필터링으로 새로 빈 행 수       1.000
7     기본 분석용 평균 토큰 수       4.184
8   2차 필터링 후 평균 토큰 수       4.055

[3] 2차 필터링으로 새로 빈 토큰이 된 행
- 새로 빈 행 수: 1

,시도,지자체명,사업명,사업명_clean_spacefix,tokens_raw,tokens_analysis_primary,tokens_analysis_second_filter,평가결과,평가종류
49794,경기,화성시,추가 운영비 지원,추가 운영비 지원,"[추가, 운영비, 지원]",[추가],[],보통,유지필요성평가

[4] 기본 분석용 토큰 빈도 상위 100개

   token  freq  ratio_percent
0     대회  8704         2.6248
1    장애인  5392         1.6260
2     체육  4031         1.2156
3     행사  3885         1.1716
4     시설  3395         1.0238
..   ...   ...            ...
95   어르신   517         0.1559
96    참여   511         0.1541
97    추가   510         0.1538
98    가정   509         0.1535
99    품질   492         0.1484

[100 rows x 3 columns]

[5] 2차 필터링 비교용 토큰 빈도 상위 100개

   token  freq  ratio_percent
0     대회  8704         2.7080
1    장애인  5392         1.6776
2     체육  4031         1.2541
3     행사  3885         1.2087
4     시설  3395         1.0563
..   ...   ...            ...
95    대학   477         0.1484
96    공연   475         0.1478
97   공동체   472         0.1468
98   유공자   472         0.1468
99  기념행사   471         0.1465

[100 rows x 3 columns]

[6] 기본 버전 vs 2차 필터링 버전 비교 상위 100개

,token,freq_primary,ratio_primary,freq_second_filter,ratio_second_filter,freq_diff_primary_minus_second,ratio_diff_primary_minus_second
0,대회,8704,2.6248,8704.0,2.7080,0.0,-0.0832
1,장애인,5392,1.6260,5392.0,1.6776,0.0,-0.0516
2,체육,4031,1.2156,4031.0,1.2541,0.0,-0.0385
3,행사,3885,1.1716,3885.0,1.2087,0.0,-0.0371
4,시설,3395,1.0238,3395.0,1.0563,0.0,-0.0325
...,...,...,...,...,...,...,...
95,어르신,517,0.1559,517.0,0.1608,0.0,-0.0049
96,참여,511,0.1541,0.0,0.0000,511.0,0.1541
97,추가,510,0.1538,0.0,0.0000,510.0,0.1538
98,가정,509,0.1535,509.0,0.1584,0.0,-0.0049
99,품질,492,0.1484,492.0,0.1531,0.0,-0.0047

[7] 2차 불용어 후보 제거 확인

,token,freq_primary,ratio_primary,freq_second_filter,ratio_second_filter,freq_diff_primary_minus_second,ratio_diff_primary_minus_second
15,개선,1920,0.5790,0.0,0.0,1920.0,0.5790
19,육성,1629,0.4913,0.0,0.0,1629.0,0.4913
33,조성,1233,0.3718,0.0,0.0,1233.0,0.3718
37,강화,1117,0.3368,0.0,0.0,1117.0,0.3368
47,설치,896,0.2702,0.0,0.0,896.0,0.2702
49,구입,869,0.2621,0.0,0.0,869.0,0.2621
90,보급,550,0.1659,0.0,0.0,550.0,0.1659
92,정비,536,0.1616,0.0,0.0,536.0,0.1616
96,참여,511,0.1541,0.0,0.0,511.0,0.1541
97,추가,510,0.1538,0.0,0.0,510.0,0.1538
233,제작,247,0.0745,0.0,0.0,247.0,0.0745
349,확대,167,0.0504,0.0,0.0,167.0,0.0504

03-14 저장 완료
- 기본 분석용 토큰 빈도표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_analysis_primary_v1_20260526_1900.csv
- 2차 필터링 비교용 빈도표: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_token_freq_second_filter_compare_v1_20260526_1900.csv
- 2차 필터링 검토 Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/03_second_filter_review_v1_20260526_1900.xlsx

저장 파일 존재 여부
- token_freq_primary_csv: True
- token_freq_second_csv: True
- second_filter_review_xlsx: True

03-14 완료
다음 단계에서는 2차 필터링을 최종 적용할지, 아니면 기본 분석용 토큰을 유지할지 결정합니다.

In [ ]:
# 03-14B. 03번 산출물 파일 정리: final / review / archive_intermediate로 이동
# 주의: 삭제하지 않고 폴더만 나눕니다.

from pathlib import Path
import shutil

# 정리할 폴더
FINAL_DIR = TABLE_DIR / 'final'
REVIEW_DIR = TABLE_DIR / 'review'
ARCHIVE_DIR = TABLE_DIR / 'archive_intermediate'

FINAL_DIR.mkdir(parents=True, exist_ok=True)
REVIEW_DIR.mkdir(parents=True, exist_ok=True)
ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)

# 현재 tables 폴더의 파일 목록
all_table_files = [p for p in TABLE_DIR.iterdir() if p.is_file()]

print("정리 전 tables 파일 수:", len(all_table_files))

# 파일명 패턴별 이동 규칙
final_patterns = [
    '03_token_freq_analysis_primary',
    '03_token_freq_filtered_no_region_strict'
]

review_patterns = [
    '03_char_space_issue_candidates',
    '03_region_filter_strict_review',
    '03_second_filter_review'
]

archive_patterns = [
    '03_token_freq_raw',
    '03_candidate_stopword_check',
    '03_token_freq_filtered_keep_region',
    '03_token_freq_filtered_no_region_v1',
    '03_token_filter_summary',
    '03_filter_compare',
    '03_token_freq_second_filter_compare'
]

def move_by_patterns(file_path, patterns, target_dir):
    """파일명이 특정 패턴을 포함하면 target_dir로 이동합니다."""
    for pattern in patterns:
        if pattern in file_path.name:
            target_path = target_dir / file_path.name

            # 이미 대상 위치에 있으면 건너뜁니다.
            if file_path.resolve() == target_path.resolve():
                return True

            shutil.move(str(file_path), str(target_path))
            return True
    return False

moved_log = []

for file_path in all_table_files:
    moved = False

    if move_by_patterns(file_path, final_patterns, FINAL_DIR):
        moved_log.append((file_path.name, 'final'))
        moved = True

    elif move_by_patterns(file_path, review_patterns, REVIEW_DIR):
        moved_log.append((file_path.name, 'review'))
        moved = True

    elif move_by_patterns(file_path, archive_patterns, ARCHIVE_DIR):
        moved_log.append((file_path.name, 'archive_intermediate'))
        moved = True

    else:
        moved_log.append((file_path.name, 'not_moved'))

# 이동 결과 확인
move_result = pd.DataFrame(moved_log, columns=['file_name', 'moved_to'])

print("\n파일 정리 결과")
display(move_result)

print("\n정리 후 폴더별 파일 수")
print("- final:", len(list(FINAL_DIR.glob('*'))))
print("- review:", len(list(REVIEW_DIR.glob('*'))))
print("- archive_intermediate:", len(list(ARCHIVE_DIR.glob('*'))))
print("- tables 루트에 남은 파일:", len([p for p in TABLE_DIR.iterdir() if p.is_file()]))

print("\n폴더 경로")
print("- FINAL_DIR:", FINAL_DIR)
print("- REVIEW_DIR:", REVIEW_DIR)
print("- ARCHIVE_DIR:", ARCHIVE_DIR)

정리 전 tables 파일 수: 19

파일 정리 결과

                                            file_name              moved_to
0   03_char_space_issue_candidates_v1_20260526_055...                review
1   03_char_space_issue_candidates_v1_20260526_055...                review
2   03_char_space_issue_candidates_v1_20260526_165...                review
3   03_char_space_issue_candidates_v1_20260526_165...                review
4              03_token_freq_raw_v1_20260526_1723.csv  archive_intermediate
5   03_candidate_stopword_check_v1_20260526_1723.xlsx  archive_intermediate
6    03_candidate_stopword_check_v1_20260526_1723.csv  archive_intermediate
7              03_token_freq_raw_v1_20260526_1752.csv  archive_intermediate
8   03_candidate_stopword_check_v1_20260526_1752.xlsx  archive_intermediate
9    03_candidate_stopword_check_v1_20260526_1752.csv  archive_intermediate
10  03_token_freq_filtered_keep_region_v1_20260526...  archive_intermediate
11  03_token_freq_filtered_no_region_v1_20260526_1...  archive_intermediate
12       03_token_filter_summary_v1_20260526_1828.csv  archive_intermediate
13            03_filter_compare_v1_20260526_1839.xlsx  archive_intermediate
14  03_token_freq_filtered_no_region_strict_v1_202...                 final
15  03_region_filter_strict_review_v1_20260526_185...                review
16  03_token_freq_analysis_primary_v1_20260526_190...                 final
17  03_token_freq_second_filter_compare_v1_2026052...  archive_intermediate
18      03_second_filter_review_v1_20260526_1900.xlsx                review

정리 후 폴더별 파일 수
- final: 2
- review: 6
- archive_intermediate: 11
- tables 루트에 남은 파일: 0

폴더 경로
- FINAL_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final
- REVIEW_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/review
- ARCHIVE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/archive_intermediate

03-15. 03번 중간 분석 데이터 저장 및 산출물 정리
1. 이 단계의 목적

03번 사업명 텍스트 분석에서 생성한 핵심 분석용 열을 포함하여, 후속 노트북에서 사용할 수 있는 중간 분석 데이터셋을 저장합니다.

특히 다음 후속 작업을 고려합니다.

04번 정책분야 분류
06A 단어 동시출현 네트워크
은세와 공유할 정책분야 연결 분석 준비

| 변수 또는 파일                                                     | 의미               |
| ------------------------------------------------------------ | ---------------- |
| `df_03_analysis`                                             | 03번 중간 분석 데이터    |
| `03_project_name_text_analysis_v1_YYYYMMDD_HHMM.parquet`     | 후속 분석용 parquet   |
| `03_project_name_text_analysis_sample_v1_YYYYMMDD_HHMM.xlsx` | 사람이 확인할 샘플 Excel |
| `03_project_name_text_analysis_columns_v1_YYYYMMDD_HHMM.csv` | 저장 열 목록          |

In [ ]:
# 03-15. 03번 중간 분석 데이터 저장 및 산출물 정리

# ------------------------------------------------------------
# 1) final 폴더 확인
# ------------------------------------------------------------

FINAL_DIR = TABLE_DIR / 'final'
FINAL_DIR.mkdir(parents=True, exist_ok=True)

print("FINAL_DIR:", FINAL_DIR)
print("FINAL_DIR 존재 여부:", FINAL_DIR.exists())


# ------------------------------------------------------------
# 2) 저장할 핵심 열 선정
# ------------------------------------------------------------
# 원본 열과 분석용 파생열을 함께 저장합니다.
# 단, 원본 df 전체가 아니라 사업명 텍스트 분석에 필요한 열 중심으로 저장합니다.

base_cols = [
    # 원자료 식별 및 기본 정보
    '시도',
    '시군구',
    '지자체명',
    '지자체유형',
    '원본파일명',
    'source_file',
    'file_name',

    # 원본 표준 7개 열
    '사업명',
    '보조사업자',
    '사업비합계',
    '보조금',
    '사업자부담',
    '평가결과',
    '평가종류',

    # 03번 분석용 텍스트 정제 열
    '사업명_is_missing',
    '사업명_clean',
    '사업명_key',
    '사업명_clean_is_empty',
    '사업명_clean_changed',
    '사업명_clean_length',
    '사업명_clean_spacefix',

    # 글자 간 공백 진단 및 보정 관련 열
    'char_space_issue_flag',
    'char_space_run_text',
    'char_space_run_count',
    'char_space_max_run_len',
    'spacefix_applied',
    'spacefix_note',
    'char_space_run_text_after_fix2',

    # 토큰 관련 열
    'tokens_raw',
    'tokens_raw_count',
    'tokens_raw_empty',
    'tokens_filtered_keep_region',
    'tokens_filtered_keep_region_count',
    'tokens_filtered_keep_region_empty',
    'tokens_filtered_no_region',
    'tokens_filtered_no_region_count',
    'tokens_filtered_no_region_empty',
    'tokens_filtered_no_region_strict',
    'tokens_filtered_no_region_strict_count',
    'tokens_filtered_no_region_strict_empty',

    # 최종 분석 후보 열
    'tokens_analysis_primary',
    'tokens_analysis_primary_count',
    'tokens_analysis_primary_empty',
    'tokens_analysis_second_filter',
    'tokens_analysis_second_filter_count',
    'tokens_analysis_second_filter_empty'
]

# 실제 df_text에 존재하는 열만 저장합니다.
save_cols = [col for col in base_cols if col in df_text.columns]

# 누락된 열도 확인해둡니다.
missing_save_cols = [col for col in base_cols if col not in df_text.columns]

print("\n저장 대상 열 수:", len(save_cols))
print("저장 대상에서 누락된 열 수:", len(missing_save_cols))

if missing_save_cols:
    print("\n저장 대상 후보였지만 현재 df_text에 없는 열:")
    for col in missing_save_cols:
        print("-", col)


# ------------------------------------------------------------
# 3) 03번 중간 분석 데이터 생성
# ------------------------------------------------------------

df_03_analysis = df_text[save_cols].copy()

print("\n03번 중간 분석 데이터 생성 완료")
print("- 행 수:", len(df_03_analysis))
print("- 열 수:", df_03_analysis.shape[1])

print("\n저장 열 목록:")
for i, col in enumerate(df_03_analysis.columns, start=1):
    print(f"{i:02d}. {col}")


# ------------------------------------------------------------
# 4) 저장 전 핵심 값 재확인
# ------------------------------------------------------------

save_check_summary = pd.DataFrame({
    '항목': [
        '03번 분석 데이터 행 수',
        '원본 사업명 결측 제외 후 행 수',
        'tokens_raw 빈 행 수',
        'tokens_analysis_primary 빈 행 수',
        'tokens_analysis_second_filter 빈 행 수',
        '글자 간 공백 보정 적용 행 수'
    ],
    '값': [
        len(df_03_analysis),
        len(df_text),
        int(df_text['tokens_raw_empty'].sum()) if 'tokens_raw_empty' in df_text.columns else None,
        int(df_text['tokens_analysis_primary_empty'].sum()) if 'tokens_analysis_primary_empty' in df_text.columns else None,
        int(df_text['tokens_analysis_second_filter_empty'].sum()) if 'tokens_analysis_second_filter_empty' in df_text.columns else None,
        int(df_text['spacefix_applied'].sum()) if 'spacefix_applied' in df_text.columns else None
    ]
})

print("\n저장 전 핵심 요약")
display(save_check_summary)


# ------------------------------------------------------------
# 5) 저장 파일명 설정
# ------------------------------------------------------------

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

analysis_parquet = FINAL_DIR / f'03_project_name_text_analysis_v1_{timestamp}.parquet'
analysis_sample_xlsx = FINAL_DIR / f'03_project_name_text_analysis_sample_v1_{timestamp}.xlsx'
columns_csv = FINAL_DIR / f'03_project_name_text_analysis_columns_v1_{timestamp}.csv'
save_check_csv = FINAL_DIR / f'03_project_name_text_analysis_save_check_v1_{timestamp}.csv'


# ------------------------------------------------------------
# 6) 파일 저장
# ------------------------------------------------------------
# parquet은 후속 분석용입니다.
# Excel 샘플은 사람이 빠르게 확인하기 위한 용도입니다.

df_03_analysis.to_parquet(analysis_parquet, index=False)

# 전체 Excel은 행 수가 많아 무거우므로 샘플만 저장합니다.
df_03_analysis.head(1000).to_excel(analysis_sample_xlsx, index=False)

# 저장 열 목록 저장
columns_df = pd.DataFrame({
    'column_order': range(1, len(df_03_analysis.columns) + 1),
    'column_name': df_03_analysis.columns
})

columns_df.to_csv(columns_csv, index=False, encoding='utf-8-sig')

# 저장 전 요약 저장
save_check_summary.to_csv(save_check_csv, index=False, encoding='utf-8-sig')


# ------------------------------------------------------------
# 7) 저장 결과 확인
# ------------------------------------------------------------

print("\n03-15 저장 완료")
print("- 03번 중간 분석 parquet:", analysis_parquet)
print("- 03번 샘플 Excel:", analysis_sample_xlsx)
print("- 03번 저장 열 목록 CSV:", columns_csv)
print("- 03번 저장 전 요약 CSV:", save_check_csv)

print("\n저장 파일 존재 여부")
print("- analysis_parquet:", analysis_parquet.exists())
print("- analysis_sample_xlsx:", analysis_sample_xlsx.exists())
print("- columns_csv:", columns_csv.exists())
print("- save_check_csv:", save_check_csv.exists())


# ------------------------------------------------------------
# 8) final 폴더 파일 목록 확인
# ------------------------------------------------------------

print("\n현재 final 폴더 파일 목록:")
for p in sorted(FINAL_DIR.iterdir()):
    if p.is_file():
        print("-", p.name)

print("\n03-15 완료")
print("이제 03번 사업명 텍스트 분석의 중간 분석 데이터가 저장되었습니다.")
print("다음 단계에서는 03번 결과 요약표와 work_log 기록용 내용을 정리할 수 있습니다.")

FINAL_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final
FINAL_DIR 존재 여부: True

저장 대상 열 수: 41
저장 대상에서 누락된 열 수: 5

저장 대상 후보였지만 현재 df_text에 없는 열:
- 시군구
- 지자체유형
- 원본파일명
- source_file
- file_name

03번 중간 분석 데이터 생성 완료
- 행 수: 79262
- 열 수: 41

저장 열 목록:
01. 시도
02. 지자체명
03. 사업명
04. 보조사업자
05. 사업비합계
06. 보조금
07. 사업자부담
08. 평가결과
09. 평가종류
10. 사업명_is_missing
11. 사업명_clean
12. 사업명_key
13. 사업명_clean_is_empty
14. 사업명_clean_changed
15. 사업명_clean_length
16. 사업명_clean_spacefix
17. char_space_issue_flag
18. char_space_run_text
19. char_space_run_count
20. char_space_max_run_len
21. spacefix_applied
22. spacefix_note
23. char_space_run_text_after_fix2
24. tokens_raw
25. tokens_raw_count
26. tokens_raw_empty
27. tokens_filtered_keep_region
28. tokens_filtered_keep_region_count
29. tokens_filtered_keep_region_empty
30. tokens_filtered_no_region
31. tokens_filtered_no_region_count
32. tokens_filtered_no_region_empty
33. tokens_filtered_no_region_strict
34. tokens_filtered_no_region_strict_count
35. tokens_filtered_no_region_strict_empty
36. tokens_analysis_primary
37. tokens_analysis_primary_count
38. tokens_analysis_primary_empty
39. tokens_analysis_second_filter
40. tokens_analysis_second_filter_count
41. tokens_analysis_second_filter_empty

저장 전 핵심 요약

                                    항목      값
0                       03번 분석 데이터 행 수  79262
1                   원본 사업명 결측 제외 후 행 수  79262
2                     tokens_raw 빈 행 수      4
3        tokens_analysis_primary 빈 행 수     61
4  tokens_analysis_second_filter 빈 행 수     62
5                    글자 간 공백 보정 적용 행 수     24

03-15 저장 완료
- 03번 중간 분석 parquet: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet
- 03번 샘플 Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_sample_v1_20260526_1935.xlsx
- 03번 저장 열 목록 CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_columns_v1_20260526_1935.csv
- 03번 저장 전 요약 CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_save_check_v1_20260526_1935.csv

저장 파일 존재 여부
- analysis_parquet: True
- analysis_sample_xlsx: True
- columns_csv: True
- save_check_csv: True

현재 final 폴더 파일 목록:
- 03_project_name_text_analysis_columns_v1_20260526_1935.csv
- 03_project_name_text_analysis_sample_v1_20260526_1935.xlsx
- 03_project_name_text_analysis_save_check_v1_20260526_1935.csv
- 03_project_name_text_analysis_v1_20260526_1935.parquet
- 03_token_freq_analysis_primary_v1_20260526_1900.csv
- 03_token_freq_filtered_no_region_strict_v1_20260526_1851.csv

03-15 완료
이제 03번 사업명 텍스트 분석의 중간 분석 데이터가 저장되었습니다.
다음 단계에서는 03번 결과 요약표와 work_log 기록용 내용을 정리할 수 있습니다.

In [ ]:
# 03-RESTART 수정 버전
# 기존 03번 중간 분석 parquet 파일을 찾아서 불러오기만 합니다.
# 새 파일은 생성하지 않습니다.

from pathlib import Path
from google.colab import drive
import pandas as pd
import numpy as np
import re
from datetime import datetime
import unicodedata

drive.mount('/content/drive', force_remount=True)

MYDRIVE = Path('/content/drive/MyDrive')

# ------------------------------------------------------------
# 1) 파공장(PA Factory) 폴더 찾기
# ------------------------------------------------------------

pa_candidates = [
    p for p in MYDRIVE.iterdir()
    if p.is_dir() and 'PA Factory' in p.name
]

print("파공장 후보 폴더 수:", len(pa_candidates))

for i, p in enumerate(pa_candidates, start=1):
    print(f"{i}. {p}")

if len(pa_candidates) != 1:
    raise FileNotFoundError("파공장(PA Factory) 폴더를 정확히 1개 찾지 못했습니다.")

PA_FACTORY_DIR = pa_candidates[0]


# ------------------------------------------------------------
# 2) 03번 중간 분석 parquet 파일 넓게 검색
# ------------------------------------------------------------

# 1차: 파일명 정확 패턴 검색
raw_candidates = list(
    PA_FACTORY_DIR.rglob('03_project_name_text_analysis_v1_*.parquet')
)

print("\n1차 검색 후보 수:", len(raw_candidates))

for i, p in enumerate(sorted(raw_candidates), start=1):
    print(f"{i}. {p}")

# 2차: 혹시 파일명 일부가 다를 경우 더 넓게 검색
if len(raw_candidates) == 0:
    print("\n1차 검색에서 찾지 못해 더 넓게 검색합니다.")

    raw_candidates = list(
        PA_FACTORY_DIR.rglob('*project_name_text*analysis*.parquet')
    )

    print("2차 검색 후보 수:", len(raw_candidates))

    for i, p in enumerate(sorted(raw_candidates), start=1):
        print(f"{i}. {p}")

# 3차: parquet 전체 중 03번 final 후보 확인
if len(raw_candidates) == 0:
    print("\n2차 검색에서도 찾지 못해 parquet 전체를 검색합니다.")

    all_parquet_candidates = list(PA_FACTORY_DIR.rglob('*.parquet'))

    print("PA Factory 아래 parquet 전체 수:", len(all_parquet_candidates))

    for i, p in enumerate(sorted(all_parquet_candidates), start=1):
        print(f"{i}. {p}")

    raise FileNotFoundError(
        "03_project_name_text_analysis 관련 parquet을 찾지 못했습니다. "
        "위 parquet 목록에서 실제 파일명을 확인해야 합니다."
    )


# ------------------------------------------------------------
# 3) final 폴더 안에 있는 후보를 우선 선택
# ------------------------------------------------------------

# 경로 문자열을 유니코드 NFC로 정규화해서 비교합니다.
def norm_path_text(path):
    return unicodedata.normalize('NFC', str(path))

final_candidates = [
    p for p in raw_candidates
    if 'tables/final' in norm_path_text(p).replace('\\', '/')
]

print("\nfinal 폴더 후보 수:", len(final_candidates))

for i, p in enumerate(sorted(final_candidates), start=1):
    print(f"{i}. {p}")

# final 후보가 있으면 그중 최신 파일 사용
# final 후보가 없으면 raw 후보 중 최신 파일 사용
if len(final_candidates) > 0:
    ANALYSIS_FILE = sorted(final_candidates)[-1]
else:
    print("\n주의: final 폴더 후보가 없어 전체 후보 중 최신 파일을 사용합니다.")
    ANALYSIS_FILE = sorted(raw_candidates)[-1]

print("\n사용할 03번 중간 분석 파일:")
print(ANALYSIS_FILE)


# ------------------------------------------------------------
# 4) 경로 변수 복원
# ------------------------------------------------------------

FINAL_DIR = ANALYSIS_FILE.parent
TABLE_DIR = FINAL_DIR.parent
OUTPUT_DIR = TABLE_DIR.parent
PROJECT_OUTPUT_DIR = OUTPUT_DIR.parent
FIGURE_DIR = OUTPUT_DIR / 'figures'

print("\n복원된 경로")
print("FINAL_DIR:", FINAL_DIR)
print("TABLE_DIR:", TABLE_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("FIGURE_DIR:", FIGURE_DIR)


# ------------------------------------------------------------
# 5) 03번 중간 분석 데이터 불러오기
# ------------------------------------------------------------

df_03_analysis = pd.read_parquet(ANALYSIS_FILE)
df_text = df_03_analysis.copy()

print("\n03번 중간 분석 데이터 불러오기 완료")
print("- 행 수:", df_text.shape[0])
print("- 열 수:", df_text.shape[1])

print("\n주요 열 존재 여부")
key_cols = [
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'tokens_raw',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter'
]

for col in key_cols:
    print(f"- {col}:", col in df_text.columns)


# ------------------------------------------------------------
# 6) 빈도표 생성 함수 복원
# ------------------------------------------------------------

def make_token_freq(df, token_col):
    """
    리스트 형태 토큰 열을 펼쳐 빈도표를 생성합니다.
    """
    token_long = (
        df[[token_col]]
        .explode(token_col)
        .rename(columns={token_col: 'token'})
        .dropna()
        .copy()
    )

    token_long['token'] = token_long['token'].astype(str).str.strip()
    token_long = token_long[token_long['token'] != '']

    token_freq = (
        token_long['token']
        .value_counts()
        .reset_index()
    )

    token_freq.columns = ['token', 'freq']
    token_freq['ratio_percent'] = (
        token_freq['freq'] / token_freq['freq'].sum() * 100
    ).round(4)

    return token_freq


# ------------------------------------------------------------
# 7) 기본 빈도표 메모리에서만 재생성
# ------------------------------------------------------------

token_freq_analysis_primary = make_token_freq(
    df_text,
    'tokens_analysis_primary'
)

token_freq_second_filter = make_token_freq(
    df_text,
    'tokens_analysis_second_filter'
)

print("\n빈도표 재생성 완료")
print("- token_freq_analysis_primary 행 수:", len(token_freq_analysis_primary))
print("- token_freq_second_filter 행 수:", len(token_freq_second_filter))

print("\n기본 분석용 토큰 빈도 상위 20개")
display(token_freq_analysis_primary.head(20))

print("\n재개 준비 완료")

Mounted at /content/drive
파공장 후보 폴더 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)

1차 검색 후보 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet

final 폴더 후보 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet

사용할 03번 중간 분석 파일:
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet

복원된 경로
FINAL_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final
TABLE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables
OUTPUT_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석
FIGURE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/figures

03번 중간 분석 데이터 불러오기 완료
- 행 수: 79262
- 열 수: 41

주요 열 존재 여부
- 사업명: True
- 사업명_clean: True
- 사업명_clean_spacefix: True
- tokens_raw: True
- tokens_analysis_primary: True
- tokens_analysis_second_filter: True

빈도표 재생성 완료
- token_freq_analysis_primary 행 수: 18151
- token_freq_second_filter 행 수: 18139

기본 분석용 토큰 빈도 상위 20개

   token  freq  ratio_percent
0     대회  8704         2.6248
1    장애인  5392         1.6260
2     체육  4031         1.2156
3     행사  3885         1.1716
4     시설  3395         1.0238
5     센터  2807         0.8465
6     문화  2728         0.8227
7     교육  2508         0.7563
8     단체  2467         0.7440
9     지역  2447         0.7379
10    생활  2439         0.7355
11    전국  2363         0.7126
12    활동  2324         0.7008
13    마을  2288         0.6900
14    환경  2051         0.6185
15    개선  1920         0.5790
16    활성  1807         0.5449
17    복지  1784         0.5380
18   경로당  1720         0.5187
19    육성  1629         0.4913

재개 준비 완료

03-16. 03번 결과 요약 및 work_log 기록용 내용 정리
1. 이 단계의 목적

03번 사업명 텍스트 분석에서 지금까지 처리한 내용을 요약하고, 이후 logs/work_log.md에 기록할 수 있는 문장을 정리합니다.

이번 단계에서는 다음을 확인합니다.

03번 분석 대상 행 수
주요 정제 열 생성 여부
글자 간 공백 보정 적용 수
토큰화 결과
기본 분석용 토큰 기준
저장된 주요 산출물
후속 04번·06A번에서 사용할 입력 기준

In [ ]:
# 03-16. 03번 결과 요약 및 work_log 기록용 내용 정리

# ------------------------------------------------------------
# 0) 파일 저장 여부 설정
# ------------------------------------------------------------
# 파일이 계속 늘어나는 것을 막기 위해 기본값은 False입니다.
# 저장이 필요할 때만 True로 바꾸세요.

SAVE_03_SUMMARY = False


# ------------------------------------------------------------
# 1) 03번 핵심 요약표 생성
# ------------------------------------------------------------

summary_03 = pd.DataFrame({
    '항목': [
        '03번 분석 데이터 행 수',
        '03번 분석 데이터 열 수',
        '원본 사업명 결측 제외 후 행 수',
        'tokens_raw 빈 행 수',
        'tokens_analysis_primary 빈 행 수',
        'tokens_analysis_second_filter 빈 행 수',
        '글자 간 공백 보정 적용 행 수',
        '기본 분석용 토큰 전체 수',
        '2차 필터링 비교용 토큰 전체 수',
        '기본 분석용 고유 토큰 수',
        '2차 필터링 비교용 고유 토큰 수'
    ],
    '값': [
        len(df_text),
        df_text.shape[1],
        len(df_text),
        int(df_text['tokens_raw_empty'].sum()) if 'tokens_raw_empty' in df_text.columns else None,
        int(df_text['tokens_analysis_primary_empty'].sum()) if 'tokens_analysis_primary_empty' in df_text.columns else None,
        int(df_text['tokens_analysis_second_filter_empty'].sum()) if 'tokens_analysis_second_filter_empty' in df_text.columns else None,
        int(df_text['spacefix_applied'].sum()) if 'spacefix_applied' in df_text.columns else None,
        int(df_text['tokens_analysis_primary_count'].sum()) if 'tokens_analysis_primary_count' in df_text.columns else None,
        int(df_text['tokens_analysis_second_filter_count'].sum()) if 'tokens_analysis_second_filter_count' in df_text.columns else None,
        len(token_freq_analysis_primary),
        len(token_freq_second_filter)
    ]
})

print("03-16. 03번 결과 요약")
display(summary_03)


# ------------------------------------------------------------
# 2) 기본 분석용 토큰 상위 빈도 확인
# ------------------------------------------------------------

top_tokens_primary = token_freq_analysis_primary.head(50).copy()
top_tokens_second_filter = token_freq_second_filter.head(50).copy()

print("\n[1] 기본 분석용 토큰 상위 50개")
display(top_tokens_primary)

print("\n[2] 2차 필터링 비교용 토큰 상위 50개")
display(top_tokens_second_filter)


# ------------------------------------------------------------
# 3) final / review / archive 폴더 파일 현황 확인
# ------------------------------------------------------------

REVIEW_DIR = TABLE_DIR / 'review'
ARCHIVE_DIR = TABLE_DIR / 'archive_intermediate'

folder_status = []

for folder_name, folder_path in [
    ('final', FINAL_DIR),
    ('review', REVIEW_DIR),
    ('archive_intermediate', ARCHIVE_DIR)
]:
    if folder_path.exists():
        files = sorted([p.name for p in folder_path.iterdir() if p.is_file()])
        folder_status.append({
            'folder': folder_name,
            'path': str(folder_path),
            'file_count': len(files),
            'files': files
        })
    else:
        folder_status.append({
            'folder': folder_name,
            'path': str(folder_path),
            'file_count': 0,
            'files': []
        })

folder_status_df = pd.DataFrame([
    {
        'folder': item['folder'],
        'file_count': item['file_count'],
        'path': item['path']
    }
    for item in folder_status
])

print("\n[3] 03번 산출물 폴더 현황")
display(folder_status_df)

print("\n[4] final 폴더 파일 목록")
for item in folder_status:
    if item['folder'] == 'final':
        for file_name in item['files']:
            print("-", file_name)


# ------------------------------------------------------------
# 4) work_log.md 기록용 텍스트 생성
# ------------------------------------------------------------

today_str = datetime.now().strftime('%Y-%m-%d')

work_log_text = f"""
## {today_str} - 03_project_name_text_analysis_bumsu.ipynb 사업명 텍스트 분석 중간 산출물 생성

### 작업 개요
- 01번 V1 분석데이터를 기반으로 03번 사업명 텍스트 분석을 진행하였다.
- 원본 `사업명` 열은 덮어쓰지 않고, 분석용 파생열 `사업명_clean`, `사업명_clean_spacefix`, `tokens_raw`, `tokens_analysis_primary`, `tokens_analysis_second_filter`를 생성하였다.
- 사업명 결측 14행은 원본 데이터에서 삭제하지 않고, 텍스트 분석용 데이터에서는 제외된 상태로 79,262행을 분석 대상으로 사용하였다.

### 주요 처리 내용
- 줄바꿈, 탭, 연속 공백, 앞뒤 공백, 특수 따옴표를 정리하여 `사업명_clean`을 생성하였다.
- 글자 간 공백 오류 의심 사례를 진단하고, 명확한 오류 사례만 `사업명_clean_spacefix`에 제한적으로 보정하였다.
- Kiwi 형태소 분석기를 사용하여 `tokens_raw`를 생성하였다.
- 숫자, 기본 행정 일반어, 일부 1글자 잡음, 지역명 후보를 검토하여 필터링 토큰을 생성하였다.
- 지역명 제거는 강한 제거 버전과 보수적 제거 버전을 비교했으며, `경기`, `대전`, `연수`는 일반명사 가능성이 있어 보수적 지역명 제거 버전에서는 보존하였다.
- 현재 03번 기본 분석용 토큰은 `tokens_analysis_primary`이며, 이는 `tokens_filtered_no_region_strict`를 기준으로 한다.
- 2차 불용어 후보를 적용한 `tokens_analysis_second_filter`는 비교용으로 생성했으며, 기본 분석 결과로 확정하지는 않았다.

### 주요 결과
- 03번 분석 데이터 행 수: {len(df_text):,}행
- 저장 열 수: {df_text.shape[1]}개
- `tokens_raw` 빈 행 수: {int(df_text['tokens_raw_empty'].sum()) if 'tokens_raw_empty' in df_text.columns else '확인필요'}
- `tokens_analysis_primary` 빈 행 수: {int(df_text['tokens_analysis_primary_empty'].sum()) if 'tokens_analysis_primary_empty' in df_text.columns else '확인필요'}
- 글자 간 공백 보정 적용 행 수: {int(df_text['spacefix_applied'].sum()) if 'spacefix_applied' in df_text.columns else '확인필요'}
- 기본 분석용 고유 토큰 수: {len(token_freq_analysis_primary):,}개

### 저장 산출물
- 03번 중간 분석 데이터 parquet:
  - `03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet`
- 03번 샘플 확인 Excel:
  - `03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_sample_v1_20260526_1935.xlsx`
- 기본 분석용 토큰 빈도표:
  - `03_v1_사업명텍스트분석/tables/final/03_token_freq_analysis_primary_v1_20260526_1900.csv`
- 보수적 지역명 제거 빈도표:
  - `03_v1_사업명텍스트분석/tables/final/03_token_freq_filtered_no_region_strict_v1_20260526_1851.csv`
- 검토 근거 파일은 `tables/review`, 중간 산출물은 `tables/archive_intermediate`로 이동하여 정리하였다.

### 후속 작업 참고
- 04번 정책분야 분류에서는 `사업명_clean_spacefix`와 `tokens_analysis_primary`를 기본 참고 열로 사용한다.
- 06A 단어 동시출현 네트워크 분석에서는 우선 `tokens_analysis_primary`를 기본 토큰으로 사용하고, 필요 시 `tokens_analysis_second_filter`와 비교한다.
- 2차 불용어 적용 여부는 포스터용 빈도표와 네트워크 결과를 비교한 뒤 최종 판단한다.
"""

print("\n[5] work_log.md 기록용 초안")
print(work_log_text)


# ------------------------------------------------------------
# 5) 선택적 저장
# ------------------------------------------------------------
# 기본값은 저장하지 않습니다.
# SAVE_03_SUMMARY = True로 바꾼 경우에만 final 폴더에 저장합니다.

if SAVE_03_SUMMARY:
    timestamp = datetime.now().strftime('%Y%m%d_%H%M')

    summary_csv = FINAL_DIR / f'03_summary_for_worklog_v1_{timestamp}.csv'
    worklog_txt = FINAL_DIR / f'03_worklog_draft_v1_{timestamp}.txt'

    summary_03.to_csv(summary_csv, index=False, encoding='utf-8-sig')

    with open(worklog_txt, 'w', encoding='utf-8') as f:
        f.write(work_log_text)

    print("\n03-16 저장 완료")
    print("- 요약 CSV:", summary_csv)
    print("- work_log 초안 TXT:", worklog_txt)
    print("- summary_csv exists:", summary_csv.exists())
    print("- worklog_txt exists:", worklog_txt.exists())
else:
    print("\nSAVE_03_SUMMARY = False이므로 새 파일은 생성하지 않았습니다.")
    print("work_log_text는 위 출력 내용을 복사해서 logs/work_log.md에 붙여 넣으면 됩니다.")

03-16. 03번 결과 요약

                                     항목       값
0                        03번 분석 데이터 행 수   79262
1                        03번 분석 데이터 열 수      41
2                    원본 사업명 결측 제외 후 행 수   79262
3                      tokens_raw 빈 행 수       4
4         tokens_analysis_primary 빈 행 수      61
5   tokens_analysis_second_filter 빈 행 수      62
6                     글자 간 공백 보정 적용 행 수      24
7                        기본 분석용 토큰 전체 수  331603
8                    2차 필터링 비교용 토큰 전체 수  321418
9                        기본 분석용 고유 토큰 수   18151
10                   2차 필터링 비교용 고유 토큰 수   18139

[1] 기본 분석용 토큰 상위 50개

   token  freq  ratio_percent
0     대회  8704         2.6248
1    장애인  5392         1.6260
2     체육  4031         1.2156
3     행사  3885         1.1716
4     시설  3395         1.0238
5     센터  2807         0.8465
6     문화  2728         0.8227
7     교육  2508         0.7563
8     단체  2467         0.7440
9     지역  2447         0.7379
10    생활  2439         0.7355
11    전국  2363         0.7126
12    활동  2324         0.7008
13    마을  2288         0.6900
14    환경  2051         0.6185
15    개선  1920         0.5790
16    활성  1807         0.5449
17    복지  1784         0.5380
18   경로당  1720         0.5187
19    육성  1629         0.4913
20    노인  1624         0.4897
21    아동  1588         0.4789
22    사회  1535         0.4629
23   청소년  1531         0.4617
24    시범  1485         0.4478
25  프로그램  1431         0.4315
26  어린이집  1400         0.4222
27    여성  1374         0.4144
28     날  1338         0.4035
29     비  1319         0.3978
30    축제  1301         0.3923
31    지회  1299         0.3917
32    공동  1270         0.3830
33    조성  1233         0.3718
34   종사자  1232         0.3715
35    주민  1160         0.3498
36   협의회  1148         0.3462
37    강화  1117         0.3368
38    운동  1106         0.3335
39   지도자  1057         0.3188
40   한마음  1011         0.3049
41    생산   985         0.2970
42    농업   963         0.2904
43    보훈   957         0.2886
44    농가   946         0.2853
45    주택   918         0.2768
46    출전   910         0.2744
47    설치   896         0.2702
48    체험   876         0.2642
49    구입   869         0.2621

[2] 2차 필터링 비교용 토큰 상위 50개

   token  freq  ratio_percent
0     대회  8704         2.7080
1    장애인  5392         1.6776
2     체육  4031         1.2541
3     행사  3885         1.2087
4     시설  3395         1.0563
5     센터  2807         0.8733
6     문화  2728         0.8487
7     교육  2508         0.7803
8     단체  2467         0.7675
9     지역  2447         0.7613
10    생활  2439         0.7588
11    전국  2363         0.7352
12    활동  2324         0.7230
13    마을  2288         0.7118
14    환경  2051         0.6381
15    활성  1807         0.5622
16    복지  1784         0.5550
17   경로당  1720         0.5351
18    노인  1624         0.5053
19    아동  1588         0.4941
20    사회  1535         0.4776
21   청소년  1531         0.4763
22    시범  1485         0.4620
23  프로그램  1431         0.4452
24  어린이집  1400         0.4356
25    여성  1374         0.4275
26     날  1338         0.4163
27     비  1319         0.4104
28    축제  1301         0.4048
29    지회  1299         0.4041
30    공동  1270         0.3951
31   종사자  1232         0.3833
32    주민  1160         0.3609
33   협의회  1148         0.3572
34    운동  1106         0.3441
35   지도자  1057         0.3289
36   한마음  1011         0.3145
37    생산   985         0.3065
38    농업   963         0.2996
39    보훈   957         0.2977
40    농가   946         0.2943
41    주택   918         0.2856
42    출전   910         0.2831
43    체험   876         0.2725
44    공모   866         0.2694
45    역량   858         0.2669
46    교실   854         0.2657
47    예술   840         0.2613
48    수당   833         0.2592
49    가족   828         0.2576

[3] 03번 산출물 폴더 현황

,folder,file_count,path
0,final,6,/content/drive/MyDrive/파공장 (PA Factory)/2...
1,review,6,/content/drive/MyDrive/파공장 (PA Factory)/2...
2,archive_intermediate,11,/content/drive/MyDrive/파공장 (PA Factory)/2...

[4] final 폴더 파일 목록
- 03_project_name_text_analysis_columns_v1_20260526_1935.csv
- 03_project_name_text_analysis_sample_v1_20260526_1935.xlsx
- 03_project_name_text_analysis_save_check_v1_20260526_1935.csv
- 03_project_name_text_analysis_v1_20260526_1935.parquet
- 03_token_freq_analysis_primary_v1_20260526_1900.csv
- 03_token_freq_filtered_no_region_strict_v1_20260526_1851.csv

[5] work_log.md 기록용 초안

## 2026-05-27 - 03_project_name_text_analysis_bumsu.ipynb 사업명 텍스트 분석 중간 산출물 생성

### 작업 개요
- 01번 V1 분석데이터를 기반으로 03번 사업명 텍스트 분석을 진행하였다.
- 원본 `사업명` 열은 덮어쓰지 않고, 분석용 파생열 `사업명_clean`, `사업명_clean_spacefix`, `tokens_raw`, `tokens_analysis_primary`, `tokens_analysis_second_filter`를 생성하였다.
- 사업명 결측 14행은 원본 데이터에서 삭제하지 않고, 텍스트 분석용 데이터에서는 제외된 상태로 79,262행을 분석 대상으로 사용하였다.

### 주요 처리 내용
- 줄바꿈, 탭, 연속 공백, 앞뒤 공백, 특수 따옴표를 정리하여 `사업명_clean`을 생성하였다.
- 글자 간 공백 오류 의심 사례를 진단하고, 명확한 오류 사례만 `사업명_clean_spacefix`에 제한적으로 보정하였다.
- Kiwi 형태소 분석기를 사용하여 `tokens_raw`를 생성하였다.
- 숫자, 기본 행정 일반어, 일부 1글자 잡음, 지역명 후보를 검토하여 필터링 토큰을 생성하였다.
- 지역명 제거는 강한 제거 버전과 보수적 제거 버전을 비교했으며, `경기`, `대전`, `연수`는 일반명사 가능성이 있어 보수적 지역명 제거 버전에서는 보존하였다.
- 현재 03번 기본 분석용 토큰은 `tokens_analysis_primary`이며, 이는 `tokens_filtered_no_region_strict`를 기준으로 한다.
- 2차 불용어 후보를 적용한 `tokens_analysis_second_filter`는 비교용으로 생성했으며, 기본 분석 결과로 확정하지는 않았다.

### 주요 결과
- 03번 분석 데이터 행 수: 79,262행
- 저장 열 수: 41개
- `tokens_raw` 빈 행 수: 4
- `tokens_analysis_primary` 빈 행 수: 61
- 글자 간 공백 보정 적용 행 수: 24
- 기본 분석용 고유 토큰 수: 18,151개

### 저장 산출물
- 03번 중간 분석 데이터 parquet:
  - `03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet`
- 03번 샘플 확인 Excel:
  - `03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_sample_v1_20260526_1935.xlsx`
- 기본 분석용 토큰 빈도표:
  - `03_v1_사업명텍스트분석/tables/final/03_token_freq_analysis_primary_v1_20260526_1900.csv`
- 보수적 지역명 제거 빈도표:
  - `03_v1_사업명텍스트분석/tables/final/03_token_freq_filtered_no_region_strict_v1_20260526_1851.csv`
- 검토 근거 파일은 `tables/review`, 중간 산출물은 `tables/archive_intermediate`로 이동하여 정리하였다.

### 후속 작업 참고
- 04번 정책분야 분류에서는 `사업명_clean_spacefix`와 `tokens_analysis_primary`를 기본 참고 열로 사용한다.
- 06A 단어 동시출현 네트워크 분석에서는 우선 `tokens_analysis_primary`를 기본 토큰으로 사용하고, 필요 시 `tokens_analysis_second_filter`와 비교한다.
- 2차 불용어 적용 여부는 포스터용 빈도표와 네트워크 결과를 비교한 뒤 최종 판단한다.


SAVE_03_SUMMARY = False이므로 새 파일은 생성하지 않았습니다.
work_log_text는 위 출력 내용을 복사해서 logs/work_log.md에 붙여 넣으면 됩니다.

파일 생성 없이 03번 결과 불러오기

In [1]:
# 03-RELOAD. 파일 생성 없이 03번 중간 분석 데이터 불러오기
# 주의: 이 셀은 기존 parquet 파일을 읽기만 하며, 새 파일을 생성하지 않습니다.

from pathlib import Path
from google.colab import drive
import pandas as pd
import numpy as np
import re
import unicodedata

# ------------------------------------------------------------
# 1) Google Drive 마운트
# ------------------------------------------------------------

drive.mount('/content/drive', force_remount=True)

MYDRIVE = Path('/content/drive/MyDrive')

# ------------------------------------------------------------
# 2) PA Factory 폴더 찾기
# ------------------------------------------------------------

pa_candidates = [
    p for p in MYDRIVE.iterdir()
    if p.is_dir() and 'PA Factory' in p.name
]

print("파공장 후보 폴더 수:", len(pa_candidates))

for i, p in enumerate(pa_candidates, start=1):
    print(f"{i}. {p}")

if len(pa_candidates) != 1:
    raise FileNotFoundError(
        "PA Factory 폴더를 정확히 1개 찾지 못했습니다. "
        "Drive 바로가기 또는 폴더명을 확인하세요."
    )

PA_FACTORY_DIR = pa_candidates[0]

# ------------------------------------------------------------
# 3) 03번 중간 분석 parquet 찾기
# ------------------------------------------------------------

analysis_candidates = list(
    PA_FACTORY_DIR.rglob('03_project_name_text_analysis_v1_*.parquet')
)

# final 폴더 안의 파일 우선
final_candidates = [
    p for p in analysis_candidates
    if 'tables/final' in str(p).replace('\\', '/')
]

print("\n03번 parquet 후보 수:", len(analysis_candidates))
print("final 폴더 후보 수:", len(final_candidates))

if len(final_candidates) > 0:
    ANALYSIS_FILE = sorted(final_candidates)[-1]
elif len(analysis_candidates) > 0:
    ANALYSIS_FILE = sorted(analysis_candidates)[-1]
else:
    raise FileNotFoundError(
        "03_project_name_text_analysis_v1_*.parquet 파일을 찾지 못했습니다."
    )

print("\n사용할 03번 중간 분석 파일:")
print(ANALYSIS_FILE)

# ------------------------------------------------------------
# 4) 경로 변수 복원
# ------------------------------------------------------------

FINAL_DIR = ANALYSIS_FILE.parent
TABLE_DIR = FINAL_DIR.parent
OUTPUT_DIR = TABLE_DIR.parent
FIGURE_DIR = OUTPUT_DIR / 'figures'

print("\n복원된 경로")
print("OUTPUT_DIR:", OUTPUT_DIR)
print("TABLE_DIR:", TABLE_DIR)
print("FINAL_DIR:", FINAL_DIR)
print("FIGURE_DIR:", FIGURE_DIR)

# ------------------------------------------------------------
# 5) 03번 데이터 불러오기
# ------------------------------------------------------------

df_03_analysis = pd.read_parquet(ANALYSIS_FILE)

# 기존 코드와 호환되도록 df_text 이름도 같이 사용
df_text = df_03_analysis.copy()

print("\n03번 중간 분석 데이터 불러오기 완료")
print("- 행 수:", df_text.shape[0])
print("- 열 수:", df_text.shape[1])

# ------------------------------------------------------------
# 6) 주요 열 확인
# ------------------------------------------------------------

key_cols = [
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'tokens_raw',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter'
]

print("\n주요 열 존재 여부")
for col in key_cols:
    print(f"- {col}: {col in df_text.columns}")

# ------------------------------------------------------------
# 7) 빈도표 생성 함수 복원
# ------------------------------------------------------------

def make_token_freq(df, token_col):
    """
    리스트 형태 토큰 열을 펼쳐 빈도표를 생성합니다.
    새 파일을 저장하지 않고 메모리에서만 생성합니다.
    """
    token_long = (
        df[[token_col]]
        .explode(token_col)
        .rename(columns={token_col: 'token'})
        .dropna()
        .copy()
    )

    token_long['token'] = token_long['token'].astype(str).str.strip()
    token_long = token_long[token_long['token'] != '']

    token_freq = (
        token_long['token']
        .value_counts()
        .reset_index()
    )

    token_freq.columns = ['token', 'freq']
    token_freq['ratio_percent'] = (
        token_freq['freq'] / token_freq['freq'].sum() * 100
    ).round(4)

    return token_freq

# ------------------------------------------------------------
# 8) 기존 빈도표를 메모리에서만 재생성
# ------------------------------------------------------------

token_freq_analysis_primary = make_token_freq(
    df_text,
    'tokens_analysis_primary'
)

token_freq_second_filter = make_token_freq(
    df_text,
    'tokens_analysis_second_filter'
)

print("\n빈도표 메모리 재생성 완료")
print("- token_freq_analysis_primary 행 수:", len(token_freq_analysis_primary))
print("- token_freq_second_filter 행 수:", len(token_freq_second_filter))

print("\n기본 분석용 토큰 빈도 상위 20개")
display(token_freq_analysis_primary.head(20))

print("\n재시작 후 작업 준비 완료")
print("이 셀은 새 파일을 생성하지 않았습니다.")

Mounted at /content/drive
파공장 후보 폴더 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)

03번 parquet 후보 수: 1
final 폴더 후보 수: 1

사용할 03번 중간 분석 파일:
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260526_1935.parquet

복원된 경로
OUTPUT_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석
TABLE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables
FINAL_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final
FIGURE_DIR: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/figures

03번 중간 분석 데이터 불러오기 완료
- 행 수: 79262
- 열 수: 41

주요 열 존재 여부
- 사업명: True
- 사업명_clean: True
- 사업명_clean_spacefix: True
- tokens_raw: True
- tokens_analysis_primary: True
- tokens_analysis_second_filter: True

빈도표 메모리 재생성 완료
- token_freq_analysis_primary 행 수: 18151
- token_freq_second_filter 행 수: 18139

기본 분석용 토큰 빈도 상위 20개

   token  freq  ratio_percent
0     대회  8704         2.6248
1    장애인  5392         1.6260
2     체육  4031         1.2156
3     행사  3885         1.1716
4     시설  3395         1.0238
5     센터  2807         0.8465
6     문화  2728         0.8227
7     교육  2508         0.7563
8     단체  2467         0.7440
9     지역  2447         0.7379
10    생활  2439         0.7355
11    전국  2363         0.7126
12    활동  2324         0.7008
13    마을  2288         0.6900
14    환경  2051         0.6185
15    개선  1920         0.5790
16    활성  1807         0.5449
17    복지  1784         0.5380
18   경로당  1720         0.5187
19    육성  1629         0.4913

재시작 후 작업 준비 완료
이 셀은 새 파일을 생성하지 않았습니다.

03-SUPP-1. V1 원자료 기준 v1_row_id 및 메타열 보강 준비
1. 이 단계의 목적

현재 메모리에 복원된 기존 03번 master df_text에 대해, 원본 V1 데이터의 행 순서를 기준으로 v1_row_id를 보강합니다.

핵심은 다음입니다.

기존 토큰화 결과는 건드리지 않음
기존 사업명, 사업명_clean, tokens_analysis_primary 등은 변경하지 않음
원본 V1의 행 순서 기준으로 v1_row_id 생성
사업명 결측 14행을 제외한 79,262행과 현재 03번 master가 같은 순서인지 검증
가능하면 원파일명도 원본 V1에서 가져와 보강

In [2]:
# 03-SUPP-1. V1 원자료 기준 v1_row_id 및 메타열 보강 준비
# 주의: 이 셀은 파일을 저장하지 않습니다.

from pathlib import Path
import pandas as pd
import numpy as np
import re
import unicodedata
from datetime import datetime
from zoneinfo import ZoneInfo

# ------------------------------------------------------------
# 1) 현재 03번 master 데이터 확인
# ------------------------------------------------------------

if 'df_text' not in globals():
    raise NameError(
        "df_text가 없습니다. 먼저 03번 master parquet을 불러오는 RELOAD 셀을 실행하세요."
    )

print("현재 df_text 상태")
print("- 행 수:", len(df_text))
print("- 열 수:", df_text.shape[1])

required_current_cols = [
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'tokens_raw',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter'
]

print("\n현재 03번 master 주요 열 존재 여부")
for col in required_current_cols:
    print(f"- {col}:", col in df_text.columns)


# ------------------------------------------------------------
# 2) 원본 V1 parquet 파일 찾기
# ------------------------------------------------------------
# 기존 RELOAD 셀에서 PA_FACTORY_DIR이 있으면 사용하고,
# 없으면 /content/drive/MyDrive 아래에서 다시 찾습니다.

if 'PA_FACTORY_DIR' not in globals():
    MYDRIVE = Path('/content/drive/MyDrive')
    pa_candidates = [
        p for p in MYDRIVE.iterdir()
        if p.is_dir() and 'PA Factory' in p.name
    ]

    if len(pa_candidates) != 1:
        raise FileNotFoundError(
            "PA Factory 폴더를 정확히 1개 찾지 못했습니다. "
            "Drive 마운트와 바로가기 위치를 확인하세요."
        )

    PA_FACTORY_DIR = pa_candidates[0]

v1_candidates = list(
    PA_FACTORY_DIR.rglob('all_clean_data_v1_20260523_0054_KST.parquet')
)

print("\n원본 V1 parquet 후보 수:", len(v1_candidates))

for i, p in enumerate(v1_candidates, start=1):
    print(f"{i}. {p}")

if len(v1_candidates) == 0:
    raise FileNotFoundError(
        "all_clean_data_v1_20260523_0054_KST.parquet 파일을 찾지 못했습니다."
    )

# 이름이 정확히 같다면 보통 1개지만, 혹시 여러 개면 경로에 01_v1_분석데이터가 포함된 것을 우선 사용
preferred_v1 = [
    p for p in v1_candidates
    if '01_v1_' in str(p) or '01_v1_' in unicodedata.normalize('NFC', str(p))
]

if len(preferred_v1) > 0:
    V1_FILE = sorted(preferred_v1)[-1]
else:
    V1_FILE = sorted(v1_candidates)[-1]

print("\n사용할 원본 V1 파일:")
print(V1_FILE)


# ------------------------------------------------------------
# 3) 원본 V1 데이터 불러오기 및 v1_row_id 생성
# ------------------------------------------------------------

df_v1 = pd.read_parquet(V1_FILE).copy()

# 원본 V1 행 순서를 안정적으로 보존하는 식별자
if 'v1_row_id' not in df_v1.columns:
    df_v1['v1_row_id'] = df_v1.index.astype(int)

print("\n원본 V1 데이터")
print("- 행 수:", len(df_v1))
print("- 열 수:", df_v1.shape[1])
print("- v1_row_id 최소:", df_v1['v1_row_id'].min())
print("- v1_row_id 최대:", df_v1['v1_row_id'].max())
print("- v1_row_id 중복 수:", int(df_v1['v1_row_id'].duplicated().sum()))

print("\n원본 V1 열 목록")
for col in df_v1.columns:
    print("-", col)


# ------------------------------------------------------------
# 4) 원본 V1에서 텍스트 분석 대상 행만 분리
# ------------------------------------------------------------
# 03번에서는 사업명 결측 14행을 텍스트 분석 대상에서 제외했습니다.
# 여기서도 같은 기준으로 V1의 텍스트 분석 대상 행을 만듭니다.

if '사업명' not in df_v1.columns:
    raise KeyError("원본 V1 데이터에 '사업명' 열이 없습니다.")

v1_project_name_text = df_v1['사업명'].fillna('').astype(str).str.strip()

v1_project_name_missing_or_blank = (
    df_v1['사업명'].isna() |
    v1_project_name_text.eq('')
)

df_v1_text = df_v1.loc[~v1_project_name_missing_or_blank].copy()

print("\n원본 V1 기준 텍스트 분석 대상")
print("- V1 전체 행 수:", len(df_v1))
print("- 사업명 결측/공백 제외 행 수:", len(df_v1_text))
print("- 제외 행 수:", int(v1_project_name_missing_or_blank.sum()))

if len(df_v1_text) != len(df_text):
    raise ValueError(
        f"행 수가 맞지 않습니다. df_v1_text={len(df_v1_text)}, df_text={len(df_text)}. "
        "03번 master와 V1 텍스트 대상 행의 정렬 기준을 다시 확인해야 합니다."
    )


# ------------------------------------------------------------
# 5) df_text와 df_v1_text의 사업명 순서 일치 여부 확인
# ------------------------------------------------------------
# v1_row_id를 행 순서로 붙이려면 두 데이터의 행 순서가 같아야 합니다.
# 원본 사업명 기준으로 순서 일치 여부를 확인합니다.

def normalize_compare_text(s):
    if pd.isna(s):
        return ''
    return unicodedata.normalize('NFC', str(s)).strip()

text_03 = df_text['사업명'].apply(normalize_compare_text).reset_index(drop=True)
text_v1 = df_v1_text['사업명'].apply(normalize_compare_text).reset_index(drop=True)

alignment_match = text_03.eq(text_v1)
alignment_mismatch_count = int((~alignment_match).sum())

print("\n03번 master와 V1 텍스트 대상 사업명 순서 비교")
print("- 순서 불일치 행 수:", alignment_mismatch_count)

if alignment_mismatch_count > 0:
    mismatch_sample = pd.DataFrame({
        'pos': np.where(~alignment_match)[0],
        '사업명_03': text_03[~alignment_match].values,
        '사업명_v1': text_v1[~alignment_match].values
    }).head(20)

    print("\n순서 불일치 샘플")
    display(mismatch_sample)

    raise ValueError(
        "df_text와 df_v1_text의 사업명 순서가 일치하지 않습니다. "
        "v1_row_id를 단순 행 순서로 붙이면 위험합니다."
    )

print("사업명 순서가 일치합니다. v1_row_id를 행 순서 기준으로 보강할 수 있습니다.")


# ------------------------------------------------------------
# 6) 원파일명 후보 열 탐색
# ------------------------------------------------------------
# 프로젝트에서 파일 식별 메타열 이름이 원파일명/원본파일명/source_file/file_name 등으로 다를 수 있어 후보를 탐색합니다.

file_meta_candidates = [
    '원파일명',
    '원본파일명',
    'source_file',
    'file_name',
    '파일명',
    'source_path',
    '원본경로'
]

existing_file_meta_cols = [
    col for col in file_meta_candidates
    if col in df_v1_text.columns
]

print("\n원본 V1에서 발견된 파일 메타열 후보:")
if existing_file_meta_cols:
    for col in existing_file_meta_cols:
        print("-", col)
else:
    print("- 없음")

# 원파일명 표준 열 생성에 사용할 후보
source_file_col = existing_file_meta_cols[0] if existing_file_meta_cols else None

print("\n원파일명 보강에 사용할 열:", source_file_col)


# ------------------------------------------------------------
# 7) df_text_supp 생성 및 v1_row_id / 메타열 보강
# ------------------------------------------------------------
# 기존 df_text는 직접 덮어쓰지 않고, 보강 후보 df_text_supp를 따로 만듭니다.

df_text_supp = df_text.copy()

# v1_row_id가 이미 있으면 비교하고, 없으면 추가합니다.
if 'v1_row_id' in df_text_supp.columns:
    current_id = df_text_supp['v1_row_id'].reset_index(drop=True)
    expected_id = df_v1_text['v1_row_id'].reset_index(drop=True)

    id_mismatch_count = int((current_id != expected_id).sum())
    print("\n기존 v1_row_id 존재")
    print("- 기존 v1_row_id와 V1 기준 v1_row_id 불일치 수:", id_mismatch_count)

    if id_mismatch_count > 0:
        raise ValueError(
            "기존 v1_row_id가 V1 기준과 일치하지 않습니다. "
            "자동 보정하지 말고 원인을 확인해야 합니다."
        )
else:
    df_text_supp['v1_row_id'] = df_v1_text['v1_row_id'].to_numpy()
    print("\nv1_row_id를 새로 추가했습니다.")

# 원파일명 표준 열 보강
if '원파일명' not in df_text_supp.columns:
    if source_file_col is not None:
        df_text_supp['원파일명'] = df_v1_text[source_file_col].to_numpy()
        print(f"'원파일명' 열을 원본 V1의 '{source_file_col}' 열에서 생성했습니다.")
    else:
        df_text_supp['원파일명'] = pd.NA
        print("주의: 원본 V1에서 파일 메타열을 찾지 못해 '원파일명'을 결측으로 생성했습니다.")
else:
    print("'원파일명' 열이 이미 존재합니다.")

# 후속 병합에 필요한 핵심 메타열 중 현재 df_text_supp에 없고 V1에는 있는 열은 보강
meta_cols_to_check = [
    '시도',
    '지자체명',
    '사업명',
    '보조사업자',
    '평가결과',
    '평가종류',
    '사업비합계',
    '보조금',
    '사업자부담'
]

added_meta_cols = []

for col in meta_cols_to_check:
    if col not in df_text_supp.columns and col in df_v1_text.columns:
        df_text_supp[col] = df_v1_text[col].to_numpy()
        added_meta_cols.append(col)

print("\n추가 보강한 메타열:", added_meta_cols if added_meta_cols else "없음")


# ------------------------------------------------------------
# 8) 보강 결과 점검
# ------------------------------------------------------------

v1_row_id_missing = int(df_text_supp['v1_row_id'].isna().sum())
v1_row_id_duplicate = int(df_text_supp['v1_row_id'].duplicated().sum())
v1_row_id_min = int(df_text_supp['v1_row_id'].min())
v1_row_id_max = int(df_text_supp['v1_row_id'].max())

wonfile_exists = '원파일명' in df_text_supp.columns
wonfile_missing = int(df_text_supp['원파일명'].isna().sum()) if wonfile_exists else None

core_required_cols = [
    'v1_row_id',
    '시도',
    '지자체명',
    '원파일명',
    '사업명',
    '보조사업자',
    '평가결과',
    '평가종류'
]

core_col_status = pd.DataFrame({
    '열': core_required_cols,
    '존재여부': [col in df_text_supp.columns for col in core_required_cols],
    '결측수': [
        int(df_text_supp[col].isna().sum()) if col in df_text_supp.columns else None
        for col in core_required_cols
    ]
})

supp_check_summary = pd.DataFrame({
    '항목': [
        '보강 후보 데이터 행 수',
        '보강 후보 데이터 열 수',
        'v1_row_id 결측 수',
        'v1_row_id 중복 수',
        'v1_row_id 최소값',
        'v1_row_id 최대값',
        '원파일명 존재 여부',
        '원파일명 결측 수',
        '사업명 순서 불일치 수'
    ],
    '값': [
        len(df_text_supp),
        df_text_supp.shape[1],
        v1_row_id_missing,
        v1_row_id_duplicate,
        v1_row_id_min,
        v1_row_id_max,
        wonfile_exists,
        wonfile_missing,
        alignment_mismatch_count
    ]
})

print("\n[1] 보강 결과 요약")
display(supp_check_summary)

print("\n[2] 핵심 열 존재 및 결측 확인")
display(core_col_status)

print("\n[3] v1_row_id와 핵심 열 샘플")
sample_cols = [
    'v1_row_id',
    '시도',
    '지자체명',
    '원파일명',
    '사업명',
    '사업명_clean_spacefix',
    'tokens_analysis_primary',
    '보조사업자',
    '평가결과',
    '평가종류'
]
sample_cols = [col for col in sample_cols if col in df_text_supp.columns]
display(df_text_supp[sample_cols].head(20))


# ------------------------------------------------------------
# 9) 04번 handoff 핵심 열 목록
# ------------------------------------------------------------

core_handoff_cols = [
    'v1_row_id',
    '시도',
    '지자체명',
    '원파일명',
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter',
    '보조사업자',
    '평가결과',
    '평가종류'
]

existing_core_handoff_cols = [
    col for col in core_handoff_cols
    if col in df_text_supp.columns
]

print("\n[4] 04번으로 넘길 핵심 열 목록")
for col in existing_core_handoff_cols:
    print("-", col)

print("\n03-SUPP-1 완료")
print("이 셀은 파일을 저장하지 않았습니다.")
print("위 결과에서 v1_row_id 결측 0, 중복 0, 사업명 순서 불일치 0이면 다음 저장 셀로 넘어가면 됩니다.")

현재 df_text 상태
- 행 수: 79262
- 열 수: 41

현재 03번 master 주요 열 존재 여부
- 사업명: True
- 사업명_clean: True
- 사업명_clean_spacefix: True
- tokens_raw: True
- tokens_analysis_primary: True
- tokens_analysis_second_filter: True

원본 V1 parquet 후보 수: 1
1. /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet

사용할 원본 V1 파일:
/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/01_v1_분석데이터/all_clean_data_v1_20260523_0054_KST.parquet

원본 V1 데이터
- 행 수: 79276
- 열 수: 13
- v1_row_id 최소: 0
- v1_row_id 최대: 79275
- v1_row_id 중복 수: 0

원본 V1 열 목록
- 시도
- 지자체명
- 파일상태
- 원파일명
- 파일경로
- 사업명
- 보조사업자
- 사업비합계
- 보조금
- 사업자부담
- 평가결과
- 평가종류
- v1_row_id

원본 V1 기준 텍스트 분석 대상
- V1 전체 행 수: 79276
- 사업명 결측/공백 제외 행 수: 79262
- 제외 행 수: 14

03번 master와 V1 텍스트 대상 사업명 순서 비교
- 순서 불일치 행 수: 0
사업명 순서가 일치합니다. v1_row_id를 행 순서 기준으로 보강할 수 있습니다.

원본 V1에서 발견된 파일 메타열 후보:
- 원파일명

원파일명 보강에 사용할 열: 원파일명

v1_row_id를 새로 추가했습니다.
'원파일명' 열을 원본 V1의 '원파일명' 열에서 생성했습니다.

추가 보강한 메타열: 없음

[1] 보강 결과 요약

               항목      값
0   보강 후보 데이터 행 수  79262
1   보강 후보 데이터 열 수     43
2  v1_row_id 결측 수      0
3  v1_row_id 중복 수      0
4   v1_row_id 최소값      0
5   v1_row_id 최대값  79275
6      원파일명 존재 여부   True
7       원파일명 결측 수      0
8    사업명 순서 불일치 수      0

[2] 핵심 열 존재 및 결측 확인

           열  존재여부   결측수
0  v1_row_id  True     0
1         시도  True     0
2       지자체명  True     0
3       원파일명  True     0
4        사업명  True     0
5      보조사업자  True   182
6       평가결과  True    78
7       평가종류  True  1466

[3] v1_row_id와 핵심 열 샘플

,v1_row_id,시도,지자체명,원파일명,사업명,사업명_clean_spacefix,tokens_analysis_primary,보조사업자,평가결과,평가종류
0,0,경남,남해군,경남_남해군.xlsx,마늘재배 영농지원단 지원,마늘재배 영농지원단 지원,"[마늘, 재배, 영농, 지원단]",농협중앙회 남해군지부,매우우수,유지필요성평가
1,1,경남,남해군,경남_남해군.xlsx,2023년 사)진주지역범죄피해자지원센터‘등불 ’남해지부 운영,2023년 사)진주지역범죄피해자지원센터'등불 '남해지부 운영,"[지역, 범죄, 피해자, 센터, 등불, 지부]",사단법인진주지역범죄피 해자지원센터남해지부,미흡,유지필요성평가
2,2,경남,남해군,경남_남해군.xlsx,자유민주주의신장 및 자유선진의식 고취,자유민주주의신장 및 자유선진의식 고취,"[자유, 민주주의, 신장, 자유선진, 의식, 고취]",한국자유총연맹남해군지 회,미흡,유지필요성평가
3,3,경남,남해군,경남_남해군.xlsx,보물섬 독서학교 지원,보물섬 독서학교 지원,"[보물섬, 독서, 학교]",보물섬남해독서학교,미흡,유지필요성평가
4,4,경남,남해군,경남_남해군.xlsx,참전경찰유공자 보훈활동,참전경찰유공자 보훈활동,"[참전, 경찰, 유공자, 보훈, 활동]",한국참전경찰유공자회,미흡,유지필요성평가
5,5,경남,남해군,경남_남해군.xlsx,무공수훈자회 운영비 보조,무공수훈자회 운영비 보조,"[무공, 수훈자]",대한민국무공수훈자회남 해 군 지 회,미흡,유지필요성평가
6,6,경남,남해군,경남_남해군.xlsx,행복나눔센터 운영,행복나눔센터 운영,"[행복, 센터]",남해군지역사회보장협의 체,미흡,유지필요성평가
7,7,경남,남해군,경남_남해군.xlsx,경로당 양곡구입비 지원,경로당 양곡구입비 지원,"[경로당, 양곡, 구입비]",봉내경로당 외 10개소,미흡,유지필요성평가
8,8,경남,남해군,경남_남해군.xlsx,장애인직업재활 자활교육,장애인직업재활 자활교육,"[장애인, 직업, 재활, 자활, 교육]",남해장애인종합복지관,미흡,유지필요성평가
9,9,경남,남해군,경남_남해군.xlsx,어린이집 운전기사 인건비 (미조지역영유아수송),어린이집 운전기사 인건비 (미조지역영유아수송),"[어린이집, 운전기사, 미조, 지역, 영유아, 수송]",모 모 어 린 이 집,미흡,유지필요성평가
10,10,경남,남해군,경남_남해군.xlsx,아동 일일나들이 행사,아동 일일나들이 행사,"[아동, 일일, 나들이, 행사]",남해군아동위원 협의회,미흡,유지필요성평가
11,11,경남,남해군,경남_남해군.xlsx,문화학교 운영,문화학교 운영,"[문화, 학교]",남 해 문 화 원,미흡,유지필요성평가
12,12,경남,남해군,경남_남해군.xlsx,남중권생활체육 교류 지원,남중권생활체육 교류 지원,"[남, 생활, 체육, 교류]",남 해 군 체 육 회,미흡,유지필요성평가
13,13,경남,남해군,경남_남해군.xlsx,"전국대회 운영(구급차, 응급의료 등) 지원","전국대회 운영(구급차, 응급의료 등) 지원","[전국, 대회, 구급차, 응급, 의료]",남 해 군 체 육 회,미흡,유지필요성평가
14,14,경남,남해군,경남_남해군.xlsx,레포츠 자격증 취득 지원,레포츠 자격증 취득 지원,"[레포츠, 자격증, 취득]",남 해 군 체 육 회,미흡,유지필요성평가
15,15,경남,남해군,경남_남해군.xlsx,수산물 상생할인 지원사업,수산물 상생할인 지원사업,"[수산물, 상생, 할인]",남 해 군 수 협,미흡,유지필요성평가
16,16,경남,남해군,경남_남해군.xlsx,마을어장 개발,마을어장 개발,"[마을, 어장, 개발]",갈화어촌계 외 6 개소,미흡,유지필요성평가
17,17,경남,남해군,경남_남해군.xlsx,자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),자연환경 보전활동 사업 (자연보호정화활동및군수기경진대회),"[자연, 환경, 보전, 활동, 자연보호, 정화, 활동, 수기, 경진, 대회]",(사)자연보호연맹남해군협의회,미흡,유지필요성평가
18,18,경남,남해군,경남_남해군.xlsx,2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),2023년 음식점 위생환경 개선사업 (시설환경개선및입식테이블지원),"[음식점, 위생, 환경, 개선, 시설, 환경, 개선, 입식, 테이블]",갯내음 외 1 9 개소,미흡,유지필요성평가
19,19,경남,남해군,경남_남해군.xlsx,농촌신활력 플러스사업 (추진단사무국상근직원인건비),농촌신활력 플러스사업 (추진단사무국상근직원인건비),"[농촌신활력, 플러스사업, 추진단, 사무국, 상근, 직원]",남해군신활력플러스사업추진단,미흡,유지필요성평가

[4] 04번으로 넘길 핵심 열 목록
- v1_row_id
- 시도
- 지자체명
- 원파일명
- 사업명
- 사업명_clean
- 사업명_clean_spacefix
- tokens_analysis_primary
- tokens_analysis_second_filter
- 보조사업자
- 평가결과
- 평가종류

03-SUPP-1 완료
이 셀은 파일을 저장하지 않았습니다.
위 결과에서 v1_row_id 결측 0, 중복 0, 사업명 순서 불일치 0이면 다음 저장 셀로 넘어가면 됩니다.

03-SUPP-2. 식별자 보강 03번 master 새 파일 저장

03-SUPP-1 결과가 정상일 때만 아래 셀을 실행하면 됩니다.

1. 이 단계의 목적

df_text_supp를 새 03번 master 파일로 저장합니다.

기존 파일은 덮어쓰지 않고, 새 timestamp를 붙여 저장합니다.

In [3]:
# 03-SUPP-2. 식별자 보강 03번 master 새 파일 저장
# 주의: 기존 파일을 덮어쓰지 않고 새 timestamp로 저장합니다.

from zoneinfo import ZoneInfo

# ------------------------------------------------------------
# 1) 저장 전 필수 객체 확인
# ------------------------------------------------------------

if 'df_text_supp' not in globals():
    raise NameError("df_text_supp가 없습니다. 먼저 03-SUPP-1 셀을 실행하세요.")

if 'FINAL_DIR' not in globals():
    raise NameError("FINAL_DIR이 없습니다. 먼저 RELOAD 셀을 실행하세요.")

FINAL_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 2) 저장 전 최종 안전 점검
# ------------------------------------------------------------

required_save_cols = [
    'v1_row_id',
    '시도',
    '지자체명',
    '원파일명',
    '사업명',
    '보조사업자',
    '평가결과',
    '평가종류',
    '사업명_clean_spacefix',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter'
]

missing_required_save_cols = [
    col for col in required_save_cols
    if col not in df_text_supp.columns
]

if missing_required_save_cols:
    print("주의: 저장 전 필수 후보 열 중 누락된 열이 있습니다.")
    for col in missing_required_save_cols:
        print("-", col)

# v1_row_id는 반드시 정상이어야 저장 진행
if 'v1_row_id' not in df_text_supp.columns:
    raise KeyError("v1_row_id가 없어 저장할 수 없습니다.")

if df_text_supp['v1_row_id'].isna().sum() > 0:
    raise ValueError("v1_row_id 결측이 있어 저장을 중단합니다.")

if df_text_supp['v1_row_id'].duplicated().sum() > 0:
    raise ValueError("v1_row_id 중복이 있어 저장을 중단합니다.")

# ------------------------------------------------------------
# 3) 저장 전 요약 생성
# ------------------------------------------------------------

save_check_summary_supp = pd.DataFrame({
    '항목': [
        '저장 데이터 행 수',
        '저장 데이터 열 수',
        'v1_row_id 결측 수',
        'v1_row_id 중복 수',
        'v1_row_id 최소값',
        'v1_row_id 최대값',
        '원파일명 존재 여부',
        '원파일명 결측 수',
        'tokens_raw 빈 행 수',
        'tokens_analysis_primary 빈 행 수',
        'tokens_analysis_second_filter 빈 행 수'
    ],
    '값': [
        len(df_text_supp),
        df_text_supp.shape[1],
        int(df_text_supp['v1_row_id'].isna().sum()),
        int(df_text_supp['v1_row_id'].duplicated().sum()),
        int(df_text_supp['v1_row_id'].min()),
        int(df_text_supp['v1_row_id'].max()),
        '원파일명' in df_text_supp.columns,
        int(df_text_supp['원파일명'].isna().sum()) if '원파일명' in df_text_supp.columns else None,
        int(df_text_supp['tokens_raw_empty'].sum()) if 'tokens_raw_empty' in df_text_supp.columns else None,
        int(df_text_supp['tokens_analysis_primary_empty'].sum()) if 'tokens_analysis_primary_empty' in df_text_supp.columns else None,
        int(df_text_supp['tokens_analysis_second_filter_empty'].sum()) if 'tokens_analysis_second_filter_empty' in df_text_supp.columns else None
    ]
})

print("저장 전 최종 점검")
display(save_check_summary_supp)

# ------------------------------------------------------------
# 4) 저장 파일명 설정
# ------------------------------------------------------------

timestamp = datetime.now(ZoneInfo("Asia/Seoul")).strftime('%Y%m%d_%H%M')

supp_master_parquet = FINAL_DIR / f'03_project_name_text_analysis_v1_{timestamp}.parquet'
supp_sample_xlsx = FINAL_DIR / f'03_project_name_text_analysis_sample_v1_{timestamp}.xlsx'
supp_columns_csv = FINAL_DIR / f'03_project_name_text_analysis_columns_v1_{timestamp}.csv'
supp_save_check_csv = FINAL_DIR / f'03_project_name_text_analysis_save_check_v1_{timestamp}.csv'
supp_handoff_memo_txt = FINAL_DIR / f'03_handoff_memo_for_04_v1_{timestamp}.txt'

# ------------------------------------------------------------
# 5) 파일 저장
# ------------------------------------------------------------

df_text_supp.to_parquet(supp_master_parquet, index=False)

# 샘플은 기존처럼 head(1000) 저장
# 전체 대표 샘플이 아니라 구조 확인용임
df_text_supp.head(1000).to_excel(supp_sample_xlsx, index=False)

columns_df_supp = pd.DataFrame({
    'column_order': range(1, len(df_text_supp.columns) + 1),
    'column_name': df_text_supp.columns
})

columns_df_supp.to_csv(supp_columns_csv, index=False, encoding='utf-8-sig')
save_check_summary_supp.to_csv(supp_save_check_csv, index=False, encoding='utf-8-sig')

# ------------------------------------------------------------
# 6) 04번 전달 메모 생성
# ------------------------------------------------------------

new_master_name = supp_master_parquet.name

core_handoff_cols = [
    'v1_row_id',
    '시도',
    '지자체명',
    '원파일명',
    '사업명',
    '사업명_clean',
    '사업명_clean_spacefix',
    'tokens_analysis_primary',
    'tokens_analysis_second_filter',
    '보조사업자',
    '평가결과',
    '평가종류'
]

existing_core_handoff_cols = [
    col for col in core_handoff_cols
    if col in df_text_supp.columns
]

handoff_memo = f"""
# 04번 노트북 전달 메모

## 새 03번 master 파일

04번 정책분야 분석에서는 아래 파일을 입력으로 사용한다.

`{new_master_name}`

Drive 경로:

`{FINAL_DIR}`

## 사용 이유

이 파일은 기존 03번 master에 원본 V1 행 식별자인 `v1_row_id`와 후속 병합에 필요한 메타열을 보강한 버전이다.

기존 토큰화 결과, 불용어 처리 결과, 정책어휘 빈도 결과는 임의로 변경하지 않았다.

## 행 수 기준

- 원본 V1 데이터 행 수: 79,276행
- 03번 텍스트 분석 master 행 수: 79,262행
- V1 79,276행 중 `사업명` 결측 14행은 텍스트 분석용 데이터에서 제외되었다.
- 원본 행 식별자인 `v1_row_id`는 V1 데이터의 원래 행 순서를 기준으로 한다.

## 병합 기준

- `v1_row_id`를 05번 병합의 우선 식별자로 사용할 수 있다.
- 04번에서 정책분야 변수를 만든 뒤 05번 또는 06B번으로 넘길 때도 `v1_row_id`를 함께 보존해야 한다.

## 04번에서 사용할 핵심 열

{chr(10).join(['- `' + col + '`' for col in existing_core_handoff_cols])}

## 토큰 열 기준

- `tokens_analysis_primary`: 04번 기본 참고 토큰
- `tokens_analysis_second_filter`: 2차 불용어 제거 비교용 토큰
- 두 열의 차이는 지역명 제거 방식이 아니라 2차 불용어 적용 여부이다.

## 주의사항

- 원본 `사업명`은 덮어쓰지 않는다.
- 04번 정책분야 분류는 공식 행정분류 확정값이 아니라 사업명 텍스트 기반 탐색용 분류이다.
- 애매한 사례는 `검토필요`, `기타`, `복합` 등으로 남긴다.
"""

with open(supp_handoff_memo_txt, 'w', encoding='utf-8') as f:
    f.write(handoff_memo)

# ------------------------------------------------------------
# 7) 저장 결과 출력
# ------------------------------------------------------------

print("\n03-SUPP-2 저장 완료")
print("- 새 03번 master parquet:", supp_master_parquet)
print("- 확인용 sample Excel:", supp_sample_xlsx)
print("- columns CSV:", supp_columns_csv)
print("- save_check CSV:", supp_save_check_csv)
print("- 04번 handoff memo:", supp_handoff_memo_txt)

print("\n저장 파일 존재 여부")
print("- supp_master_parquet:", supp_master_parquet.exists())
print("- supp_sample_xlsx:", supp_sample_xlsx.exists())
print("- supp_columns_csv:", supp_columns_csv.exists())
print("- supp_save_check_csv:", supp_save_check_csv.exists())
print("- supp_handoff_memo_txt:", supp_handoff_memo_txt.exists())

print("\n저장 결과 핵심값")
print("- 저장 파일명:", supp_master_parquet.name)
print("- 행 수:", len(df_text_supp))
print("- 열 수:", df_text_supp.shape[1])
print("- v1_row_id 결측 수:", int(df_text_supp['v1_row_id'].isna().sum()))
print("- v1_row_id 중복 수:", int(df_text_supp['v1_row_id'].duplicated().sum()))
print("- v1_row_id 최소값:", int(df_text_supp['v1_row_id'].min()))
print("- v1_row_id 최대값:", int(df_text_supp['v1_row_id'].max()))
print("- 원파일명 존재 여부:", '원파일명' in df_text_supp.columns)
print("- 원파일명 결측 수:", int(df_text_supp['원파일명'].isna().sum()) if '원파일명' in df_text_supp.columns else None)

print("\n04번으로 넘길 핵심 열 목록")
for col in existing_core_handoff_cols:
    print("-", col)

print("\n04번 전달 메모")
print(handoff_memo)

저장 전 최종 점검

                                     항목      값
0                            저장 데이터 행 수  79262
1                            저장 데이터 열 수     43
2                        v1_row_id 결측 수      0
3                        v1_row_id 중복 수      0
4                         v1_row_id 최소값      0
5                         v1_row_id 최대값  79275
6                            원파일명 존재 여부   True
7                             원파일명 결측 수      0
8                      tokens_raw 빈 행 수      4
9         tokens_analysis_primary 빈 행 수     61
10  tokens_analysis_second_filter 빈 행 수     62

03-SUPP-2 저장 완료
- 새 03번 master parquet: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_v1_20260529_0135.parquet
- 확인용 sample Excel: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_sample_v1_20260529_0135.xlsx
- columns CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_columns_v1_20260529_0135.csv
- save_check CSV: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_project_name_text_analysis_save_check_v1_20260529_0135.csv
- 04번 handoff memo: /content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final/03_handoff_memo_for_04_v1_20260529_0135.txt

저장 파일 존재 여부
- supp_master_parquet: True
- supp_sample_xlsx: True
- supp_columns_csv: True
- supp_save_check_csv: True
- supp_handoff_memo_txt: True

저장 결과 핵심값
- 저장 파일명: 03_project_name_text_analysis_v1_20260529_0135.parquet
- 행 수: 79262
- 열 수: 43
- v1_row_id 결측 수: 0
- v1_row_id 중복 수: 0
- v1_row_id 최소값: 0
- v1_row_id 최대값: 79275
- 원파일명 존재 여부: True
- 원파일명 결측 수: 0

04번으로 넘길 핵심 열 목록
- v1_row_id
- 시도
- 지자체명
- 원파일명
- 사업명
- 사업명_clean
- 사업명_clean_spacefix
- tokens_analysis_primary
- tokens_analysis_second_filter
- 보조사업자
- 평가결과
- 평가종류

04번 전달 메모

# 04번 노트북 전달 메모

## 새 03번 master 파일

04번 정책분야 분석에서는 아래 파일을 입력으로 사용한다.

`03_project_name_text_analysis_v1_20260529_0135.parquet`

Drive 경로:

`/content/drive/MyDrive/파공장 (PA Factory)/2026 KAPA/[guide & output] 분석 협업 매뉴얼 및 Figure 후보/03_중간결과표/03_v1_사업명텍스트분석/tables/final`

## 사용 이유

이 파일은 기존 03번 master에 원본 V1 행 식별자인 `v1_row_id`와 후속 병합에 필요한 메타열을 보강한 버전이다.

기존 토큰화 결과, 불용어 처리 결과, 정책어휘 빈도 결과는 임의로 변경하지 않았다.

## 행 수 기준

- 원본 V1 데이터 행 수: 79,276행
- 03번 텍스트 분석 master 행 수: 79,262행
- V1 79,276행 중 `사업명` 결측 14행은 텍스트 분석용 데이터에서 제외되었다.
- 원본 행 식별자인 `v1_row_id`는 V1 데이터의 원래 행 순서를 기준으로 한다.

## 병합 기준

- `v1_row_id`를 05번 병합의 우선 식별자로 사용할 수 있다.
- 04번에서 정책분야 변수를 만든 뒤 05번 또는 06B번으로 넘길 때도 `v1_row_id`를 함께 보존해야 한다.

## 04번에서 사용할 핵심 열

- `v1_row_id`
- `시도`
- `지자체명`
- `원파일명`
- `사업명`
- `사업명_clean`
- `사업명_clean_spacefix`
- `tokens_analysis_primary`
- `tokens_analysis_second_filter`
- `보조사업자`
- `평가결과`
- `평가종류`

## 토큰 열 기준

- `tokens_analysis_primary`: 04번 기본 참고 토큰
- `tokens_analysis_second_filter`: 2차 불용어 제거 비교용 토큰
- 두 열의 차이는 지역명 제거 방식이 아니라 2차 불용어 적용 여부이다.

## 주의사항

- 원본 `사업명`은 덮어쓰지 않는다.
- 04번 정책분야 분류는 공식 행정분류 확정값이 아니라 사업명 텍스트 기반 탐색용 분류이다.
- 애매한 사례는 `검토필요`, `기타`, `복합` 등으로 남긴다.